/**
 * TTS model registry — central source of truth for text-to-speech.
 *
 * Pricing convention:
 *   providerCostUsdPerMillionChars  — what the provider charges per Mchar
 *   fiatPriceUsdPerMillionChars     — providerCost × FIAT_MARGIN
 *   loarPriceUsdPerMillionChars     — providerCost × LOAR_MARGIN
 *   creditCostPer1kChars            — ceil((fiat / 1000) / LOAR_TO_USD)
 *
 * For per-second / per-token TTS (OpenAI realtime), convert to per-Mchar
 * using a 4 chars-per-token, ~120 wpm rule of thumb at integration time —
 * the realtime variants live in `realtime-voice` (future registry), not here.
 */
import type { TtsModelConfig, TtsVoicePreset } from './types';

export { FIAT_MARGIN, LOAR_MARGIN, LOAR_TO_USD } from '../video-models/registry';
import { FIAT_MARGIN, LOAR_MARGIN, LOAR_TO_USD } from '../video-models/registry';

function withFiatMargin(c: number): number {
  return Math.round(c * FIAT_MARGIN * 100) / 100;
}
function withLoarMargin(c: number): number {
  return Math.round(c * LOAR_MARGIN * 100) / 100;
}
function usdToCreditsPer1k(perMillion: number): number {
  // perMillion USD / 1000 = USD/1k chars; convert to credits at LOAR_TO_USD
  const perThousandUsd = perMillion / 1000;
  return Math.max(1, Math.ceil(perThousandUsd / LOAR_TO_USD));
}

// ── Voice preset shortcuts ──────────────────────────────────────────────

const OPENAI_VOICES: TtsVoicePreset[] = [
  { id: 'alloy', name: 'Alloy', language: 'multi', gender: 'neutral' },
  { id: 'ash', name: 'Ash', language: 'multi', gender: 'male' },
  { id: 'ballad', name: 'Ballad', language: 'multi', gender: 'female' },
  { id: 'coral', name: 'Coral', language: 'multi', gender: 'female' },
  { id: 'echo', name: 'Echo', language: 'multi', gender: 'male' },
  { id: 'fable', name: 'Fable', language: 'en', gender: 'male', style: 'narrator' },
  { id: 'nova', name: 'Nova', language: 'multi', gender: 'female' },
  { id: 'onyx', name: 'Onyx', language: 'multi', gender: 'male' },
  { id: 'sage', name: 'Sage', language: 'multi', gender: 'neutral' },
  { id: 'shimmer', name: 'Shimmer', language: 'multi', gender: 'female' },
  { id: 'verse', name: 'Verse', language: 'multi', gender: 'neutral' },
  { id: 'marin', name: 'Marin', language: 'multi', gender: 'female' },
  { id: 'cedar', name: 'Cedar', language: 'multi', gender: 'male' },
];

const ELEVENLABS_PRESETS: TtsVoicePreset[] = [
  // A representative subset; full ElevenLabs library is queried at runtime.
  {
    id: '21m00Tcm4TlvDq8ikWAM',
    name: 'Rachel',
    language: 'multi',
    gender: 'female',
    style: 'narration',
  },
  {
    id: 'AZnzlk1XvdvUeBnXmlld',
    name: 'Domi',
    language: 'multi',
    gender: 'female',
    style: 'strong',
  },
  { id: 'EXAVITQu4vr4xnSDxMaL', name: 'Bella', language: 'multi', gender: 'female', style: 'soft' },
  { id: 'ErXwobaYiN019PkySvjV', name: 'Antoni', language: 'multi', gender: 'male', style: 'warm' },
  {
    id: 'MF3mGyEYCl7XYWbV9V6O',
    name: 'Elli',
    language: 'multi',
    gender: 'female',
    style: 'emotional',
  },
  { id: 'TxGEqnHWrfWFTfGW9XjX', name: 'Josh', language: 'multi', gender: 'male', style: 'deep' },
  { id: 'VR6AewLTigWG4xSOukaG', name: 'Arnold', language: 'multi', gender: 'male', style: 'crisp' },
  {
    id: 'pNInz6obpgDQGcFmaJgB',
    name: 'Adam',
    language: 'multi',
    gender: 'male',
    style: 'narrator',
  },
  { id: 'yoZ06aMxZJJ28mfd3POQ', name: 'Sam', language: 'multi', gender: 'male', style: 'raspy' },
];

const DEEPGRAM_AURA2_VOICES: TtsVoicePreset[] = [
  { id: 'aura-2-thalia-en', name: 'Thalia', language: 'en', gender: 'female' },
  { id: 'aura-2-andromeda-en', name: 'Andromeda', language: 'en', gender: 'female' },
  { id: 'aura-2-apollo-en', name: 'Apollo', language: 'en', gender: 'male' },
  { id: 'aura-2-asteria-en', name: 'Asteria', language: 'en', gender: 'female' },
  { id: 'aura-2-athena-en', name: 'Athena', language: 'en', gender: 'female' },
  { id: 'aura-2-orion-en', name: 'Orion', language: 'en', gender: 'male' },
  { id: 'aura-2-zeus-en', name: 'Zeus', language: 'en', gender: 'male', style: 'authoritative' },
  { id: 'aura-2-luna-en', name: 'Luna', language: 'en', gender: 'female' },
  { id: 'aura-2-helena-en', name: 'Helena', language: 'en', gender: 'female' },
  { id: 'aura-2-juno-en', name: 'Juno', language: 'en', gender: 'female' },
  { id: 'aura-2-celeste-es', name: 'Celeste', language: 'es', gender: 'female' },
  { id: 'aura-2-estrella-es', name: 'Estrella', language: 'es', gender: 'female' },
  { id: 'aura-2-nestor-es', name: 'Nestor', language: 'es', gender: 'male' },
];

export const TTS_MODELS: TtsModelConfig[] = [
  // ── ElevenLabs (direct, BYOK preferred) ──────────────────────────────
  {
    id: 'eleven-v3',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs v3 (Multilingual)',
    shortDescription: 'Flagship TTS — 70+ languages, gold-standard realism',
    providerModelId: 'eleven_v3',
    firstAudioLatencyMs: 800,
    maxChars: 10000,
    supportedFormats: ['mp3', 'pcm', 'wav', 'opus'],
    supportedLanguages: [], // empty = all supported langs
    voices: ELEVENLABS_PRESETS,
    supportsVoiceClone: true,
    supportsStyleSteer: true,
    supportsStreaming: true,
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    providerCostUsdPerMillionChars: 206,
    fiatPriceUsdPerMillionChars: withFiatMargin(206),
    loarPriceUsdPerMillionChars: withLoarMargin(206),
    creditCostPer1kChars: usdToCreditsPer1k(206),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'premium', 'multilingual', 'realism'],
    bestFor: 'Hero narration, character VO, premium dub',
  },
  {
    id: 'eleven-multilingual-v2',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Multilingual v2',
    shortDescription: 'Long-form-friendly v2 — 29 languages, balanced quality',
    providerModelId: 'eleven_multilingual_v2',
    firstAudioLatencyMs: 800,
    maxChars: 10000,
    supportedFormats: ['mp3', 'pcm', 'wav'],
    supportedLanguages: [],
    voices: ELEVENLABS_PRESETS,
    supportsVoiceClone: true,
    supportsStyleSteer: false,
    supportsStreaming: true,
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    providerCostUsdPerMillionChars: 165,
    fiatPriceUsdPerMillionChars: withFiatMargin(165),
    loarPriceUsdPerMillionChars: withLoarMargin(165),
    creditCostPer1kChars: usdToCreditsPer1k(165),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'premium', 'multilingual', 'long-form'],
    bestFor: 'Long-form narration (audiobooks, scenes, podcasts)',
  },
  {
    id: 'eleven-flash-v25',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Flash v2.5',
    shortDescription: 'Ultra-low latency (~75ms), 32 languages, 40k char cap',
    providerModelId: 'eleven_flash_v2_5',
    firstAudioLatencyMs: 75,
    maxChars: 40000,
    supportedFormats: ['mp3', 'pcm', 'wav', 'opus', 'mulaw'],
    supportedLanguages: [],
    voices: ELEVENLABS_PRESETS,
    supportsVoiceClone: true,
    supportsStyleSteer: false,
    supportsStreaming: true,
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    providerCostUsdPerMillionChars: 103,
    fiatPriceUsdPerMillionChars: withFiatMargin(103),
    loarPriceUsdPerMillionChars: withLoarMargin(103),
    creditCostPer1kChars: usdToCreditsPer1k(103),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'fast', 'realtime', 'multilingual'],
    bestFor: 'Realtime / interactive voice, agent chat, captions',
  },
  {
    id: 'eleven-turbo-v25',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Turbo v2.5',
    shortDescription: 'Turbo tier — balance of latency and quality',
    providerModelId: 'eleven_turbo_v2_5',
    firstAudioLatencyMs: 250,
    maxChars: 40000,
    supportedFormats: ['mp3', 'pcm', 'wav', 'opus'],
    supportedLanguages: [],
    voices: ELEVENLABS_PRESETS,
    supportsVoiceClone: true,
    supportsStyleSteer: false,
    supportsStreaming: true,
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    providerCostUsdPerMillionChars: 110,
    fiatPriceUsdPerMillionChars: withFiatMargin(110),
    loarPriceUsdPerMillionChars: withLoarMargin(110),
    creditCostPer1kChars: usdToCreditsPer1k(110),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'turbo', 'realtime', 'multilingual'],
    bestFor: 'Realtime with slightly better quality than Flash',
  },

  // ── OpenAI ────────────────────────────────────────────────────────────
  {
    id: 'gpt-4o-mini-tts',
    provider: 'openai',
    displayName: 'GPT-4o Mini TTS (OpenAI)',
    shortDescription: 'Prompt-steerable TTS — emotion/style control via natural language',
    providerModelId: 'gpt-4o-mini-tts',
    firstAudioLatencyMs: 400,
    maxChars: 50000,
    supportedFormats: ['mp3', 'opus', 'aac', 'flac', 'wav', 'pcm'],
    supportedLanguages: [],
    voices: OPENAI_VOICES,
    supportsVoiceClone: false,
    supportsStyleSteer: true,
    supportsStreaming: true,
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'medium',
    providerCostUsdPerMillionChars: 12, // ~$12/M chars (audio out, ignoring text-in pennies)
    fiatPriceUsdPerMillionChars: withFiatMargin(12),
    loarPriceUsdPerMillionChars: withLoarMargin(12),
    creditCostPer1kChars: usdToCreditsPer1k(12),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'openai', 'steerable', 'multilingual'],
    bestFor: 'Steerable TTS where you want to script emotion / pacing via prompt',
  },
  {
    id: 'tts-1-hd',
    provider: 'openai',
    displayName: 'OpenAI tts-1-hd',
    shortDescription: 'HD legacy TTS — 11 voices',
    providerModelId: 'tts-1-hd',
    firstAudioLatencyMs: 500,
    maxChars: 4096,
    supportedFormats: ['mp3', 'opus', 'aac', 'flac', 'wav', 'pcm'],
    supportedLanguages: [],
    voices: OPENAI_VOICES.slice(0, 11),
    supportsVoiceClone: false,
    supportsStyleSteer: false,
    supportsStreaming: false,
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    providerCostUsdPerMillionChars: 30,
    fiatPriceUsdPerMillionChars: withFiatMargin(30),
    loarPriceUsdPerMillionChars: withLoarMargin(30),
    creditCostPer1kChars: usdToCreditsPer1k(30),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'openai', 'hd', 'legacy'],
    bestFor: 'Legacy HD quality where gpt-4o-mini-tts is unavailable',
  },
  {
    id: 'tts-1',
    provider: 'openai',
    displayName: 'OpenAI tts-1',
    shortDescription: 'Cheap OpenAI TTS',
    providerModelId: 'tts-1',
    firstAudioLatencyMs: 400,
    maxChars: 4096,
    supportedFormats: ['mp3', 'opus', 'aac', 'flac', 'wav', 'pcm'],
    supportedLanguages: [],
    voices: OPENAI_VOICES.slice(0, 11),
    supportsVoiceClone: false,
    supportsStyleSteer: false,
    supportsStreaming: false,
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    providerCostUsdPerMillionChars: 15,
    fiatPriceUsdPerMillionChars: withFiatMargin(15),
    loarPriceUsdPerMillionChars: withLoarMargin(15),
    creditCostPer1kChars: usdToCreditsPer1k(15),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: false, // gpt-4o-mini-tts supersedes
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'openai', 'budget', 'legacy'],
    bestFor: 'Legacy parity',
  },

  // ── Deepgram Aura-2 ──────────────────────────────────────────────────
  {
    id: 'aura-2-deepgram',
    provider: 'deepgram',
    displayName: 'Deepgram Aura-2',
    shortDescription: '40+ voices, ~90ms first audio, flat $30/Mchar',
    providerModelId: 'aura-2',
    firstAudioLatencyMs: 90,
    maxChars: 2000,
    supportedFormats: ['mp3', 'wav', 'opus', 'mulaw'],
    supportedLanguages: ['en', 'es', 'de', 'fr', 'it', 'ja', 'nl'],
    voices: DEEPGRAM_AURA2_VOICES,
    supportsVoiceClone: false,
    supportsStyleSteer: false,
    supportsStreaming: true,
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    providerCostUsdPerMillionChars: 30,
    fiatPriceUsdPerMillionChars: withFiatMargin(30),
    loarPriceUsdPerMillionChars: withLoarMargin(30),
    creditCostPer1kChars: usdToCreditsPer1k(30),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: false,
    tags: ['tts', 'deepgram', 'aura', 'realtime', 'voice-agent'],
    bestFor: 'Voice-agent + realtime use cases with deep voice library',
  },

  // ── Groq TTS ──────────────────────────────────────────────────────────
  {
    id: 'orpheus-v1-en-groq',
    provider: 'groq',
    displayName: 'Orpheus v1 EN (Groq)',
    shortDescription: 'Canopy Labs Orpheus — successor to PlayAI on Groq',
    providerModelId: 'canopylabs/orpheus-v1-english',
    firstAudioLatencyMs: 200,
    maxChars: 4000,
    supportedFormats: ['mp3', 'wav', 'pcm'],
    supportedLanguages: ['en'],
    voices: [{ id: 'orpheus-default', name: 'Orpheus Default', language: 'en', gender: 'neutral' }],
    supportsVoiceClone: false,
    supportsStyleSteer: false,
    supportsStreaming: true,
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    providerCostUsdPerMillionChars: 22,
    fiatPriceUsdPerMillionChars: withFiatMargin(22),
    loarPriceUsdPerMillionChars: withLoarMargin(22),
    creditCostPer1kChars: usdToCreditsPer1k(22),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: false,
    tags: ['tts', 'groq', 'orpheus', 'english'],
    bestFor: 'Cheap fast English TTS via Groq',
  },
  {
    id: 'playai-tts-groq',
    provider: 'groq',
    displayName: 'PlayAI TTS (Groq)',
    shortDescription: 'PlayAI Dialog v1 — preview tier on Groq',
    providerModelId: 'playai-tts',
    firstAudioLatencyMs: 200,
    maxChars: 4000,
    supportedFormats: ['mp3', 'wav'],
    supportedLanguages: ['en'],
    voices: [{ id: 'playai-default', name: 'PlayAI Default', language: 'en', gender: 'neutral' }],
    supportsVoiceClone: false,
    supportsStyleSteer: false,
    supportsStreaming: true,
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'high',
    providerCostUsdPerMillionChars: 50,
    fiatPriceUsdPerMillionChars: withFiatMargin(50),
    loarPriceUsdPerMillionChars: withLoarMargin(50),
    creditCostPer1kChars: usdToCreditsPer1k(50),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: false, // being phased out per Groq, Orpheus is the new path
    allowedPlans: [],
    serverPoolAvailable: false,
    tags: ['tts', 'groq', 'playai', 'preview', 'legacy'],
    bestFor: 'Legacy PlayAI usage — prefer Orpheus',
  },

  // ── Google Gemini TTS ─────────────────────────────────────────────────
  {
    id: 'gemini-25-flash-tts',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash TTS',
    shortDescription: 'Multi-speaker, ~30 voices, 100+ languages — preview',
    providerModelId: 'gemini-2.5-flash-preview-tts',
    firstAudioLatencyMs: 600,
    maxChars: 32000,
    supportedFormats: ['mp3', 'wav', 'pcm'],
    supportedLanguages: [],
    voices: [], // populated by listVoices() at runtime
    supportsVoiceClone: false,
    supportsStyleSteer: true,
    supportsStreaming: true,
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'medium',
    providerCostUsdPerMillionChars: 10, // approx token math: $10/Mtok audio out
    fiatPriceUsdPerMillionChars: withFiatMargin(10),
    loarPriceUsdPerMillionChars: withLoarMargin(10),
    creditCostPer1kChars: usdToCreditsPer1k(10),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'google', 'gemini', 'multilingual', 'multi-speaker', 'preview'],
    bestFor: 'Multi-speaker scene reads with multilingual coverage',
  },
  {
    id: 'gemini-25-pro-tts',
    provider: 'google',
    displayName: 'Gemini 2.5 Pro TTS',
    shortDescription: 'Premium Gemini TTS — Pro tier',
    providerModelId: 'gemini-2.5-pro-preview-tts',
    firstAudioLatencyMs: 800,
    maxChars: 32000,
    supportedFormats: ['mp3', 'wav', 'pcm'],
    supportedLanguages: [],
    voices: [],
    supportsVoiceClone: false,
    supportsStyleSteer: true,
    supportsStreaming: true,
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    providerCostUsdPerMillionChars: 20,
    fiatPriceUsdPerMillionChars: withFiatMargin(20),
    loarPriceUsdPerMillionChars: withLoarMargin(20),
    creditCostPer1kChars: usdToCreditsPer1k(20),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'google', 'gemini', 'pro', 'multilingual', 'preview'],
    bestFor: 'Pro-tier Gemini TTS for hero VO',
  },
  {
    id: 'gemini-31-flash-tts',
    provider: 'google',
    displayName: 'Gemini 3.1 Flash TTS',
    shortDescription: 'Latest Gemini TTS — preview',
    providerModelId: 'gemini-3.1-flash-tts-preview',
    firstAudioLatencyMs: 500,
    maxChars: 32000,
    supportedFormats: ['mp3', 'wav', 'pcm'],
    supportedLanguages: [],
    voices: [],
    supportsVoiceClone: false,
    supportsStyleSteer: true,
    supportsStreaming: true,
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'high',
    providerCostUsdPerMillionChars: 20,
    fiatPriceUsdPerMillionChars: withFiatMargin(20),
    loarPriceUsdPerMillionChars: withLoarMargin(20),
    creditCostPer1kChars: usdToCreditsPer1k(20),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'google', 'gemini', '3.1', 'preview'],
    bestFor: 'Latest Gemini 3.1 TTS with finest audio tag control',
  },

  // ── Z.AI ──────────────────────────────────────────────────────────────
  {
    id: 'glm-tts',
    provider: 'zai',
    displayName: 'GLM-TTS (Z.AI)',
    shortDescription: 'Zero-shot voice cloning + emotion control',
    providerModelId: 'glm-tts',
    firstAudioLatencyMs: 600,
    maxChars: 8000,
    supportedFormats: ['mp3', 'wav', 'pcm'],
    supportedLanguages: ['zh', 'en'],
    voices: [
      { id: 'female-1', name: 'GLM Female 1', language: 'zh', gender: 'female' },
      { id: 'male-1', name: 'GLM Male 1', language: 'zh', gender: 'male' },
    ],
    supportsVoiceClone: true,
    supportsStyleSteer: true,
    supportsStreaming: false,
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    providerCostUsdPerMillionChars: 8, // approximate
    fiatPriceUsdPerMillionChars: withFiatMargin(8),
    loarPriceUsdPerMillionChars: withLoarMargin(8),
    creditCostPer1kChars: usdToCreditsPer1k(8),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'zai', 'glm', 'voice-clone', 'emotion'],
    bestFor: 'Zero-shot voice cloning + Chinese/English TTS',
  },

  // ── ByteDance Doubao Seed TTS ────────────────────────────────────────
  {
    id: 'seed-tts-2-0',
    provider: 'bytedance',
    displayName: 'Doubao Seed-TTS 2.0',
    shortDescription: 'Doubao Seed-TTS 2.0 — LLM-driven emotion, native cloning',
    providerModelId: 'seed-tts-2.0',
    firstAudioLatencyMs: 500,
    maxChars: 8000,
    supportedFormats: ['mp3', 'wav', 'pcm'],
    supportedLanguages: ['zh', 'en'],
    voices: [],
    supportsVoiceClone: true,
    supportsStyleSteer: true,
    supportsStreaming: true,
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'low',
    providerCostUsdPerMillionChars: 7,
    fiatPriceUsdPerMillionChars: withFiatMargin(7),
    loarPriceUsdPerMillionChars: withLoarMargin(7),
    creditCostPer1kChars: usdToCreditsPer1k(7),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'bytedance', 'doubao', 'voice-clone', 'emotion'],
    bestFor: 'Chinese-first TTS with high-quality voice cloning',
  },
  {
    id: 'seed-tts-1-0',
    provider: 'bytedance',
    displayName: 'Doubao Seed-TTS 1.0',
    shortDescription: '5-second voice clone',
    providerModelId: 'seed-tts-1.0',
    firstAudioLatencyMs: 500,
    maxChars: 8000,
    supportedFormats: ['mp3', 'wav'],
    supportedLanguages: ['zh', 'en'],
    voices: [],
    supportsVoiceClone: true,
    supportsStyleSteer: false,
    supportsStreaming: true,
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    providerCostUsdPerMillionChars: 5,
    fiatPriceUsdPerMillionChars: withFiatMargin(5),
    loarPriceUsdPerMillionChars: withLoarMargin(5),
    creditCostPer1kChars: usdToCreditsPer1k(5),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: false, // 2.0 supersedes
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'bytedance', 'doubao', 'legacy'],
    bestFor: 'Legacy Doubao Seed-TTS 1.0 parity',
  },

  // ── FAL passthrough TTS (legacy) ─────────────────────────────────────
  {
    id: 'minimax-speech-28-hd-fal',
    provider: 'fal',
    displayName: 'MiniMax Speech 2.8 HD (FAL)',
    shortDescription: 'MiniMax HD speech via FAL',
    providerModelId: 'minimax/speech-2.8-hd',
    firstAudioLatencyMs: 800,
    maxChars: 5000,
    supportedFormats: ['mp3', 'wav'],
    supportedLanguages: [],
    voices: [],
    supportsVoiceClone: true,
    supportsStyleSteer: false,
    supportsStreaming: false,
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    providerCostUsdPerMillionChars: 25,
    fiatPriceUsdPerMillionChars: withFiatMargin(25),
    loarPriceUsdPerMillionChars: withLoarMargin(25),
    creditCostPer1kChars: usdToCreditsPer1k(25),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['tts', 'fal', 'minimax', 'hd', 'multilingual'],
    bestFor: 'MiniMax HD speech without managing a MiniMax key',
  },
];

// ── Lookup helpers ────────────────────────────────────────────────────

export function getTtsModelById(id: string): TtsModelConfig | undefined {
  return TTS_MODELS.find((m) => m.id === id);
}

export function getEnabledTtsModels(): TtsModelConfig[] {
  return TTS_MODELS.filter((m) => m.isEnabled);
}

export function getVisibleTtsModels(): TtsModelConfig[] {
  return TTS_MODELS.filter((m) => m.isEnabled && m.isVisibleToUsers);
}

export function getTtsModelIds(): string[] {
  return TTS_MODELS.map((m) => m.id);
}

/** Quote credits to synthesize `chars` characters with a chosen model. */
export function quoteTtsCredits(modelId: string, chars: number): number {
  const m = getTtsModelById(modelId);
  if (!m) throw new Error(`Unknown TTS model: ${modelId}`);
  if (!m.isEnabled) throw new Error(`TTS model is disabled: ${modelId}`);
  const kchars = Math.max(1, Math.ceil(chars / 1000));
  return kchars * m.creditCostPer1kChars;
}
