/**
 * Layer 6 — chain
 * Checks:
 *   - RPC reachable + current block (Sepolia or Base Sepolia)
 *   - UniverseManager contract deployed at expected address
 *   - (optional) createNode on a target Universe contract
 *
 * On-chain write requires both SMOKE_PRIVATE_KEY and SMOKE_UNIVERSE_ADDRESS.
 * Without them the write checks are skipped — the harness still confirms RPC
 * and contract reachability.
 *
 * Identifies: RPC endpoint down, wrong contract address, insufficient gas,
 *             contract logic regressions.
 */
import { createPublicClient, createWalletClient, http, parseAbi, getAddress } from 'viem';
import { sepolia, baseSepolia } from 'viem/chains';
import { privateKeyToAccount } from 'viem/accounts';
import type { SmokeConfig } from '../config.ts';
import { DEMO_CONTENT_PACK } from '../fixtures.ts';
import { check, skipped, type CheckResult } from '../reporter.ts';
import { UniverseManager as UniverseManagerAddresses } from '../../../packages/abis/src/addresses.ts';

// Chain lookup by ID
const CHAINS: Record<number, typeof sepolia> = {
  [sepolia.id]: sepolia,
  [baseSepolia.id]: baseSepolia,
};

// Read UniverseManager addresses from the canonical deployment manifests
// (packages/abis/src/addresses.ts, auto-generated by `pnpm sync:addresses`).
const UNIVERSE_MANAGER_ADDRESSES: Record<number, `0x${string}`> = {
  [sepolia.id]: getAddress((UniverseManagerAddresses as any)[String(sepolia.id)]),
  [baseSepolia.id]: getAddress((UniverseManagerAddresses as any)[String(baseSepolia.id)]),
};

const UNIVERSE_MANAGER_ABI = parseAbi([
  'function totalSupply() view returns (uint256)',
  'function getUniverseData(uint256 id) view returns (address universe, address token, address governor)',
  'function mintFee() view returns (uint256)',
]);

const UNIVERSE_ABI = parseAbi([
  'function universeName() view returns (string)',
  'function latestNodeId() view returns (uint256)',
  'function createNode(bytes32 _contentHash, bytes32 _plotHash, uint256 _previous, string calldata _link, string calldata _plot) returns (uint256)',
]);

export interface ChainResult {
  blockNumber: bigint | undefined;
  nodeId: bigint | undefined;
  checks: CheckResult[];
}

export async function runChainLayer(cfg: SmokeConfig): Promise<ChainResult> {
  const results: CheckResult[] = [];
  let blockNumber: bigint | undefined;
  let nodeId: bigint | undefined;

  const chain = CHAINS[cfg.chainId] ?? sepolia;
  const chainName = chain.name;
  const UNIVERSE_MANAGER_ADDRESS =
    UNIVERSE_MANAGER_ADDRESSES[cfg.chainId] ?? UNIVERSE_MANAGER_ADDRESSES[sepolia.id];

  const publicClient = createPublicClient({
    chain,
    transport: http(cfg.rpcUrl),
  });

  // 1. RPC reachable — get latest block
  results.push(
    await check(`${chainName} RPC reachable → block number`, async () => {
      blockNumber = await publicClient.getBlockNumber();
      if (!blockNumber || blockNumber === 0n) throw new Error('block number is 0 or missing');
      return `block #${blockNumber.toLocaleString()}`;
    })
  );

  // 2. UniverseManager contract code present
  results.push(
    await check('UniverseManager contract deployed', async () => {
      const code = await publicClient.getCode({ address: UNIVERSE_MANAGER_ADDRESS });
      if (!code || code === '0x') {
        throw new Error(
          `no code at ${UNIVERSE_MANAGER_ADDRESS} — contract not deployed on this RPC`
        );
      }
      return `${UNIVERSE_MANAGER_ADDRESS.slice(0, 10)}… code=${code.slice(0, 10)}…`;
    })
  );

  // 3. Read universe count from UniverseManager (via ERC721 totalSupply)
  results.push(
    await check('UniverseManager.totalSupply() readable', async () => {
      const count = await publicClient.readContract({
        address: UNIVERSE_MANAGER_ADDRESS,
        abi: UNIVERSE_MANAGER_ABI,
        functionName: 'totalSupply',
      });
      return `${count} universe(s) minted on-chain`;
    })
  );

  // 3b. Read mint fee (proves contract is properly initialized)
  results.push(
    await check('UniverseManager.mintFee() readable', async () => {
      const fee = await publicClient.readContract({
        address: UNIVERSE_MANAGER_ADDRESS,
        abi: UNIVERSE_MANAGER_ABI,
        functionName: 'mintFee',
      });
      return `${Number(fee) / 1e18} ETH mint fee`;
    })
  );

  // 4. Read target Universe if SMOKE_UNIVERSE_ADDRESS is set
  if (cfg.universeAddress) {
    results.push(
      await check(`Universe(${cfg.universeAddress.slice(0, 10)}…).universeName()`, async () => {
        const name = await publicClient.readContract({
          address: cfg.universeAddress!,
          abi: UNIVERSE_ABI,
          functionName: 'universeName',
        });
        return String(name).slice(0, 60);
      })
    );

    results.push(
      await check(`Universe.latestNodeId() readable`, async () => {
        const id = await publicClient.readContract({
          address: cfg.universeAddress!,
          abi: UNIVERSE_ABI,
          functionName: 'latestNodeId',
        });
        return `latestNodeId=${id}`;
      })
    );
  } else {
    results.push(
      skipped('Universe.universeName() / latestNodeId()', 'set SMOKE_UNIVERSE_ADDRESS to enable')
    );
  }

  // 5. Write test node (requires SMOKE_PRIVATE_KEY + SMOKE_UNIVERSE_ADDRESS)
  if (cfg.privateKey && cfg.universeAddress) {
    results.push(
      await check('Universe.createNode() — write smoke node', async () => {
        const account = privateKeyToAccount(cfg.privateKey!);
        const walletClient = createWalletClient({
          account,
          chain,
          transport: http(cfg.rpcUrl),
        });

        // Read current nodeId so we can verify it increments
        const beforeId = await publicClient.readContract({
          address: cfg.universeAddress!,
          abi: UNIVERSE_ABI,
          functionName: 'latestNodeId',
        });

        const txHash = await walletClient.writeContract({
          address: cfg.universeAddress!,
          abi: UNIVERSE_ABI,
          functionName: 'createNode',
          args: [
            DEMO_CONTENT_PACK.contentHashBytes32,
            DEMO_CONTENT_PACK.plotHashBytes32,
            0n, // previous = 0 (root node)
            DEMO_CONTENT_PACK.contentUrl,
            DEMO_CONTENT_PACK.plot.slice(0, 200),
          ],
        });

        const receipt = await publicClient.waitForTransactionReceipt({ hash: txHash });
        if (receipt.status !== 'success') {
          throw new Error(`tx reverted: ${txHash}`);
        }

        const afterId = await publicClient.readContract({
          address: cfg.universeAddress!,
          abi: UNIVERSE_ABI,
          functionName: 'latestNodeId',
        });

        if (afterId <= beforeId) {
          throw new Error(`nodeId did not increment: before=${beforeId} after=${afterId}`);
        }

        nodeId = afterId;
        return `nodeId=${afterId} tx=${txHash.slice(0, 10)}…`;
      })
    );
  } else {
    results.push(
      skipped(
        'Universe.createNode() — write smoke node',
        'set SMOKE_PRIVATE_KEY + SMOKE_UNIVERSE_ADDRESS to enable on-chain write tests'
      )
    );
  }

  return { blockNumber, nodeId, checks: results };
}
