services:
  app-server:
    build:
      context: .
      dockerfile: apps/server/Dockerfile
      target: production
    container_name: loar-server
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - loar-network

  app-web:
    build:
      context: .
      dockerfile: apps/web/Dockerfile
      target: production
    container_name: loar-web
    ports:
      - "3001:3001"
    restart: unless-stopped
    networks:
      - loar-network

  indexer:
    build:
      context: .
      dockerfile: apps/indexer/Dockerfile
    container_name: loar-indexer
    env_file:
      - ./.env
    environment:
      - NODE_ENV=production
    ports:
      - "42069:42069"
    restart: unless-stopped
    networks:
      - loar-network

networks:
  loar-network:
    name: loar-network
    driver: bridge
