packages:
  - 'apps/web'
  - 'apps/server'
  - 'apps/indexer'
  - 'apps/event-listener'
  - 'apps/contracts'
  - 'apps/programs'
  - 'apps/solana-indexer'
  - 'apps/mcp'
  - 'apps/mcp-gateway'
  - 'apps/mobile'
  - 'packages/*'
