/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ViralityRouteImport } from './routes/virality'
import { Route as RoyaltiesRouteImport } from './routes/royalties'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TestnetRouteImport } from './routes/testnet'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SubscriptionsRouteImport } from './routes/subscriptions'
import { Route as StudioControlledRouteImport } from './routes/studio-controlled'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as StatusRouteImport } from './routes/status'
import { Route as SolanaRouteImport } from './routes/solana'
import { Route as SeriesRouteImport } from './routes/series'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as ResidencyRouteImport } from './routes/residency'
import { Route as RelightRouteImport } from './routes/relight'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NotebookRouteImport } from './routes/notebook'
import { Route as MyWorksRouteImport } from './routes/my-works'
import { Route as MarketingRouteImport } from './routes/marketing'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FaucetRouteImport } from './routes/faucet'
import { Route as EditorRouteImport } from './routes/editor'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as CounterNoticeRouteImport } from './routes/counter-notice'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as CinematicUniverseCreateRouteImport } from './routes/cinematicUniverseCreate'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CanvasRouteImport } from './routes/canvas'
import { Route as BridgeRouteImport } from './routes/bridge'
import { Route as AdReferenceRouteImport } from './routes/ad-reference'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as TokensIndexRouteImport } from './routes/tokens/index'
import { Route as SellIndexRouteImport } from './routes/sell/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as BountiesIndexRouteImport } from './routes/bounties/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AdplacementsIndexRouteImport } from './routes/adplacements/index'
import { Route as WikiKindRouteImport } from './routes/wiki/$kind'
import { Route as UniverseIdRouteImport } from './routes/universe/$id'
import { Route as TreasuryUniverseIdRouteImport } from './routes/treasury/$universeId'
import { Route as TokensSwapRouteImport } from './routes/tokens/swap'
import { Route as TokensPortfolioRouteImport } from './routes/tokens/portfolio'
import { Route as TokensLaunchRouteImport } from './routes/tokens/launch'
import { Route as TokensAddressRouteImport } from './routes/tokens/$address'
import { Route as ShopUniverseIdRouteImport } from './routes/shop/$universeId'
import { Route as SettingsWalletsRouteImport } from './routes/settings.wallets'
import { Route as SettingsUsageRouteImport } from './routes/settings.usage'
import { Route as SettingsApiKeysRouteImport } from './routes/settings.api-keys'
import { Route as SellNewRouteImport } from './routes/sell/new'
import { Route as SellEarningsRouteImport } from './routes/sell/earnings'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ProductIdRouteImport } from './routes/product/$id'
import { Route as PlayUniverseIdRouteImport } from './routes/play/$universeId'
import { Route as OrderIdRouteImport } from './routes/order/$id'
import { Route as OauthSiweRouteImport } from './routes/oauth/siwe'
import { Route as NotebookIdRouteImport } from './routes/notebook.$id'
import { Route as MarketplaceLikenessRouteImport } from './routes/marketplace.likeness'
import { Route as LineageAssetIdRouteImport } from './routes/lineage.$assetId'
import { Route as LabZaiRouteImport } from './routes/lab.zai'
import { Route as LabVoiceStudioRouteImport } from './routes/lab.voice-studio'
import { Route as LabGptImageRouteImport } from './routes/lab.gpt-image'
import { Route as GovernanceUniverseIdRouteImport } from './routes/governance/$universeId'
import { Route as ExtractJobIdRouteImport } from './routes/extract.$jobId'
import { Route as EpisodeIdRouteImport } from './routes/episode.$id'
import { Route as EditOutpaintRouteImport } from './routes/edit.outpaint'
import { Route as EditInpaintRouteImport } from './routes/edit.inpaint'
import { Route as DashboardRevenueRouteImport } from './routes/dashboard.revenue'
import { Route as DashboardPersonasRouteImport } from './routes/dashboard.personas'
import { Route as CreatePersonaRouteImport } from './routes/create.persona'
import { Route as CreateLikenessRouteImport } from './routes/create.likeness'
import { Route as CreateKindRouteImport } from './routes/create/$kind'
import { Route as CharactersUniverseIdRouteImport } from './routes/characters.$universeId'
import { Route as CanvasCanvasIdRouteImport } from './routes/canvas.$canvasId'
import { Route as CanonUniverseIdRouteImport } from './routes/canon/$universeId'
import { Route as BrandDashboardRouteImport } from './routes/brand/dashboard'
import { Route as BountiesMineRouteImport } from './routes/bounties/mine'
import { Route as BountiesBountyIdRouteImport } from './routes/bounties/$bountyId'
import { Route as AnatomyUniverseRouteImport } from './routes/anatomy.$universe'
import { Route as AnalyticsUniverseIdRouteImport } from './routes/analytics.$universeId'
import { Route as AgentsRegisterRouteImport } from './routes/agents/register'
import { Route as AgentsDashboardRouteImport } from './routes/agents/dashboard'
import { Route as AgentsUidRouteImport } from './routes/agents/$uid'
import { Route as AdplacementsNewRouteImport } from './routes/adplacements/new'
import { Route as AdplacementsSlotIdRouteImport } from './routes/adplacements/$slotId'
import { Route as AdminUniversesRouteImport } from './routes/admin/universes'
import { Route as AdminResidencyRouteImport } from './routes/admin/residency'
import { Route as AdminOpsRouteImport } from './routes/admin/ops'
import { Route as AdminMainnetRouteImport } from './routes/admin/mainnet'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as AdminMcpUsageRouteImport } from './routes/admin/mcp-usage'
import { Route as AdminCostRouteImport } from './routes/admin/cost'
import { Route as AdminByokCodesRouteImport } from './routes/admin/byok-codes'
import { Route as AdplacementsSeedsIndexRouteImport } from './routes/adplacements/seeds/index'
import { Route as WikiEntityIdRouteImport } from './routes/wiki/entity/$id'
import { Route as WikiCharacterIdRouteImport } from './routes/wiki/character/$id'
import { Route as UniverseIdWatchRouteImport } from './routes/universe/$id/watch'
import { Route as UniverseIdStyleRouteImport } from './routes/universe/$id/style'
import { Route as UniverseIdProfileRouteImport } from './routes/universe/$id/profile'
import { Route as UniverseIdLineageRouteImport } from './routes/universe/$id/lineage'
import { Route as UniverseIdGenConfigRouteImport } from './routes/universe/$id/gen-config'
import { Route as UniverseIdGalleryRouteImport } from './routes/universe/$id/gallery'
import { Route as UniverseIdDeployTokenRouteImport } from './routes/universe/$id.deploy-token'
import { Route as UniverseAddressPollsRouteImport } from './routes/universe.$address.polls'
import { Route as UniverseAddressPhysicsRouteImport } from './routes/universe.$address.physics'
import { Route as TokensCreatorAddressRouteImport } from './routes/tokens/creator.$address'
import { Route as StudioEditAssetIdRouteImport } from './routes/studio.edit.$assetId'
import { Route as MarketplacePersonaPersonaIdRouteImport } from './routes/marketplace.persona.$personaId'
import { Route as MarketplaceLikenessListingIdRouteImport } from './routes/marketplace.likeness.$listingId'
import { Route as LabZaiDiagnosticRouteImport } from './routes/lab.zai.diagnostic'
import { Route as EventUniverseEventRouteImport } from './routes/event.$universe.$event'
import { Route as AdplacementsSeedsNewRouteImport } from './routes/adplacements/seeds/new'
import { Route as AdplacementsSeedsSeedIdRouteImport } from './routes/adplacements/seeds/$seedId'
import { Route as LabZaiVideoJobIdRouteImport } from './routes/lab.zai.video.$jobId'
import { Route as DashboardPersonasPersonaIdEditRouteImport } from './routes/dashboard.personas.$personaId.edit'

const ViralityRoute = ViralityRouteImport.update({
  id: '/virality',
  path: '/virality',
  getParentRoute: () => rootRouteImport,
} as any)
const RoyaltiesRoute = RoyaltiesRouteImport.update({
  id: '/royalties',
  path: '/royalties',
  getParentRoute: () => rootRouteImport,
} as any)
const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TestnetRoute = TestnetRouteImport.update({
  id: '/testnet',
  path: '/testnet',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SubscriptionsRoute = SubscriptionsRouteImport.update({
  id: '/subscriptions',
  path: '/subscriptions',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioControlledRoute = StudioControlledRouteImport.update({
  id: '/studio-controlled',
  path: '/studio-controlled',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const StatusRoute = StatusRouteImport.update({
  id: '/status',
  path: '/status',
  getParentRoute: () => rootRouteImport,
} as any)
const SolanaRoute = SolanaRouteImport.update({
  id: '/solana',
  path: '/solana',
  getParentRoute: () => rootRouteImport,
} as any)
const SeriesRoute = SeriesRouteImport.update({
  id: '/series',
  path: '/series',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const ResidencyRoute = ResidencyRouteImport.update({
  id: '/residency',
  path: '/residency',
  getParentRoute: () => rootRouteImport,
} as any)
const RelightRoute = RelightRouteImport.update({
  id: '/relight',
  path: '/relight',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookRoute = NotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorksRoute = MyWorksRouteImport.update({
  id: '/my-works',
  path: '/my-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketingRoute = MarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FaucetRoute = FaucetRouteImport.update({
  id: '/faucet',
  path: '/faucet',
  getParentRoute: () => rootRouteImport,
} as any)
const EditorRoute = EditorRouteImport.update({
  id: '/editor',
  path: '/editor',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const CounterNoticeRoute = CounterNoticeRouteImport.update({
  id: '/counter-notice',
  path: '/counter-notice',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const CinematicUniverseCreateRoute = CinematicUniverseCreateRouteImport.update({
  id: '/cinematicUniverseCreate',
  path: '/cinematicUniverseCreate',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasRoute = CanvasRouteImport.update({
  id: '/canvas',
  path: '/canvas',
  getParentRoute: () => rootRouteImport,
} as any)
const BridgeRoute = BridgeRouteImport.update({
  id: '/bridge',
  path: '/bridge',
  getParentRoute: () => rootRouteImport,
} as any)
const AdReferenceRoute = AdReferenceRouteImport.update({
  id: '/ad-reference',
  path: '/ad-reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensIndexRoute = TokensIndexRouteImport.update({
  id: '/tokens/',
  path: '/tokens/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesIndexRoute = BountiesIndexRouteImport.update({
  id: '/bounties/',
  path: '/bounties/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdplacementsIndexRoute = AdplacementsIndexRouteImport.update({
  id: '/adplacements/',
  path: '/adplacements/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiKindRoute = WikiKindRouteImport.update({
  id: '/wiki/$kind',
  path: '/wiki/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseIdRoute = UniverseIdRouteImport.update({
  id: '/universe/$id',
  path: '/universe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryUniverseIdRoute = TreasuryUniverseIdRouteImport.update({
  id: '/treasury/$universeId',
  path: '/treasury/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensSwapRoute = TokensSwapRouteImport.update({
  id: '/tokens/swap',
  path: '/tokens/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensPortfolioRoute = TokensPortfolioRouteImport.update({
  id: '/tokens/portfolio',
  path: '/tokens/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensLaunchRoute = TokensLaunchRouteImport.update({
  id: '/tokens/launch',
  path: '/tokens/launch',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensAddressRoute = TokensAddressRouteImport.update({
  id: '/tokens/$address',
  path: '/tokens/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopUniverseIdRoute = ShopUniverseIdRouteImport.update({
  id: '/shop/$universeId',
  path: '/shop/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsWalletsRoute = SettingsWalletsRouteImport.update({
  id: '/settings/wallets',
  path: '/settings/wallets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsUsageRoute = SettingsUsageRouteImport.update({
  id: '/settings/usage',
  path: '/settings/usage',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsApiKeysRoute = SettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => rootRouteImport,
} as any)
const SellNewRoute = SellNewRouteImport.update({
  id: '/sell/new',
  path: '/sell/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SellEarningsRoute = SellEarningsRouteImport.update({
  id: '/sell/earnings',
  path: '/sell/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayUniverseIdRoute = PlayUniverseIdRouteImport.update({
  id: '/play/$universeId',
  path: '/play/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const OauthSiweRoute = OauthSiweRouteImport.update({
  id: '/oauth/siwe',
  path: '/oauth/siwe',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebookIdRoute = NotebookIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => NotebookRoute,
} as any)
const MarketplaceLikenessRoute = MarketplaceLikenessRouteImport.update({
  id: '/marketplace/likeness',
  path: '/marketplace/likeness',
  getParentRoute: () => rootRouteImport,
} as any)
const LineageAssetIdRoute = LineageAssetIdRouteImport.update({
  id: '/lineage/$assetId',
  path: '/lineage/$assetId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabZaiRoute = LabZaiRouteImport.update({
  id: '/lab/zai',
  path: '/lab/zai',
  getParentRoute: () => rootRouteImport,
} as any)
const LabVoiceStudioRoute = LabVoiceStudioRouteImport.update({
  id: '/lab/voice-studio',
  path: '/lab/voice-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const LabGptImageRoute = LabGptImageRouteImport.update({
  id: '/lab/gpt-image',
  path: '/lab/gpt-image',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceUniverseIdRoute = GovernanceUniverseIdRouteImport.update({
  id: '/governance/$universeId',
  path: '/governance/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const ExtractJobIdRoute = ExtractJobIdRouteImport.update({
  id: '/extract/$jobId',
  path: '/extract/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const EpisodeIdRoute = EpisodeIdRouteImport.update({
  id: '/episode/$id',
  path: '/episode/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EditOutpaintRoute = EditOutpaintRouteImport.update({
  id: '/edit/outpaint',
  path: '/edit/outpaint',
  getParentRoute: () => rootRouteImport,
} as any)
const EditInpaintRoute = EditInpaintRouteImport.update({
  id: '/edit/inpaint',
  path: '/edit/inpaint',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRevenueRoute = DashboardRevenueRouteImport.update({
  id: '/revenue',
  path: '/revenue',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardPersonasRoute = DashboardPersonasRouteImport.update({
  id: '/personas',
  path: '/personas',
  getParentRoute: () => DashboardRoute,
} as any)
const CreatePersonaRoute = CreatePersonaRouteImport.update({
  id: '/create/persona',
  path: '/create/persona',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateLikenessRoute = CreateLikenessRouteImport.update({
  id: '/create/likeness',
  path: '/create/likeness',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateKindRoute = CreateKindRouteImport.update({
  id: '/create/$kind',
  path: '/create/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const CharactersUniverseIdRoute = CharactersUniverseIdRouteImport.update({
  id: '/characters/$universeId',
  path: '/characters/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CanvasCanvasIdRoute = CanvasCanvasIdRouteImport.update({
  id: '/$canvasId',
  path: '/$canvasId',
  getParentRoute: () => CanvasRoute,
} as any)
const CanonUniverseIdRoute = CanonUniverseIdRouteImport.update({
  id: '/canon/$universeId',
  path: '/canon/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandDashboardRoute = BrandDashboardRouteImport.update({
  id: '/brand/dashboard',
  path: '/brand/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesMineRoute = BountiesMineRouteImport.update({
  id: '/bounties/mine',
  path: '/bounties/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesBountyIdRoute = BountiesBountyIdRouteImport.update({
  id: '/bounties/$bountyId',
  path: '/bounties/$bountyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AnatomyUniverseRoute = AnatomyUniverseRouteImport.update({
  id: '/anatomy/$universe',
  path: '/anatomy/$universe',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsUniverseIdRoute = AnalyticsUniverseIdRouteImport.update({
  id: '/analytics/$universeId',
  path: '/analytics/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRegisterRoute = AgentsRegisterRouteImport.update({
  id: '/agents/register',
  path: '/agents/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDashboardRoute = AgentsDashboardRouteImport.update({
  id: '/agents/dashboard',
  path: '/agents/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsUidRoute = AgentsUidRouteImport.update({
  id: '/agents/$uid',
  path: '/agents/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const AdplacementsNewRoute = AdplacementsNewRouteImport.update({
  id: '/adplacements/new',
  path: '/adplacements/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdplacementsSlotIdRoute = AdplacementsSlotIdRouteImport.update({
  id: '/adplacements/$slotId',
  path: '/adplacements/$slotId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUniversesRoute = AdminUniversesRouteImport.update({
  id: '/admin/universes',
  path: '/admin/universes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminResidencyRoute = AdminResidencyRouteImport.update({
  id: '/admin/residency',
  path: '/admin/residency',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOpsRoute = AdminOpsRouteImport.update({
  id: '/admin/ops',
  path: '/admin/ops',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMainnetRoute = AdminMainnetRouteImport.update({
  id: '/admin/mainnet',
  path: '/admin/mainnet',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminMcpUsageRoute = AdminMcpUsageRouteImport.update({
  id: '/admin/mcp-usage',
  path: '/admin/mcp-usage',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCostRoute = AdminCostRouteImport.update({
  id: '/admin/cost',
  path: '/admin/cost',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminByokCodesRoute = AdminByokCodesRouteImport.update({
  id: '/admin/byok-codes',
  path: '/admin/byok-codes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdplacementsSeedsIndexRoute = AdplacementsSeedsIndexRouteImport.update({
  id: '/adplacements/seeds/',
  path: '/adplacements/seeds/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiEntityIdRoute = WikiEntityIdRouteImport.update({
  id: '/wiki/entity/$id',
  path: '/wiki/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiCharacterIdRoute = WikiCharacterIdRouteImport.update({
  id: '/wiki/character/$id',
  path: '/wiki/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseIdWatchRoute = UniverseIdWatchRouteImport.update({
  id: '/watch',
  path: '/watch',
  getParentRoute: () => UniverseIdRoute,
} as any)
const UniverseIdStyleRoute = UniverseIdStyleRouteImport.update({
  id: '/style',
  path: '/style',
  getParentRoute: () => UniverseIdRoute,
} as any)
const UniverseIdProfileRoute = UniverseIdProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => UniverseIdRoute,
} as any)
const UniverseIdLineageRoute = UniverseIdLineageRouteImport.update({
  id: '/lineage',
  path: '/lineage',
  getParentRoute: () => UniverseIdRoute,
} as any)
const UniverseIdGenConfigRoute = UniverseIdGenConfigRouteImport.update({
  id: '/gen-config',
  path: '/gen-config',
  getParentRoute: () => UniverseIdRoute,
} as any)
const UniverseIdGalleryRoute = UniverseIdGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => UniverseIdRoute,
} as any)
const UniverseIdDeployTokenRoute = UniverseIdDeployTokenRouteImport.update({
  id: '/deploy-token',
  path: '/deploy-token',
  getParentRoute: () => UniverseIdRoute,
} as any)
const UniverseAddressPollsRoute = UniverseAddressPollsRouteImport.update({
  id: '/universe/$address/polls',
  path: '/universe/$address/polls',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseAddressPhysicsRoute = UniverseAddressPhysicsRouteImport.update({
  id: '/universe/$address/physics',
  path: '/universe/$address/physics',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensCreatorAddressRoute = TokensCreatorAddressRouteImport.update({
  id: '/tokens/creator/$address',
  path: '/tokens/creator/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioEditAssetIdRoute = StudioEditAssetIdRouteImport.update({
  id: '/edit/$assetId',
  path: '/edit/$assetId',
  getParentRoute: () => StudioRoute,
} as any)
const MarketplacePersonaPersonaIdRoute =
  MarketplacePersonaPersonaIdRouteImport.update({
    id: '/marketplace/persona/$personaId',
    path: '/marketplace/persona/$personaId',
    getParentRoute: () => rootRouteImport,
  } as any)
const MarketplaceLikenessListingIdRoute =
  MarketplaceLikenessListingIdRouteImport.update({
    id: '/$listingId',
    path: '/$listingId',
    getParentRoute: () => MarketplaceLikenessRoute,
  } as any)
const LabZaiDiagnosticRoute = LabZaiDiagnosticRouteImport.update({
  id: '/diagnostic',
  path: '/diagnostic',
  getParentRoute: () => LabZaiRoute,
} as any)
const EventUniverseEventRoute = EventUniverseEventRouteImport.update({
  id: '/event/$universe/$event',
  path: '/event/$universe/$event',
  getParentRoute: () => rootRouteImport,
} as any)
const AdplacementsSeedsNewRoute = AdplacementsSeedsNewRouteImport.update({
  id: '/adplacements/seeds/new',
  path: '/adplacements/seeds/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdplacementsSeedsSeedIdRoute = AdplacementsSeedsSeedIdRouteImport.update({
  id: '/adplacements/seeds/$seedId',
  path: '/adplacements/seeds/$seedId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabZaiVideoJobIdRoute = LabZaiVideoJobIdRouteImport.update({
  id: '/video/$jobId',
  path: '/video/$jobId',
  getParentRoute: () => LabZaiRoute,
} as any)
const DashboardPersonasPersonaIdEditRoute =
  DashboardPersonasPersonaIdEditRouteImport.update({
    id: '/$personaId/edit',
    path: '/$personaId/edit',
    getParentRoute: () => DashboardPersonasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ad-reference': typeof AdReferenceRoute
  '/bridge': typeof BridgeRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cinematicUniverseCreate': typeof CinematicUniverseCreateRoute
  '/coming-soon': typeof ComingSoonRoute
  '/counter-notice': typeof CounterNoticeRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/docs': typeof DocsRoute
  '/editor': typeof EditorRoute
  '/faucet': typeof FaucetRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/marketing': typeof MarketingRoute
  '/my-works': typeof MyWorksRoute
  '/notebook': typeof NotebookRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/relight': typeof RelightRoute
  '/residency': typeof ResidencyRoute
  '/sandbox': typeof SandboxRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/solana': typeof SolanaRoute
  '/status': typeof StatusRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio-controlled': typeof StudioControlledRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/terms': typeof TermsRoute
  '/testnet': typeof TestnetRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/virality': typeof ViralityRoute
  '/royalties': typeof RoyaltiesRoute
  '/admin/byok-codes': typeof AdminByokCodesRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/mcp-usage': typeof AdminMcpUsageRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/mainnet': typeof AdminMainnetRoute
  '/admin/residency': typeof AdminResidencyRoute
  '/admin/universes': typeof AdminUniversesRoute
  '/adplacements/$slotId': typeof AdplacementsSlotIdRoute
  '/adplacements/new': typeof AdplacementsNewRoute
  '/agents/$uid': typeof AgentsUidRoute
  '/agents/dashboard': typeof AgentsDashboardRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/analytics/$universeId': typeof AnalyticsUniverseIdRoute
  '/anatomy/$universe': typeof AnatomyUniverseRoute
  '/bounties/$bountyId': typeof BountiesBountyIdRoute
  '/bounties/mine': typeof BountiesMineRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/canon/$universeId': typeof CanonUniverseIdRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/characters/$universeId': typeof CharactersUniverseIdRoute
  '/create/$kind': typeof CreateKindRoute
  '/create/likeness': typeof CreateLikenessRoute
  '/create/persona': typeof CreatePersonaRoute
  '/dashboard/personas': typeof DashboardPersonasRouteWithChildren
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/edit/inpaint': typeof EditInpaintRoute
  '/edit/outpaint': typeof EditOutpaintRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/extract/$jobId': typeof ExtractJobIdRoute
  '/governance/$universeId': typeof GovernanceUniverseIdRoute
  '/lab/gpt-image': typeof LabGptImageRoute
  '/lab/voice-studio': typeof LabVoiceStudioRoute
  '/lab/zai': typeof LabZaiRouteWithChildren
  '/lineage/$assetId': typeof LineageAssetIdRoute
  '/marketplace/likeness': typeof MarketplaceLikenessRouteWithChildren
  '/notebook/$id': typeof NotebookIdRoute
  '/oauth/siwe': typeof OauthSiweRoute
  '/order/$id': typeof OrderIdRoute
  '/play/$universeId': typeof PlayUniverseIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/sell/earnings': typeof SellEarningsRoute
  '/sell/new': typeof SellNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/wallets': typeof SettingsWalletsRoute
  '/shop/$universeId': typeof ShopUniverseIdRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/tokens/launch': typeof TokensLaunchRoute
  '/tokens/portfolio': typeof TokensPortfolioRoute
  '/tokens/swap': typeof TokensSwapRoute
  '/treasury/$universeId': typeof TreasuryUniverseIdRoute
  '/universe/$id': typeof UniverseIdRouteWithChildren
  '/wiki/$kind': typeof WikiKindRoute
  '/adplacements/': typeof AdplacementsIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/bounties/': typeof BountiesIndexRoute
  '/create/': typeof CreateIndexRoute
  '/sell/': typeof SellIndexRoute
  '/tokens/': typeof TokensIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/adplacements/seeds/$seedId': typeof AdplacementsSeedsSeedIdRoute
  '/adplacements/seeds/new': typeof AdplacementsSeedsNewRoute
  '/event/$universe/$event': typeof EventUniverseEventRoute
  '/lab/zai/diagnostic': typeof LabZaiDiagnosticRoute
  '/marketplace/likeness/$listingId': typeof MarketplaceLikenessListingIdRoute
  '/marketplace/persona/$personaId': typeof MarketplacePersonaPersonaIdRoute
  '/studio/edit/$assetId': typeof StudioEditAssetIdRoute
  '/tokens/creator/$address': typeof TokensCreatorAddressRoute
  '/universe/$address/physics': typeof UniverseAddressPhysicsRoute
  '/universe/$address/polls': typeof UniverseAddressPollsRoute
  '/universe/$id/deploy-token': typeof UniverseIdDeployTokenRoute
  '/universe/$id/gallery': typeof UniverseIdGalleryRoute
  '/universe/$id/gen-config': typeof UniverseIdGenConfigRoute
  '/universe/$id/lineage': typeof UniverseIdLineageRoute
  '/universe/$id/profile': typeof UniverseIdProfileRoute
  '/universe/$id/style': typeof UniverseIdStyleRoute
  '/universe/$id/watch': typeof UniverseIdWatchRoute
  '/wiki/character/$id': typeof WikiCharacterIdRoute
  '/wiki/entity/$id': typeof WikiEntityIdRoute
  '/adplacements/seeds/': typeof AdplacementsSeedsIndexRoute
  '/dashboard/personas/$personaId/edit': typeof DashboardPersonasPersonaIdEditRoute
  '/lab/zai/video/$jobId': typeof LabZaiVideoJobIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ad-reference': typeof AdReferenceRoute
  '/bridge': typeof BridgeRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cinematicUniverseCreate': typeof CinematicUniverseCreateRoute
  '/coming-soon': typeof ComingSoonRoute
  '/counter-notice': typeof CounterNoticeRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/docs': typeof DocsRoute
  '/editor': typeof EditorRoute
  '/faucet': typeof FaucetRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/marketing': typeof MarketingRoute
  '/my-works': typeof MyWorksRoute
  '/notebook': typeof NotebookRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/relight': typeof RelightRoute
  '/residency': typeof ResidencyRoute
  '/sandbox': typeof SandboxRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/solana': typeof SolanaRoute
  '/status': typeof StatusRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio-controlled': typeof StudioControlledRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/terms': typeof TermsRoute
  '/testnet': typeof TestnetRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/virality': typeof ViralityRoute
  '/royalties': typeof RoyaltiesRoute
  '/admin/byok-codes': typeof AdminByokCodesRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/mcp-usage': typeof AdminMcpUsageRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/mainnet': typeof AdminMainnetRoute
  '/admin/residency': typeof AdminResidencyRoute
  '/admin/universes': typeof AdminUniversesRoute
  '/adplacements/$slotId': typeof AdplacementsSlotIdRoute
  '/adplacements/new': typeof AdplacementsNewRoute
  '/agents/$uid': typeof AgentsUidRoute
  '/agents/dashboard': typeof AgentsDashboardRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/analytics/$universeId': typeof AnalyticsUniverseIdRoute
  '/anatomy/$universe': typeof AnatomyUniverseRoute
  '/bounties/$bountyId': typeof BountiesBountyIdRoute
  '/bounties/mine': typeof BountiesMineRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/canon/$universeId': typeof CanonUniverseIdRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/characters/$universeId': typeof CharactersUniverseIdRoute
  '/create/$kind': typeof CreateKindRoute
  '/create/likeness': typeof CreateLikenessRoute
  '/create/persona': typeof CreatePersonaRoute
  '/dashboard/personas': typeof DashboardPersonasRouteWithChildren
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/edit/inpaint': typeof EditInpaintRoute
  '/edit/outpaint': typeof EditOutpaintRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/extract/$jobId': typeof ExtractJobIdRoute
  '/governance/$universeId': typeof GovernanceUniverseIdRoute
  '/lab/gpt-image': typeof LabGptImageRoute
  '/lab/voice-studio': typeof LabVoiceStudioRoute
  '/lab/zai': typeof LabZaiRouteWithChildren
  '/lineage/$assetId': typeof LineageAssetIdRoute
  '/marketplace/likeness': typeof MarketplaceLikenessRouteWithChildren
  '/notebook/$id': typeof NotebookIdRoute
  '/oauth/siwe': typeof OauthSiweRoute
  '/order/$id': typeof OrderIdRoute
  '/play/$universeId': typeof PlayUniverseIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/sell/earnings': typeof SellEarningsRoute
  '/sell/new': typeof SellNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/wallets': typeof SettingsWalletsRoute
  '/shop/$universeId': typeof ShopUniverseIdRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/tokens/launch': typeof TokensLaunchRoute
  '/tokens/portfolio': typeof TokensPortfolioRoute
  '/tokens/swap': typeof TokensSwapRoute
  '/treasury/$universeId': typeof TreasuryUniverseIdRoute
  '/universe/$id': typeof UniverseIdRouteWithChildren
  '/wiki/$kind': typeof WikiKindRoute
  '/adplacements': typeof AdplacementsIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/bounties': typeof BountiesIndexRoute
  '/create': typeof CreateIndexRoute
  '/sell': typeof SellIndexRoute
  '/tokens': typeof TokensIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/adplacements/seeds/$seedId': typeof AdplacementsSeedsSeedIdRoute
  '/adplacements/seeds/new': typeof AdplacementsSeedsNewRoute
  '/event/$universe/$event': typeof EventUniverseEventRoute
  '/lab/zai/diagnostic': typeof LabZaiDiagnosticRoute
  '/marketplace/likeness/$listingId': typeof MarketplaceLikenessListingIdRoute
  '/marketplace/persona/$personaId': typeof MarketplacePersonaPersonaIdRoute
  '/studio/edit/$assetId': typeof StudioEditAssetIdRoute
  '/tokens/creator/$address': typeof TokensCreatorAddressRoute
  '/universe/$address/physics': typeof UniverseAddressPhysicsRoute
  '/universe/$address/polls': typeof UniverseAddressPollsRoute
  '/universe/$id/deploy-token': typeof UniverseIdDeployTokenRoute
  '/universe/$id/gallery': typeof UniverseIdGalleryRoute
  '/universe/$id/gen-config': typeof UniverseIdGenConfigRoute
  '/universe/$id/lineage': typeof UniverseIdLineageRoute
  '/universe/$id/profile': typeof UniverseIdProfileRoute
  '/universe/$id/style': typeof UniverseIdStyleRoute
  '/universe/$id/watch': typeof UniverseIdWatchRoute
  '/wiki/character/$id': typeof WikiCharacterIdRoute
  '/wiki/entity/$id': typeof WikiEntityIdRoute
  '/adplacements/seeds': typeof AdplacementsSeedsIndexRoute
  '/dashboard/personas/$personaId/edit': typeof DashboardPersonasPersonaIdEditRoute
  '/lab/zai/video/$jobId': typeof LabZaiVideoJobIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/ad-reference': typeof AdReferenceRoute
  '/bridge': typeof BridgeRoute
  '/canvas': typeof CanvasRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/cinematicUniverseCreate': typeof CinematicUniverseCreateRoute
  '/coming-soon': typeof ComingSoonRoute
  '/counter-notice': typeof CounterNoticeRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/docs': typeof DocsRoute
  '/editor': typeof EditorRoute
  '/faucet': typeof FaucetRoute
  '/gallery': typeof GalleryRoute
  '/leaderboard': typeof LeaderboardRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/marketing': typeof MarketingRoute
  '/my-works': typeof MyWorksRoute
  '/notebook': typeof NotebookRouteWithChildren
  '/notifications': typeof NotificationsRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/relight': typeof RelightRoute
  '/residency': typeof ResidencyRoute
  '/sandbox': typeof SandboxRoute
  '/search': typeof SearchRoute
  '/series': typeof SeriesRoute
  '/solana': typeof SolanaRoute
  '/status': typeof StatusRoute
  '/studio': typeof StudioRouteWithChildren
  '/studio-controlled': typeof StudioControlledRoute
  '/subscriptions': typeof SubscriptionsRoute
  '/terms': typeof TermsRoute
  '/testnet': typeof TestnetRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/virality': typeof ViralityRoute
  '/royalties': typeof RoyaltiesRoute
  '/admin/byok-codes': typeof AdminByokCodesRoute
  '/admin/cost': typeof AdminCostRoute
  '/admin/mcp-usage': typeof AdminMcpUsageRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/admin/ops': typeof AdminOpsRoute
  '/admin/mainnet': typeof AdminMainnetRoute
  '/admin/residency': typeof AdminResidencyRoute
  '/admin/universes': typeof AdminUniversesRoute
  '/adplacements/$slotId': typeof AdplacementsSlotIdRoute
  '/adplacements/new': typeof AdplacementsNewRoute
  '/agents/$uid': typeof AgentsUidRoute
  '/agents/dashboard': typeof AgentsDashboardRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/analytics/$universeId': typeof AnalyticsUniverseIdRoute
  '/anatomy/$universe': typeof AnatomyUniverseRoute
  '/bounties/$bountyId': typeof BountiesBountyIdRoute
  '/bounties/mine': typeof BountiesMineRoute
  '/brand/dashboard': typeof BrandDashboardRoute
  '/canon/$universeId': typeof CanonUniverseIdRoute
  '/canvas/$canvasId': typeof CanvasCanvasIdRoute
  '/characters/$universeId': typeof CharactersUniverseIdRoute
  '/create/$kind': typeof CreateKindRoute
  '/create/likeness': typeof CreateLikenessRoute
  '/create/persona': typeof CreatePersonaRoute
  '/dashboard/personas': typeof DashboardPersonasRouteWithChildren
  '/dashboard/revenue': typeof DashboardRevenueRoute
  '/edit/inpaint': typeof EditInpaintRoute
  '/edit/outpaint': typeof EditOutpaintRoute
  '/episode/$id': typeof EpisodeIdRoute
  '/extract/$jobId': typeof ExtractJobIdRoute
  '/governance/$universeId': typeof GovernanceUniverseIdRoute
  '/lab/gpt-image': typeof LabGptImageRoute
  '/lab/voice-studio': typeof LabVoiceStudioRoute
  '/lab/zai': typeof LabZaiRouteWithChildren
  '/lineage/$assetId': typeof LineageAssetIdRoute
  '/marketplace/likeness': typeof MarketplaceLikenessRouteWithChildren
  '/notebook/$id': typeof NotebookIdRoute
  '/oauth/siwe': typeof OauthSiweRoute
  '/order/$id': typeof OrderIdRoute
  '/play/$universeId': typeof PlayUniverseIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/sell/earnings': typeof SellEarningsRoute
  '/sell/new': typeof SellNewRoute
  '/settings/api-keys': typeof SettingsApiKeysRoute
  '/settings/usage': typeof SettingsUsageRoute
  '/settings/wallets': typeof SettingsWalletsRoute
  '/shop/$universeId': typeof ShopUniverseIdRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/tokens/launch': typeof TokensLaunchRoute
  '/tokens/portfolio': typeof TokensPortfolioRoute
  '/tokens/swap': typeof TokensSwapRoute
  '/treasury/$universeId': typeof TreasuryUniverseIdRoute
  '/universe/$id': typeof UniverseIdRouteWithChildren
  '/wiki/$kind': typeof WikiKindRoute
  '/adplacements/': typeof AdplacementsIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/bounties/': typeof BountiesIndexRoute
  '/create/': typeof CreateIndexRoute
  '/sell/': typeof SellIndexRoute
  '/tokens/': typeof TokensIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/adplacements/seeds/$seedId': typeof AdplacementsSeedsSeedIdRoute
  '/adplacements/seeds/new': typeof AdplacementsSeedsNewRoute
  '/event/$universe/$event': typeof EventUniverseEventRoute
  '/lab/zai/diagnostic': typeof LabZaiDiagnosticRoute
  '/marketplace/likeness/$listingId': typeof MarketplaceLikenessListingIdRoute
  '/marketplace/persona/$personaId': typeof MarketplacePersonaPersonaIdRoute
  '/studio/edit/$assetId': typeof StudioEditAssetIdRoute
  '/tokens/creator/$address': typeof TokensCreatorAddressRoute
  '/universe/$address/physics': typeof UniverseAddressPhysicsRoute
  '/universe/$address/polls': typeof UniverseAddressPollsRoute
  '/universe/$id/deploy-token': typeof UniverseIdDeployTokenRoute
  '/universe/$id/gallery': typeof UniverseIdGalleryRoute
  '/universe/$id/gen-config': typeof UniverseIdGenConfigRoute
  '/universe/$id/lineage': typeof UniverseIdLineageRoute
  '/universe/$id/profile': typeof UniverseIdProfileRoute
  '/universe/$id/style': typeof UniverseIdStyleRoute
  '/universe/$id/watch': typeof UniverseIdWatchRoute
  '/wiki/character/$id': typeof WikiCharacterIdRoute
  '/wiki/entity/$id': typeof WikiEntityIdRoute
  '/adplacements/seeds/': typeof AdplacementsSeedsIndexRoute
  '/dashboard/personas/$personaId/edit': typeof DashboardPersonasPersonaIdEditRoute
  '/lab/zai/video/$jobId': typeof LabZaiVideoJobIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/ad-reference'
    | '/bridge'
    | '/canvas'
    | '/checkout'
    | '/cinematicUniverseCreate'
    | '/coming-soon'
    | '/counter-notice'
    | '/credits'
    | '/dashboard'
    | '/discover'
    | '/dmca'
    | '/docs'
    | '/editor'
    | '/faucet'
    | '/gallery'
    | '/leaderboard'
    | '/login'
    | '/market'
    | '/marketing'
    | '/my-works'
    | '/notebook'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/relight'
    | '/residency'
    | '/sandbox'
    | '/search'
    | '/series'
    | '/solana'
    | '/status'
    | '/studio'
    | '/studio-controlled'
    | '/subscriptions'
    | '/terms'
    | '/testnet'
    | '/upload'
    | '/videos'
    | '/virality'
    | '/royalties'
    | '/admin/byok-codes'
    | '/admin/cost'
    | '/admin/mcp-usage'
    | '/admin/moderation'
    | '/admin/ops'
    | '/admin/mainnet'
    | '/admin/residency'
    | '/admin/universes'
    | '/adplacements/$slotId'
    | '/adplacements/new'
    | '/agents/$uid'
    | '/agents/dashboard'
    | '/agents/register'
    | '/analytics/$universeId'
    | '/anatomy/$universe'
    | '/bounties/$bountyId'
    | '/bounties/mine'
    | '/brand/dashboard'
    | '/canon/$universeId'
    | '/canvas/$canvasId'
    | '/characters/$universeId'
    | '/create/$kind'
    | '/create/likeness'
    | '/create/persona'
    | '/dashboard/personas'
    | '/dashboard/revenue'
    | '/edit/inpaint'
    | '/edit/outpaint'
    | '/episode/$id'
    | '/extract/$jobId'
    | '/governance/$universeId'
    | '/lab/gpt-image'
    | '/lab/voice-studio'
    | '/lab/zai'
    | '/lineage/$assetId'
    | '/marketplace/likeness'
    | '/notebook/$id'
    | '/oauth/siwe'
    | '/order/$id'
    | '/play/$universeId'
    | '/product/$id'
    | '/profile/$username'
    | '/profile/edit'
    | '/sell/earnings'
    | '/sell/new'
    | '/settings/api-keys'
    | '/settings/usage'
    | '/settings/wallets'
    | '/shop/$universeId'
    | '/tokens/$address'
    | '/tokens/launch'
    | '/tokens/portfolio'
    | '/tokens/swap'
    | '/treasury/$universeId'
    | '/universe/$id'
    | '/wiki/$kind'
    | '/adplacements/'
    | '/agents/'
    | '/bounties/'
    | '/create/'
    | '/sell/'
    | '/tokens/'
    | '/wiki/'
    | '/adplacements/seeds/$seedId'
    | '/adplacements/seeds/new'
    | '/event/$universe/$event'
    | '/lab/zai/diagnostic'
    | '/marketplace/likeness/$listingId'
    | '/marketplace/persona/$personaId'
    | '/studio/edit/$assetId'
    | '/tokens/creator/$address'
    | '/universe/$address/physics'
    | '/universe/$address/polls'
    | '/universe/$id/deploy-token'
    | '/universe/$id/gallery'
    | '/universe/$id/gen-config'
    | '/universe/$id/lineage'
    | '/universe/$id/profile'
    | '/universe/$id/style'
    | '/universe/$id/watch'
    | '/wiki/character/$id'
    | '/wiki/entity/$id'
    | '/adplacements/seeds/'
    | '/dashboard/personas/$personaId/edit'
    | '/lab/zai/video/$jobId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/ad-reference'
    | '/bridge'
    | '/canvas'
    | '/checkout'
    | '/cinematicUniverseCreate'
    | '/coming-soon'
    | '/counter-notice'
    | '/credits'
    | '/dashboard'
    | '/discover'
    | '/dmca'
    | '/docs'
    | '/editor'
    | '/faucet'
    | '/gallery'
    | '/leaderboard'
    | '/login'
    | '/market'
    | '/marketing'
    | '/my-works'
    | '/notebook'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/relight'
    | '/residency'
    | '/sandbox'
    | '/search'
    | '/series'
    | '/solana'
    | '/status'
    | '/studio'
    | '/studio-controlled'
    | '/subscriptions'
    | '/terms'
    | '/testnet'
    | '/upload'
    | '/videos'
    | '/virality'
    | '/royalties'
    | '/admin/byok-codes'
    | '/admin/cost'
    | '/admin/mcp-usage'
    | '/admin/moderation'
    | '/admin/ops'
    | '/admin/mainnet'
    | '/admin/residency'
    | '/admin/universes'
    | '/adplacements/$slotId'
    | '/adplacements/new'
    | '/agents/$uid'
    | '/agents/dashboard'
    | '/agents/register'
    | '/analytics/$universeId'
    | '/anatomy/$universe'
    | '/bounties/$bountyId'
    | '/bounties/mine'
    | '/brand/dashboard'
    | '/canon/$universeId'
    | '/canvas/$canvasId'
    | '/characters/$universeId'
    | '/create/$kind'
    | '/create/likeness'
    | '/create/persona'
    | '/dashboard/personas'
    | '/dashboard/revenue'
    | '/edit/inpaint'
    | '/edit/outpaint'
    | '/episode/$id'
    | '/extract/$jobId'
    | '/governance/$universeId'
    | '/lab/gpt-image'
    | '/lab/voice-studio'
    | '/lab/zai'
    | '/lineage/$assetId'
    | '/marketplace/likeness'
    | '/notebook/$id'
    | '/oauth/siwe'
    | '/order/$id'
    | '/play/$universeId'
    | '/product/$id'
    | '/profile/$username'
    | '/profile/edit'
    | '/sell/earnings'
    | '/sell/new'
    | '/settings/api-keys'
    | '/settings/usage'
    | '/settings/wallets'
    | '/shop/$universeId'
    | '/tokens/$address'
    | '/tokens/launch'
    | '/tokens/portfolio'
    | '/tokens/swap'
    | '/treasury/$universeId'
    | '/universe/$id'
    | '/wiki/$kind'
    | '/adplacements'
    | '/agents'
    | '/bounties'
    | '/create'
    | '/sell'
    | '/tokens'
    | '/wiki'
    | '/adplacements/seeds/$seedId'
    | '/adplacements/seeds/new'
    | '/event/$universe/$event'
    | '/lab/zai/diagnostic'
    | '/marketplace/likeness/$listingId'
    | '/marketplace/persona/$personaId'
    | '/studio/edit/$assetId'
    | '/tokens/creator/$address'
    | '/universe/$address/physics'
    | '/universe/$address/polls'
    | '/universe/$id/deploy-token'
    | '/universe/$id/gallery'
    | '/universe/$id/gen-config'
    | '/universe/$id/lineage'
    | '/universe/$id/profile'
    | '/universe/$id/style'
    | '/universe/$id/watch'
    | '/wiki/character/$id'
    | '/wiki/entity/$id'
    | '/adplacements/seeds'
    | '/dashboard/personas/$personaId/edit'
    | '/lab/zai/video/$jobId'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/ad-reference'
    | '/bridge'
    | '/canvas'
    | '/checkout'
    | '/cinematicUniverseCreate'
    | '/coming-soon'
    | '/counter-notice'
    | '/credits'
    | '/dashboard'
    | '/discover'
    | '/dmca'
    | '/docs'
    | '/editor'
    | '/faucet'
    | '/gallery'
    | '/leaderboard'
    | '/login'
    | '/market'
    | '/marketing'
    | '/my-works'
    | '/notebook'
    | '/notifications'
    | '/pricing'
    | '/privacy'
    | '/relight'
    | '/residency'
    | '/sandbox'
    | '/search'
    | '/series'
    | '/solana'
    | '/status'
    | '/studio'
    | '/studio-controlled'
    | '/subscriptions'
    | '/terms'
    | '/testnet'
    | '/upload'
    | '/videos'
    | '/virality'
    | '/royalties'
    | '/admin/byok-codes'
    | '/admin/cost'
    | '/admin/mcp-usage'
    | '/admin/moderation'
    | '/admin/ops'
    | '/admin/mainnet'
    | '/admin/residency'
    | '/admin/universes'
    | '/adplacements/$slotId'
    | '/adplacements/new'
    | '/agents/$uid'
    | '/agents/dashboard'
    | '/agents/register'
    | '/analytics/$universeId'
    | '/anatomy/$universe'
    | '/bounties/$bountyId'
    | '/bounties/mine'
    | '/brand/dashboard'
    | '/canon/$universeId'
    | '/canvas/$canvasId'
    | '/characters/$universeId'
    | '/create/$kind'
    | '/create/likeness'
    | '/create/persona'
    | '/dashboard/personas'
    | '/dashboard/revenue'
    | '/edit/inpaint'
    | '/edit/outpaint'
    | '/episode/$id'
    | '/extract/$jobId'
    | '/governance/$universeId'
    | '/lab/gpt-image'
    | '/lab/voice-studio'
    | '/lab/zai'
    | '/lineage/$assetId'
    | '/marketplace/likeness'
    | '/notebook/$id'
    | '/oauth/siwe'
    | '/order/$id'
    | '/play/$universeId'
    | '/product/$id'
    | '/profile/$username'
    | '/profile/edit'
    | '/sell/earnings'
    | '/sell/new'
    | '/settings/api-keys'
    | '/settings/usage'
    | '/settings/wallets'
    | '/shop/$universeId'
    | '/tokens/$address'
    | '/tokens/launch'
    | '/tokens/portfolio'
    | '/tokens/swap'
    | '/treasury/$universeId'
    | '/universe/$id'
    | '/wiki/$kind'
    | '/adplacements/'
    | '/agents/'
    | '/bounties/'
    | '/create/'
    | '/sell/'
    | '/tokens/'
    | '/wiki/'
    | '/adplacements/seeds/$seedId'
    | '/adplacements/seeds/new'
    | '/event/$universe/$event'
    | '/lab/zai/diagnostic'
    | '/marketplace/likeness/$listingId'
    | '/marketplace/persona/$personaId'
    | '/studio/edit/$assetId'
    | '/tokens/creator/$address'
    | '/universe/$address/physics'
    | '/universe/$address/polls'
    | '/universe/$id/deploy-token'
    | '/universe/$id/gallery'
    | '/universe/$id/gen-config'
    | '/universe/$id/lineage'
    | '/universe/$id/profile'
    | '/universe/$id/style'
    | '/universe/$id/watch'
    | '/wiki/character/$id'
    | '/wiki/entity/$id'
    | '/adplacements/seeds/'
    | '/dashboard/personas/$personaId/edit'
    | '/lab/zai/video/$jobId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AdReferenceRoute: typeof AdReferenceRoute
  BridgeRoute: typeof BridgeRoute
  CanvasRoute: typeof CanvasRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  CinematicUniverseCreateRoute: typeof CinematicUniverseCreateRoute
  ComingSoonRoute: typeof ComingSoonRoute
  CounterNoticeRoute: typeof CounterNoticeRoute
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  DiscoverRoute: typeof DiscoverRoute
  DmcaRoute: typeof DmcaRoute
  DocsRoute: typeof DocsRoute
  EditorRoute: typeof EditorRoute
  FaucetRoute: typeof FaucetRoute
  GalleryRoute: typeof GalleryRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  MarketingRoute: typeof MarketingRoute
  MyWorksRoute: typeof MyWorksRoute
  NotebookRoute: typeof NotebookRouteWithChildren
  NotificationsRoute: typeof NotificationsRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RelightRoute: typeof RelightRoute
  ResidencyRoute: typeof ResidencyRoute
  SandboxRoute: typeof SandboxRoute
  SearchRoute: typeof SearchRoute
  SeriesRoute: typeof SeriesRoute
  SolanaRoute: typeof SolanaRoute
  StatusRoute: typeof StatusRoute
  StudioRoute: typeof StudioRouteWithChildren
  StudioControlledRoute: typeof StudioControlledRoute
  SubscriptionsRoute: typeof SubscriptionsRoute
  TermsRoute: typeof TermsRoute
  TestnetRoute: typeof TestnetRoute
  UploadRoute: typeof UploadRoute
  VideosRoute: typeof VideosRoute
  ViralityRoute: typeof ViralityRoute
  RoyaltiesRoute: typeof RoyaltiesRoute
  AdminByokCodesRoute: typeof AdminByokCodesRoute
  AdminCostRoute: typeof AdminCostRoute
  AdminMcpUsageRoute: typeof AdminMcpUsageRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdminOpsRoute: typeof AdminOpsRoute
  AdminMainnetRoute: typeof AdminMainnetRoute
  AdminResidencyRoute: typeof AdminResidencyRoute
  AdminUniversesRoute: typeof AdminUniversesRoute
  AdplacementsSlotIdRoute: typeof AdplacementsSlotIdRoute
  AdplacementsNewRoute: typeof AdplacementsNewRoute
  AgentsUidRoute: typeof AgentsUidRoute
  AgentsDashboardRoute: typeof AgentsDashboardRoute
  AgentsRegisterRoute: typeof AgentsRegisterRoute
  AnalyticsUniverseIdRoute: typeof AnalyticsUniverseIdRoute
  AnatomyUniverseRoute: typeof AnatomyUniverseRoute
  BountiesBountyIdRoute: typeof BountiesBountyIdRoute
  BountiesMineRoute: typeof BountiesMineRoute
  BrandDashboardRoute: typeof BrandDashboardRoute
  CanonUniverseIdRoute: typeof CanonUniverseIdRoute
  CharactersUniverseIdRoute: typeof CharactersUniverseIdRoute
  CreateKindRoute: typeof CreateKindRoute
  CreateLikenessRoute: typeof CreateLikenessRoute
  CreatePersonaRoute: typeof CreatePersonaRoute
  EditInpaintRoute: typeof EditInpaintRoute
  EditOutpaintRoute: typeof EditOutpaintRoute
  EpisodeIdRoute: typeof EpisodeIdRoute
  ExtractJobIdRoute: typeof ExtractJobIdRoute
  GovernanceUniverseIdRoute: typeof GovernanceUniverseIdRoute
  LabGptImageRoute: typeof LabGptImageRoute
  LabVoiceStudioRoute: typeof LabVoiceStudioRoute
  LabZaiRoute: typeof LabZaiRouteWithChildren
  LineageAssetIdRoute: typeof LineageAssetIdRoute
  MarketplaceLikenessRoute: typeof MarketplaceLikenessRouteWithChildren
  OauthSiweRoute: typeof OauthSiweRoute
  OrderIdRoute: typeof OrderIdRoute
  PlayUniverseIdRoute: typeof PlayUniverseIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ProfileEditRoute: typeof ProfileEditRoute
  SellEarningsRoute: typeof SellEarningsRoute
  SellNewRoute: typeof SellNewRoute
  SettingsApiKeysRoute: typeof SettingsApiKeysRoute
  SettingsUsageRoute: typeof SettingsUsageRoute
  SettingsWalletsRoute: typeof SettingsWalletsRoute
  ShopUniverseIdRoute: typeof ShopUniverseIdRoute
  TokensAddressRoute: typeof TokensAddressRoute
  TokensLaunchRoute: typeof TokensLaunchRoute
  TokensPortfolioRoute: typeof TokensPortfolioRoute
  TokensSwapRoute: typeof TokensSwapRoute
  TreasuryUniverseIdRoute: typeof TreasuryUniverseIdRoute
  UniverseIdRoute: typeof UniverseIdRouteWithChildren
  WikiKindRoute: typeof WikiKindRoute
  AdplacementsIndexRoute: typeof AdplacementsIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BountiesIndexRoute: typeof BountiesIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
  SellIndexRoute: typeof SellIndexRoute
  TokensIndexRoute: typeof TokensIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
  AdplacementsSeedsSeedIdRoute: typeof AdplacementsSeedsSeedIdRoute
  AdplacementsSeedsNewRoute: typeof AdplacementsSeedsNewRoute
  EventUniverseEventRoute: typeof EventUniverseEventRoute
  MarketplacePersonaPersonaIdRoute: typeof MarketplacePersonaPersonaIdRoute
  TokensCreatorAddressRoute: typeof TokensCreatorAddressRoute
  UniverseAddressPhysicsRoute: typeof UniverseAddressPhysicsRoute
  UniverseAddressPollsRoute: typeof UniverseAddressPollsRoute
  WikiCharacterIdRoute: typeof WikiCharacterIdRoute
  WikiEntityIdRoute: typeof WikiEntityIdRoute
  AdplacementsSeedsIndexRoute: typeof AdplacementsSeedsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/virality': {
      id: '/virality'
      path: '/virality'
      fullPath: '/virality'
      preLoaderRoute: typeof ViralityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/royalties': {
      id: '/royalties'
      path: '/royalties'
      fullPath: '/royalties'
      preLoaderRoute: typeof RoyaltiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/testnet': {
      id: '/testnet'
      path: '/testnet'
      fullPath: '/testnet'
      preLoaderRoute: typeof TestnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/subscriptions': {
      id: '/subscriptions'
      path: '/subscriptions'
      fullPath: '/subscriptions'
      preLoaderRoute: typeof SubscriptionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio-controlled': {
      id: '/studio-controlled'
      path: '/studio-controlled'
      fullPath: '/studio-controlled'
      preLoaderRoute: typeof StudioControlledRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/status': {
      id: '/status'
      path: '/status'
      fullPath: '/status'
      preLoaderRoute: typeof StatusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solana': {
      id: '/solana'
      path: '/solana'
      fullPath: '/solana'
      preLoaderRoute: typeof SolanaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/series': {
      id: '/series'
      path: '/series'
      fullPath: '/series'
      preLoaderRoute: typeof SeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/residency': {
      id: '/residency'
      path: '/residency'
      fullPath: '/residency'
      preLoaderRoute: typeof ResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relight': {
      id: '/relight'
      path: '/relight'
      fullPath: '/relight'
      preLoaderRoute: typeof RelightRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook': {
      id: '/notebook'
      path: '/notebook'
      fullPath: '/notebook'
      preLoaderRoute: typeof NotebookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-works': {
      id: '/my-works'
      path: '/my-works'
      fullPath: '/my-works'
      preLoaderRoute: typeof MyWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketing': {
      id: '/marketing'
      path: '/marketing'
      fullPath: '/marketing'
      preLoaderRoute: typeof MarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faucet': {
      id: '/faucet'
      path: '/faucet'
      fullPath: '/faucet'
      preLoaderRoute: typeof FaucetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/editor': {
      id: '/editor'
      path: '/editor'
      fullPath: '/editor'
      preLoaderRoute: typeof EditorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/counter-notice': {
      id: '/counter-notice'
      path: '/counter-notice'
      fullPath: '/counter-notice'
      preLoaderRoute: typeof CounterNoticeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinematicUniverseCreate': {
      id: '/cinematicUniverseCreate'
      path: '/cinematicUniverseCreate'
      fullPath: '/cinematicUniverseCreate'
      preLoaderRoute: typeof CinematicUniverseCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas': {
      id: '/canvas'
      path: '/canvas'
      fullPath: '/canvas'
      preLoaderRoute: typeof CanvasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bridge': {
      id: '/bridge'
      path: '/bridge'
      fullPath: '/bridge'
      preLoaderRoute: typeof BridgeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ad-reference': {
      id: '/ad-reference'
      path: '/ad-reference'
      fullPath: '/ad-reference'
      preLoaderRoute: typeof AdReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/': {
      id: '/tokens/'
      path: '/tokens'
      fullPath: '/tokens/'
      preLoaderRoute: typeof TokensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/': {
      id: '/bounties/'
      path: '/bounties'
      fullPath: '/bounties/'
      preLoaderRoute: typeof BountiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adplacements/': {
      id: '/adplacements/'
      path: '/adplacements'
      fullPath: '/adplacements/'
      preLoaderRoute: typeof AdplacementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/$kind': {
      id: '/wiki/$kind'
      path: '/wiki/$kind'
      fullPath: '/wiki/$kind'
      preLoaderRoute: typeof WikiKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe/$id': {
      id: '/universe/$id'
      path: '/universe/$id'
      fullPath: '/universe/$id'
      preLoaderRoute: typeof UniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury/$universeId': {
      id: '/treasury/$universeId'
      path: '/treasury/$universeId'
      fullPath: '/treasury/$universeId'
      preLoaderRoute: typeof TreasuryUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/swap': {
      id: '/tokens/swap'
      path: '/tokens/swap'
      fullPath: '/tokens/swap'
      preLoaderRoute: typeof TokensSwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/portfolio': {
      id: '/tokens/portfolio'
      path: '/tokens/portfolio'
      fullPath: '/tokens/portfolio'
      preLoaderRoute: typeof TokensPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/launch': {
      id: '/tokens/launch'
      path: '/tokens/launch'
      fullPath: '/tokens/launch'
      preLoaderRoute: typeof TokensLaunchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$address': {
      id: '/tokens/$address'
      path: '/tokens/$address'
      fullPath: '/tokens/$address'
      preLoaderRoute: typeof TokensAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$universeId': {
      id: '/shop/$universeId'
      path: '/shop/$universeId'
      fullPath: '/shop/$universeId'
      preLoaderRoute: typeof ShopUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/wallets': {
      id: '/settings/wallets'
      path: '/settings/wallets'
      fullPath: '/settings/wallets'
      preLoaderRoute: typeof SettingsWalletsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/usage': {
      id: '/settings/usage'
      path: '/settings/usage'
      fullPath: '/settings/usage'
      preLoaderRoute: typeof SettingsUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/api-keys': {
      id: '/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof SettingsApiKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/new': {
      id: '/sell/new'
      path: '/sell/new'
      fullPath: '/sell/new'
      preLoaderRoute: typeof SellNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/earnings': {
      id: '/sell/earnings'
      path: '/sell/earnings'
      fullPath: '/sell/earnings'
      preLoaderRoute: typeof SellEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$universeId': {
      id: '/play/$universeId'
      path: '/play/$universeId'
      fullPath: '/play/$universeId'
      preLoaderRoute: typeof PlayUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oauth/siwe': {
      id: '/oauth/siwe'
      path: '/oauth/siwe'
      fullPath: '/oauth/siwe'
      preLoaderRoute: typeof OauthSiweRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebook/$id': {
      id: '/notebook/$id'
      path: '/$id'
      fullPath: '/notebook/$id'
      preLoaderRoute: typeof NotebookIdRouteImport
      parentRoute: typeof NotebookRoute
    }
    '/marketplace/likeness': {
      id: '/marketplace/likeness'
      path: '/marketplace/likeness'
      fullPath: '/marketplace/likeness'
      preLoaderRoute: typeof MarketplaceLikenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lineage/$assetId': {
      id: '/lineage/$assetId'
      path: '/lineage/$assetId'
      fullPath: '/lineage/$assetId'
      preLoaderRoute: typeof LineageAssetIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/zai': {
      id: '/lab/zai'
      path: '/lab/zai'
      fullPath: '/lab/zai'
      preLoaderRoute: typeof LabZaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/voice-studio': {
      id: '/lab/voice-studio'
      path: '/lab/voice-studio'
      fullPath: '/lab/voice-studio'
      preLoaderRoute: typeof LabVoiceStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/gpt-image': {
      id: '/lab/gpt-image'
      path: '/lab/gpt-image'
      fullPath: '/lab/gpt-image'
      preLoaderRoute: typeof LabGptImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/$universeId': {
      id: '/governance/$universeId'
      path: '/governance/$universeId'
      fullPath: '/governance/$universeId'
      preLoaderRoute: typeof GovernanceUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/extract/$jobId': {
      id: '/extract/$jobId'
      path: '/extract/$jobId'
      fullPath: '/extract/$jobId'
      preLoaderRoute: typeof ExtractJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/episode/$id': {
      id: '/episode/$id'
      path: '/episode/$id'
      fullPath: '/episode/$id'
      preLoaderRoute: typeof EpisodeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/outpaint': {
      id: '/edit/outpaint'
      path: '/edit/outpaint'
      fullPath: '/edit/outpaint'
      preLoaderRoute: typeof EditOutpaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit/inpaint': {
      id: '/edit/inpaint'
      path: '/edit/inpaint'
      fullPath: '/edit/inpaint'
      preLoaderRoute: typeof EditInpaintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/revenue': {
      id: '/dashboard/revenue'
      path: '/revenue'
      fullPath: '/dashboard/revenue'
      preLoaderRoute: typeof DashboardRevenueRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/personas': {
      id: '/dashboard/personas'
      path: '/personas'
      fullPath: '/dashboard/personas'
      preLoaderRoute: typeof DashboardPersonasRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/create/persona': {
      id: '/create/persona'
      path: '/create/persona'
      fullPath: '/create/persona'
      preLoaderRoute: typeof CreatePersonaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/likeness': {
      id: '/create/likeness'
      path: '/create/likeness'
      fullPath: '/create/likeness'
      preLoaderRoute: typeof CreateLikenessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$kind': {
      id: '/create/$kind'
      path: '/create/$kind'
      fullPath: '/create/$kind'
      preLoaderRoute: typeof CreateKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/characters/$universeId': {
      id: '/characters/$universeId'
      path: '/characters/$universeId'
      fullPath: '/characters/$universeId'
      preLoaderRoute: typeof CharactersUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canvas/$canvasId': {
      id: '/canvas/$canvasId'
      path: '/$canvasId'
      fullPath: '/canvas/$canvasId'
      preLoaderRoute: typeof CanvasCanvasIdRouteImport
      parentRoute: typeof CanvasRoute
    }
    '/canon/$universeId': {
      id: '/canon/$universeId'
      path: '/canon/$universeId'
      fullPath: '/canon/$universeId'
      preLoaderRoute: typeof CanonUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brand/dashboard': {
      id: '/brand/dashboard'
      path: '/brand/dashboard'
      fullPath: '/brand/dashboard'
      preLoaderRoute: typeof BrandDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/mine': {
      id: '/bounties/mine'
      path: '/bounties/mine'
      fullPath: '/bounties/mine'
      preLoaderRoute: typeof BountiesMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/$bountyId': {
      id: '/bounties/$bountyId'
      path: '/bounties/$bountyId'
      fullPath: '/bounties/$bountyId'
      preLoaderRoute: typeof BountiesBountyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anatomy/$universe': {
      id: '/anatomy/$universe'
      path: '/anatomy/$universe'
      fullPath: '/anatomy/$universe'
      preLoaderRoute: typeof AnatomyUniverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics/$universeId': {
      id: '/analytics/$universeId'
      path: '/analytics/$universeId'
      fullPath: '/analytics/$universeId'
      preLoaderRoute: typeof AnalyticsUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/register': {
      id: '/agents/register'
      path: '/agents/register'
      fullPath: '/agents/register'
      preLoaderRoute: typeof AgentsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/dashboard': {
      id: '/agents/dashboard'
      path: '/agents/dashboard'
      fullPath: '/agents/dashboard'
      preLoaderRoute: typeof AgentsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$uid': {
      id: '/agents/$uid'
      path: '/agents/$uid'
      fullPath: '/agents/$uid'
      preLoaderRoute: typeof AgentsUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adplacements/new': {
      id: '/adplacements/new'
      path: '/adplacements/new'
      fullPath: '/adplacements/new'
      preLoaderRoute: typeof AdplacementsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adplacements/$slotId': {
      id: '/adplacements/$slotId'
      path: '/adplacements/$slotId'
      fullPath: '/adplacements/$slotId'
      preLoaderRoute: typeof AdplacementsSlotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/universes': {
      id: '/admin/universes'
      path: '/admin/universes'
      fullPath: '/admin/universes'
      preLoaderRoute: typeof AdminUniversesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/residency': {
      id: '/admin/residency'
      path: '/admin/residency'
      fullPath: '/admin/residency'
      preLoaderRoute: typeof AdminResidencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/ops': {
      id: '/admin/ops'
      path: '/admin/ops'
      fullPath: '/admin/ops'
      preLoaderRoute: typeof AdminOpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mainnet': {
      id: '/admin/mainnet'
      path: '/admin/mainnet'
      fullPath: '/admin/mainnet'
      preLoaderRoute: typeof AdminMainnetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/mcp-usage': {
      id: '/admin/mcp-usage'
      path: '/admin/mcp-usage'
      fullPath: '/admin/mcp-usage'
      preLoaderRoute: typeof AdminMcpUsageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cost': {
      id: '/admin/cost'
      path: '/admin/cost'
      fullPath: '/admin/cost'
      preLoaderRoute: typeof AdminCostRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/byok-codes': {
      id: '/admin/byok-codes'
      path: '/admin/byok-codes'
      fullPath: '/admin/byok-codes'
      preLoaderRoute: typeof AdminByokCodesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adplacements/seeds/': {
      id: '/adplacements/seeds/'
      path: '/adplacements/seeds'
      fullPath: '/adplacements/seeds/'
      preLoaderRoute: typeof AdplacementsSeedsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/entity/$id': {
      id: '/wiki/entity/$id'
      path: '/wiki/entity/$id'
      fullPath: '/wiki/entity/$id'
      preLoaderRoute: typeof WikiEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/character/$id': {
      id: '/wiki/character/$id'
      path: '/wiki/character/$id'
      fullPath: '/wiki/character/$id'
      preLoaderRoute: typeof WikiCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe/$id/watch': {
      id: '/universe/$id/watch'
      path: '/watch'
      fullPath: '/universe/$id/watch'
      preLoaderRoute: typeof UniverseIdWatchRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/universe/$id/style': {
      id: '/universe/$id/style'
      path: '/style'
      fullPath: '/universe/$id/style'
      preLoaderRoute: typeof UniverseIdStyleRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/universe/$id/profile': {
      id: '/universe/$id/profile'
      path: '/profile'
      fullPath: '/universe/$id/profile'
      preLoaderRoute: typeof UniverseIdProfileRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/universe/$id/lineage': {
      id: '/universe/$id/lineage'
      path: '/lineage'
      fullPath: '/universe/$id/lineage'
      preLoaderRoute: typeof UniverseIdLineageRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/universe/$id/gen-config': {
      id: '/universe/$id/gen-config'
      path: '/gen-config'
      fullPath: '/universe/$id/gen-config'
      preLoaderRoute: typeof UniverseIdGenConfigRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/universe/$id/gallery': {
      id: '/universe/$id/gallery'
      path: '/gallery'
      fullPath: '/universe/$id/gallery'
      preLoaderRoute: typeof UniverseIdGalleryRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/universe/$id/deploy-token': {
      id: '/universe/$id/deploy-token'
      path: '/deploy-token'
      fullPath: '/universe/$id/deploy-token'
      preLoaderRoute: typeof UniverseIdDeployTokenRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/universe/$address/polls': {
      id: '/universe/$address/polls'
      path: '/universe/$address/polls'
      fullPath: '/universe/$address/polls'
      preLoaderRoute: typeof UniverseAddressPollsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe/$address/physics': {
      id: '/universe/$address/physics'
      path: '/universe/$address/physics'
      fullPath: '/universe/$address/physics'
      preLoaderRoute: typeof UniverseAddressPhysicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/creator/$address': {
      id: '/tokens/creator/$address'
      path: '/tokens/creator/$address'
      fullPath: '/tokens/creator/$address'
      preLoaderRoute: typeof TokensCreatorAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio/edit/$assetId': {
      id: '/studio/edit/$assetId'
      path: '/edit/$assetId'
      fullPath: '/studio/edit/$assetId'
      preLoaderRoute: typeof StudioEditAssetIdRouteImport
      parentRoute: typeof StudioRoute
    }
    '/marketplace/persona/$personaId': {
      id: '/marketplace/persona/$personaId'
      path: '/marketplace/persona/$personaId'
      fullPath: '/marketplace/persona/$personaId'
      preLoaderRoute: typeof MarketplacePersonaPersonaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace/likeness/$listingId': {
      id: '/marketplace/likeness/$listingId'
      path: '/$listingId'
      fullPath: '/marketplace/likeness/$listingId'
      preLoaderRoute: typeof MarketplaceLikenessListingIdRouteImport
      parentRoute: typeof MarketplaceLikenessRoute
    }
    '/lab/zai/diagnostic': {
      id: '/lab/zai/diagnostic'
      path: '/diagnostic'
      fullPath: '/lab/zai/diagnostic'
      preLoaderRoute: typeof LabZaiDiagnosticRouteImport
      parentRoute: typeof LabZaiRoute
    }
    '/event/$universe/$event': {
      id: '/event/$universe/$event'
      path: '/event/$universe/$event'
      fullPath: '/event/$universe/$event'
      preLoaderRoute: typeof EventUniverseEventRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adplacements/seeds/new': {
      id: '/adplacements/seeds/new'
      path: '/adplacements/seeds/new'
      fullPath: '/adplacements/seeds/new'
      preLoaderRoute: typeof AdplacementsSeedsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adplacements/seeds/$seedId': {
      id: '/adplacements/seeds/$seedId'
      path: '/adplacements/seeds/$seedId'
      fullPath: '/adplacements/seeds/$seedId'
      preLoaderRoute: typeof AdplacementsSeedsSeedIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/zai/video/$jobId': {
      id: '/lab/zai/video/$jobId'
      path: '/video/$jobId'
      fullPath: '/lab/zai/video/$jobId'
      preLoaderRoute: typeof LabZaiVideoJobIdRouteImport
      parentRoute: typeof LabZaiRoute
    }
    '/dashboard/personas/$personaId/edit': {
      id: '/dashboard/personas/$personaId/edit'
      path: '/$personaId/edit'
      fullPath: '/dashboard/personas/$personaId/edit'
      preLoaderRoute: typeof DashboardPersonasPersonaIdEditRouteImport
      parentRoute: typeof DashboardPersonasRoute
    }
  }
}

interface CanvasRouteChildren {
  CanvasCanvasIdRoute: typeof CanvasCanvasIdRoute
}

const CanvasRouteChildren: CanvasRouteChildren = {
  CanvasCanvasIdRoute: CanvasCanvasIdRoute,
}

const CanvasRouteWithChildren =
  CanvasRoute._addFileChildren(CanvasRouteChildren)

interface DashboardPersonasRouteChildren {
  DashboardPersonasPersonaIdEditRoute: typeof DashboardPersonasPersonaIdEditRoute
}

const DashboardPersonasRouteChildren: DashboardPersonasRouteChildren = {
  DashboardPersonasPersonaIdEditRoute: DashboardPersonasPersonaIdEditRoute,
}

const DashboardPersonasRouteWithChildren =
  DashboardPersonasRoute._addFileChildren(DashboardPersonasRouteChildren)

interface DashboardRouteChildren {
  DashboardPersonasRoute: typeof DashboardPersonasRouteWithChildren
  DashboardRevenueRoute: typeof DashboardRevenueRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardPersonasRoute: DashboardPersonasRouteWithChildren,
  DashboardRevenueRoute: DashboardRevenueRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface NotebookRouteChildren {
  NotebookIdRoute: typeof NotebookIdRoute
}

const NotebookRouteChildren: NotebookRouteChildren = {
  NotebookIdRoute: NotebookIdRoute,
}

const NotebookRouteWithChildren = NotebookRoute._addFileChildren(
  NotebookRouteChildren,
)

interface StudioRouteChildren {
  StudioEditAssetIdRoute: typeof StudioEditAssetIdRoute
}

const StudioRouteChildren: StudioRouteChildren = {
  StudioEditAssetIdRoute: StudioEditAssetIdRoute,
}

const StudioRouteWithChildren =
  StudioRoute._addFileChildren(StudioRouteChildren)

interface LabZaiRouteChildren {
  LabZaiDiagnosticRoute: typeof LabZaiDiagnosticRoute
  LabZaiVideoJobIdRoute: typeof LabZaiVideoJobIdRoute
}

const LabZaiRouteChildren: LabZaiRouteChildren = {
  LabZaiDiagnosticRoute: LabZaiDiagnosticRoute,
  LabZaiVideoJobIdRoute: LabZaiVideoJobIdRoute,
}

const LabZaiRouteWithChildren =
  LabZaiRoute._addFileChildren(LabZaiRouteChildren)

interface MarketplaceLikenessRouteChildren {
  MarketplaceLikenessListingIdRoute: typeof MarketplaceLikenessListingIdRoute
}

const MarketplaceLikenessRouteChildren: MarketplaceLikenessRouteChildren = {
  MarketplaceLikenessListingIdRoute: MarketplaceLikenessListingIdRoute,
}

const MarketplaceLikenessRouteWithChildren =
  MarketplaceLikenessRoute._addFileChildren(MarketplaceLikenessRouteChildren)

interface UniverseIdRouteChildren {
  UniverseIdDeployTokenRoute: typeof UniverseIdDeployTokenRoute
  UniverseIdGalleryRoute: typeof UniverseIdGalleryRoute
  UniverseIdGenConfigRoute: typeof UniverseIdGenConfigRoute
  UniverseIdLineageRoute: typeof UniverseIdLineageRoute
  UniverseIdProfileRoute: typeof UniverseIdProfileRoute
  UniverseIdStyleRoute: typeof UniverseIdStyleRoute
  UniverseIdWatchRoute: typeof UniverseIdWatchRoute
}

const UniverseIdRouteChildren: UniverseIdRouteChildren = {
  UniverseIdDeployTokenRoute: UniverseIdDeployTokenRoute,
  UniverseIdGalleryRoute: UniverseIdGalleryRoute,
  UniverseIdGenConfigRoute: UniverseIdGenConfigRoute,
  UniverseIdLineageRoute: UniverseIdLineageRoute,
  UniverseIdProfileRoute: UniverseIdProfileRoute,
  UniverseIdStyleRoute: UniverseIdStyleRoute,
  UniverseIdWatchRoute: UniverseIdWatchRoute,
}

const UniverseIdRouteWithChildren = UniverseIdRoute._addFileChildren(
  UniverseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AdReferenceRoute: AdReferenceRoute,
  BridgeRoute: BridgeRoute,
  CanvasRoute: CanvasRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  CinematicUniverseCreateRoute: CinematicUniverseCreateRoute,
  ComingSoonRoute: ComingSoonRoute,
  CounterNoticeRoute: CounterNoticeRoute,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRouteWithChildren,
  DiscoverRoute: DiscoverRoute,
  DmcaRoute: DmcaRoute,
  DocsRoute: DocsRoute,
  EditorRoute: EditorRoute,
  FaucetRoute: FaucetRoute,
  GalleryRoute: GalleryRoute,
  LeaderboardRoute: LeaderboardRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  MarketingRoute: MarketingRoute,
  MyWorksRoute: MyWorksRoute,
  NotebookRoute: NotebookRouteWithChildren,
  NotificationsRoute: NotificationsRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RelightRoute: RelightRoute,
  ResidencyRoute: ResidencyRoute,
  SandboxRoute: SandboxRoute,
  SearchRoute: SearchRoute,
  SeriesRoute: SeriesRoute,
  SolanaRoute: SolanaRoute,
  StatusRoute: StatusRoute,
  StudioRoute: StudioRouteWithChildren,
  StudioControlledRoute: StudioControlledRoute,
  SubscriptionsRoute: SubscriptionsRoute,
  TermsRoute: TermsRoute,
  TestnetRoute: TestnetRoute,
  UploadRoute: UploadRoute,
  VideosRoute: VideosRoute,
  ViralityRoute: ViralityRoute,
  RoyaltiesRoute: RoyaltiesRoute,
  AdminByokCodesRoute: AdminByokCodesRoute,
  AdminCostRoute: AdminCostRoute,
  AdminMcpUsageRoute: AdminMcpUsageRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdminOpsRoute: AdminOpsRoute,
  AdminMainnetRoute: AdminMainnetRoute,
  AdminResidencyRoute: AdminResidencyRoute,
  AdminUniversesRoute: AdminUniversesRoute,
  AdplacementsSlotIdRoute: AdplacementsSlotIdRoute,
  AdplacementsNewRoute: AdplacementsNewRoute,
  AgentsUidRoute: AgentsUidRoute,
  AgentsDashboardRoute: AgentsDashboardRoute,
  AgentsRegisterRoute: AgentsRegisterRoute,
  AnalyticsUniverseIdRoute: AnalyticsUniverseIdRoute,
  AnatomyUniverseRoute: AnatomyUniverseRoute,
  BountiesBountyIdRoute: BountiesBountyIdRoute,
  BountiesMineRoute: BountiesMineRoute,
  BrandDashboardRoute: BrandDashboardRoute,
  CanonUniverseIdRoute: CanonUniverseIdRoute,
  CharactersUniverseIdRoute: CharactersUniverseIdRoute,
  CreateKindRoute: CreateKindRoute,
  CreateLikenessRoute: CreateLikenessRoute,
  CreatePersonaRoute: CreatePersonaRoute,
  EditInpaintRoute: EditInpaintRoute,
  EditOutpaintRoute: EditOutpaintRoute,
  EpisodeIdRoute: EpisodeIdRoute,
  ExtractJobIdRoute: ExtractJobIdRoute,
  GovernanceUniverseIdRoute: GovernanceUniverseIdRoute,
  LabGptImageRoute: LabGptImageRoute,
  LabVoiceStudioRoute: LabVoiceStudioRoute,
  LabZaiRoute: LabZaiRouteWithChildren,
  LineageAssetIdRoute: LineageAssetIdRoute,
  MarketplaceLikenessRoute: MarketplaceLikenessRouteWithChildren,
  OauthSiweRoute: OauthSiweRoute,
  OrderIdRoute: OrderIdRoute,
  PlayUniverseIdRoute: PlayUniverseIdRoute,
  ProductIdRoute: ProductIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ProfileEditRoute: ProfileEditRoute,
  SellEarningsRoute: SellEarningsRoute,
  SellNewRoute: SellNewRoute,
  SettingsApiKeysRoute: SettingsApiKeysRoute,
  SettingsUsageRoute: SettingsUsageRoute,
  SettingsWalletsRoute: SettingsWalletsRoute,
  ShopUniverseIdRoute: ShopUniverseIdRoute,
  TokensAddressRoute: TokensAddressRoute,
  TokensLaunchRoute: TokensLaunchRoute,
  TokensPortfolioRoute: TokensPortfolioRoute,
  TokensSwapRoute: TokensSwapRoute,
  TreasuryUniverseIdRoute: TreasuryUniverseIdRoute,
  UniverseIdRoute: UniverseIdRouteWithChildren,
  WikiKindRoute: WikiKindRoute,
  AdplacementsIndexRoute: AdplacementsIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BountiesIndexRoute: BountiesIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
  SellIndexRoute: SellIndexRoute,
  TokensIndexRoute: TokensIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
  AdplacementsSeedsSeedIdRoute: AdplacementsSeedsSeedIdRoute,
  AdplacementsSeedsNewRoute: AdplacementsSeedsNewRoute,
  EventUniverseEventRoute: EventUniverseEventRoute,
  MarketplacePersonaPersonaIdRoute: MarketplacePersonaPersonaIdRoute,
  TokensCreatorAddressRoute: TokensCreatorAddressRoute,
  UniverseAddressPhysicsRoute: UniverseAddressPhysicsRoute,
  UniverseAddressPollsRoute: UniverseAddressPollsRoute,
  WikiCharacterIdRoute: WikiCharacterIdRoute,
  WikiEntityIdRoute: WikiEntityIdRoute,
  AdplacementsSeedsIndexRoute: AdplacementsSeedsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
