/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MyWorksRouteImport } from './routes/my-works'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DmcaRouteImport } from './routes/dmca'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreditsRouteImport } from './routes/credits'
import { Route as ComingSoonRouteImport } from './routes/coming-soon'
import { Route as CinematicUniverseCreateRouteImport } from './routes/cinematicUniverseCreate'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as TokensIndexRouteImport } from './routes/tokens/index'
import { Route as SellIndexRouteImport } from './routes/sell/index'
import { Route as LicensingIndexRouteImport } from './routes/licensing/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as CollabsIndexRouteImport } from './routes/collabs/index'
import { Route as BountiesIndexRouteImport } from './routes/bounties/index'
import { Route as AgentsIndexRouteImport } from './routes/agents/index'
import { Route as AdsIndexRouteImport } from './routes/ads/index'
import { Route as UniverseIdRouteImport } from './routes/universe/$id'
import { Route as TreasuryUniverseIdRouteImport } from './routes/treasury/$universeId'
import { Route as TokensPortfolioRouteImport } from './routes/tokens/portfolio'
import { Route as TokensAddressRouteImport } from './routes/tokens/$address'
import { Route as ShopUniverseIdRouteImport } from './routes/shop/$universeId'
import { Route as SellNewRouteImport } from './routes/sell/new'
import { Route as SellEarningsRouteImport } from './routes/sell/earnings'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as ProductIdRouteImport } from './routes/product/$id'
import { Route as PlayUniverseIdRouteImport } from './routes/play/$universeId'
import { Route as OrderIdRouteImport } from './routes/order/$id'
import { Route as LicensingNewRouteImport } from './routes/licensing/new'
import { Route as GovernanceUniverseIdRouteImport } from './routes/governance/$universeId'
import { Route as CreateKindRouteImport } from './routes/create/$kind'
import { Route as CollabsNewRouteImport } from './routes/collabs/new'
import { Route as CanonUniverseIdRouteImport } from './routes/canon/$universeId'
import { Route as BountiesMineRouteImport } from './routes/bounties/mine'
import { Route as BountiesBountyIdRouteImport } from './routes/bounties/$bountyId'
import { Route as AgentsRegisterRouteImport } from './routes/agents/register'
import { Route as AgentsDashboardRouteImport } from './routes/agents/dashboard'
import { Route as AgentsUidRouteImport } from './routes/agents/$uid'
import { Route as AdsNewRouteImport } from './routes/ads/new'
import { Route as AdsSlotIdRouteImport } from './routes/ads/$slotId'
import { Route as AdminModerationRouteImport } from './routes/admin/moderation'
import { Route as WikiEntityIdRouteImport } from './routes/wiki/entity/$id'
import { Route as WikiCharacterIdRouteImport } from './routes/wiki/character/$id'
import { Route as UniverseIdGenConfigRouteImport } from './routes/universe/$id/gen-config'
import { Route as UniverseIdGalleryRouteImport } from './routes/universe/$id/gallery'
import { Route as UniverseIdDeployTokenRouteImport } from './routes/universe/$id.deploy-token'
import { Route as TokensCreatorAddressRouteImport } from './routes/tokens/creator.$address'
import { Route as EventUniverseEventRouteImport } from './routes/event.$universe.$event'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorksRoute = MyWorksRouteImport.update({
  id: '/my-works',
  path: '/my-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DmcaRoute = DmcaRouteImport.update({
  id: '/dmca',
  path: '/dmca',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreditsRoute = CreditsRouteImport.update({
  id: '/credits',
  path: '/credits',
  getParentRoute: () => rootRouteImport,
} as any)
const ComingSoonRoute = ComingSoonRouteImport.update({
  id: '/coming-soon',
  path: '/coming-soon',
  getParentRoute: () => rootRouteImport,
} as any)
const CinematicUniverseCreateRoute = CinematicUniverseCreateRouteImport.update({
  id: '/cinematicUniverseCreate',
  path: '/cinematicUniverseCreate',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensIndexRoute = TokensIndexRouteImport.update({
  id: '/tokens/',
  path: '/tokens/',
  getParentRoute: () => rootRouteImport,
} as any)
const SellIndexRoute = SellIndexRouteImport.update({
  id: '/sell/',
  path: '/sell/',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensingIndexRoute = LicensingIndexRouteImport.update({
  id: '/licensing/',
  path: '/licensing/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabsIndexRoute = CollabsIndexRouteImport.update({
  id: '/collabs/',
  path: '/collabs/',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesIndexRoute = BountiesIndexRouteImport.update({
  id: '/bounties/',
  path: '/bounties/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsIndexRoute = AdsIndexRouteImport.update({
  id: '/ads/',
  path: '/ads/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseIdRoute = UniverseIdRouteImport.update({
  id: '/universe/$id',
  path: '/universe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryUniverseIdRoute = TreasuryUniverseIdRouteImport.update({
  id: '/treasury/$universeId',
  path: '/treasury/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensPortfolioRoute = TokensPortfolioRouteImport.update({
  id: '/tokens/portfolio',
  path: '/tokens/portfolio',
  getParentRoute: () => rootRouteImport,
} as any)
const TokensAddressRoute = TokensAddressRouteImport.update({
  id: '/tokens/$address',
  path: '/tokens/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopUniverseIdRoute = ShopUniverseIdRouteImport.update({
  id: '/shop/$universeId',
  path: '/shop/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const SellNewRoute = SellNewRouteImport.update({
  id: '/sell/new',
  path: '/sell/new',
  getParentRoute: () => rootRouteImport,
} as any)
const SellEarningsRoute = SellEarningsRouteImport.update({
  id: '/sell/earnings',
  path: '/sell/earnings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayUniverseIdRoute = PlayUniverseIdRouteImport.update({
  id: '/play/$universeId',
  path: '/play/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LicensingNewRoute = LicensingNewRouteImport.update({
  id: '/licensing/new',
  path: '/licensing/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GovernanceUniverseIdRoute = GovernanceUniverseIdRouteImport.update({
  id: '/governance/$universeId',
  path: '/governance/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateKindRoute = CreateKindRouteImport.update({
  id: '/create/$kind',
  path: '/create/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const CollabsNewRoute = CollabsNewRouteImport.update({
  id: '/collabs/new',
  path: '/collabs/new',
  getParentRoute: () => rootRouteImport,
} as any)
const CanonUniverseIdRoute = CanonUniverseIdRouteImport.update({
  id: '/canon/$universeId',
  path: '/canon/$universeId',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesMineRoute = BountiesMineRouteImport.update({
  id: '/bounties/mine',
  path: '/bounties/mine',
  getParentRoute: () => rootRouteImport,
} as any)
const BountiesBountyIdRoute = BountiesBountyIdRouteImport.update({
  id: '/bounties/$bountyId',
  path: '/bounties/$bountyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsRegisterRoute = AgentsRegisterRouteImport.update({
  id: '/agents/register',
  path: '/agents/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsDashboardRoute = AgentsDashboardRouteImport.update({
  id: '/agents/dashboard',
  path: '/agents/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsUidRoute = AgentsUidRouteImport.update({
  id: '/agents/$uid',
  path: '/agents/$uid',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsNewRoute = AdsNewRouteImport.update({
  id: '/ads/new',
  path: '/ads/new',
  getParentRoute: () => rootRouteImport,
} as any)
const AdsSlotIdRoute = AdsSlotIdRouteImport.update({
  id: '/ads/$slotId',
  path: '/ads/$slotId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminModerationRoute = AdminModerationRouteImport.update({
  id: '/admin/moderation',
  path: '/admin/moderation',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiEntityIdRoute = WikiEntityIdRouteImport.update({
  id: '/wiki/entity/$id',
  path: '/wiki/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiCharacterIdRoute = WikiCharacterIdRouteImport.update({
  id: '/wiki/character/$id',
  path: '/wiki/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseIdGenConfigRoute = UniverseIdGenConfigRouteImport.update({
  id: '/gen-config',
  path: '/gen-config',
  getParentRoute: () => UniverseIdRoute,
} as any)
const UniverseIdGalleryRoute = UniverseIdGalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => UniverseIdRoute,
} as any)
const UniverseIdDeployTokenRoute = UniverseIdDeployTokenRouteImport.update({
  id: '/deploy-token',
  path: '/deploy-token',
  getParentRoute: () => UniverseIdRoute,
} as any)
const TokensCreatorAddressRoute = TokensCreatorAddressRouteImport.update({
  id: '/tokens/creator/$address',
  path: '/tokens/creator/$address',
  getParentRoute: () => rootRouteImport,
} as any)
const EventUniverseEventRoute = EventUniverseEventRouteImport.update({
  id: '/event/$universe/$event',
  path: '/event/$universe/$event',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/checkout': typeof CheckoutRoute
  '/cinematicUniverseCreate': typeof CinematicUniverseCreateRoute
  '/coming-soon': typeof ComingSoonRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/docs': typeof DocsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/my-works': typeof MyWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sandbox': typeof SandboxRoute
  '/staking': typeof StakingRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/ads/$slotId': typeof AdsSlotIdRoute
  '/ads/new': typeof AdsNewRoute
  '/agents/$uid': typeof AgentsUidRoute
  '/agents/dashboard': typeof AgentsDashboardRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/bounties/$bountyId': typeof BountiesBountyIdRoute
  '/bounties/mine': typeof BountiesMineRoute
  '/canon/$universeId': typeof CanonUniverseIdRoute
  '/collabs/new': typeof CollabsNewRoute
  '/create/$kind': typeof CreateKindRoute
  '/governance/$universeId': typeof GovernanceUniverseIdRoute
  '/licensing/new': typeof LicensingNewRoute
  '/order/$id': typeof OrderIdRoute
  '/play/$universeId': typeof PlayUniverseIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/sell/earnings': typeof SellEarningsRoute
  '/sell/new': typeof SellNewRoute
  '/shop/$universeId': typeof ShopUniverseIdRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/tokens/portfolio': typeof TokensPortfolioRoute
  '/treasury/$universeId': typeof TreasuryUniverseIdRoute
  '/universe/$id': typeof UniverseIdRouteWithChildren
  '/ads/': typeof AdsIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/bounties/': typeof BountiesIndexRoute
  '/collabs/': typeof CollabsIndexRoute
  '/create/': typeof CreateIndexRoute
  '/licensing/': typeof LicensingIndexRoute
  '/sell/': typeof SellIndexRoute
  '/tokens/': typeof TokensIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/event/$universe/$event': typeof EventUniverseEventRoute
  '/tokens/creator/$address': typeof TokensCreatorAddressRoute
  '/universe/$id/deploy-token': typeof UniverseIdDeployTokenRoute
  '/universe/$id/gallery': typeof UniverseIdGalleryRoute
  '/universe/$id/gen-config': typeof UniverseIdGenConfigRoute
  '/wiki/character/$id': typeof WikiCharacterIdRoute
  '/wiki/entity/$id': typeof WikiEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/checkout': typeof CheckoutRoute
  '/cinematicUniverseCreate': typeof CinematicUniverseCreateRoute
  '/coming-soon': typeof ComingSoonRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/docs': typeof DocsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/my-works': typeof MyWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sandbox': typeof SandboxRoute
  '/staking': typeof StakingRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/ads/$slotId': typeof AdsSlotIdRoute
  '/ads/new': typeof AdsNewRoute
  '/agents/$uid': typeof AgentsUidRoute
  '/agents/dashboard': typeof AgentsDashboardRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/bounties/$bountyId': typeof BountiesBountyIdRoute
  '/bounties/mine': typeof BountiesMineRoute
  '/canon/$universeId': typeof CanonUniverseIdRoute
  '/collabs/new': typeof CollabsNewRoute
  '/create/$kind': typeof CreateKindRoute
  '/governance/$universeId': typeof GovernanceUniverseIdRoute
  '/licensing/new': typeof LicensingNewRoute
  '/order/$id': typeof OrderIdRoute
  '/play/$universeId': typeof PlayUniverseIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/sell/earnings': typeof SellEarningsRoute
  '/sell/new': typeof SellNewRoute
  '/shop/$universeId': typeof ShopUniverseIdRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/tokens/portfolio': typeof TokensPortfolioRoute
  '/treasury/$universeId': typeof TreasuryUniverseIdRoute
  '/universe/$id': typeof UniverseIdRouteWithChildren
  '/ads': typeof AdsIndexRoute
  '/agents': typeof AgentsIndexRoute
  '/bounties': typeof BountiesIndexRoute
  '/collabs': typeof CollabsIndexRoute
  '/create': typeof CreateIndexRoute
  '/licensing': typeof LicensingIndexRoute
  '/sell': typeof SellIndexRoute
  '/tokens': typeof TokensIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/event/$universe/$event': typeof EventUniverseEventRoute
  '/tokens/creator/$address': typeof TokensCreatorAddressRoute
  '/universe/$id/deploy-token': typeof UniverseIdDeployTokenRoute
  '/universe/$id/gallery': typeof UniverseIdGalleryRoute
  '/universe/$id/gen-config': typeof UniverseIdGenConfigRoute
  '/wiki/character/$id': typeof WikiCharacterIdRoute
  '/wiki/entity/$id': typeof WikiEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/checkout': typeof CheckoutRoute
  '/cinematicUniverseCreate': typeof CinematicUniverseCreateRoute
  '/coming-soon': typeof ComingSoonRoute
  '/credits': typeof CreditsRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/dmca': typeof DmcaRoute
  '/docs': typeof DocsRoute
  '/gallery': typeof GalleryRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/my-works': typeof MyWorksRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/sandbox': typeof SandboxRoute
  '/staking': typeof StakingRoute
  '/terms': typeof TermsRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/admin/moderation': typeof AdminModerationRoute
  '/ads/$slotId': typeof AdsSlotIdRoute
  '/ads/new': typeof AdsNewRoute
  '/agents/$uid': typeof AgentsUidRoute
  '/agents/dashboard': typeof AgentsDashboardRoute
  '/agents/register': typeof AgentsRegisterRoute
  '/bounties/$bountyId': typeof BountiesBountyIdRoute
  '/bounties/mine': typeof BountiesMineRoute
  '/canon/$universeId': typeof CanonUniverseIdRoute
  '/collabs/new': typeof CollabsNewRoute
  '/create/$kind': typeof CreateKindRoute
  '/governance/$universeId': typeof GovernanceUniverseIdRoute
  '/licensing/new': typeof LicensingNewRoute
  '/order/$id': typeof OrderIdRoute
  '/play/$universeId': typeof PlayUniverseIdRoute
  '/product/$id': typeof ProductIdRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/sell/earnings': typeof SellEarningsRoute
  '/sell/new': typeof SellNewRoute
  '/shop/$universeId': typeof ShopUniverseIdRoute
  '/tokens/$address': typeof TokensAddressRoute
  '/tokens/portfolio': typeof TokensPortfolioRoute
  '/treasury/$universeId': typeof TreasuryUniverseIdRoute
  '/universe/$id': typeof UniverseIdRouteWithChildren
  '/ads/': typeof AdsIndexRoute
  '/agents/': typeof AgentsIndexRoute
  '/bounties/': typeof BountiesIndexRoute
  '/collabs/': typeof CollabsIndexRoute
  '/create/': typeof CreateIndexRoute
  '/licensing/': typeof LicensingIndexRoute
  '/sell/': typeof SellIndexRoute
  '/tokens/': typeof TokensIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/event/$universe/$event': typeof EventUniverseEventRoute
  '/tokens/creator/$address': typeof TokensCreatorAddressRoute
  '/universe/$id/deploy-token': typeof UniverseIdDeployTokenRoute
  '/universe/$id/gallery': typeof UniverseIdGalleryRoute
  '/universe/$id/gen-config': typeof UniverseIdGenConfigRoute
  '/wiki/character/$id': typeof WikiCharacterIdRoute
  '/wiki/entity/$id': typeof WikiEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/checkout'
    | '/cinematicUniverseCreate'
    | '/coming-soon'
    | '/credits'
    | '/dashboard'
    | '/discover'
    | '/dmca'
    | '/docs'
    | '/gallery'
    | '/login'
    | '/market'
    | '/my-works'
    | '/pricing'
    | '/privacy'
    | '/sandbox'
    | '/staking'
    | '/terms'
    | '/upload'
    | '/videos'
    | '/admin/moderation'
    | '/ads/$slotId'
    | '/ads/new'
    | '/agents/$uid'
    | '/agents/dashboard'
    | '/agents/register'
    | '/bounties/$bountyId'
    | '/bounties/mine'
    | '/canon/$universeId'
    | '/collabs/new'
    | '/create/$kind'
    | '/governance/$universeId'
    | '/licensing/new'
    | '/order/$id'
    | '/play/$universeId'
    | '/product/$id'
    | '/profile/$username'
    | '/profile/edit'
    | '/sell/earnings'
    | '/sell/new'
    | '/shop/$universeId'
    | '/tokens/$address'
    | '/tokens/portfolio'
    | '/treasury/$universeId'
    | '/universe/$id'
    | '/ads/'
    | '/agents/'
    | '/bounties/'
    | '/collabs/'
    | '/create/'
    | '/licensing/'
    | '/sell/'
    | '/tokens/'
    | '/wiki/'
    | '/event/$universe/$event'
    | '/tokens/creator/$address'
    | '/universe/$id/deploy-token'
    | '/universe/$id/gallery'
    | '/universe/$id/gen-config'
    | '/wiki/character/$id'
    | '/wiki/entity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/checkout'
    | '/cinematicUniverseCreate'
    | '/coming-soon'
    | '/credits'
    | '/dashboard'
    | '/discover'
    | '/dmca'
    | '/docs'
    | '/gallery'
    | '/login'
    | '/market'
    | '/my-works'
    | '/pricing'
    | '/privacy'
    | '/sandbox'
    | '/staking'
    | '/terms'
    | '/upload'
    | '/videos'
    | '/admin/moderation'
    | '/ads/$slotId'
    | '/ads/new'
    | '/agents/$uid'
    | '/agents/dashboard'
    | '/agents/register'
    | '/bounties/$bountyId'
    | '/bounties/mine'
    | '/canon/$universeId'
    | '/collabs/new'
    | '/create/$kind'
    | '/governance/$universeId'
    | '/licensing/new'
    | '/order/$id'
    | '/play/$universeId'
    | '/product/$id'
    | '/profile/$username'
    | '/profile/edit'
    | '/sell/earnings'
    | '/sell/new'
    | '/shop/$universeId'
    | '/tokens/$address'
    | '/tokens/portfolio'
    | '/treasury/$universeId'
    | '/universe/$id'
    | '/ads'
    | '/agents'
    | '/bounties'
    | '/collabs'
    | '/create'
    | '/licensing'
    | '/sell'
    | '/tokens'
    | '/wiki'
    | '/event/$universe/$event'
    | '/tokens/creator/$address'
    | '/universe/$id/deploy-token'
    | '/universe/$id/gallery'
    | '/universe/$id/gen-config'
    | '/wiki/character/$id'
    | '/wiki/entity/$id'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/checkout'
    | '/cinematicUniverseCreate'
    | '/coming-soon'
    | '/credits'
    | '/dashboard'
    | '/discover'
    | '/dmca'
    | '/docs'
    | '/gallery'
    | '/login'
    | '/market'
    | '/my-works'
    | '/pricing'
    | '/privacy'
    | '/sandbox'
    | '/staking'
    | '/terms'
    | '/upload'
    | '/videos'
    | '/admin/moderation'
    | '/ads/$slotId'
    | '/ads/new'
    | '/agents/$uid'
    | '/agents/dashboard'
    | '/agents/register'
    | '/bounties/$bountyId'
    | '/bounties/mine'
    | '/canon/$universeId'
    | '/collabs/new'
    | '/create/$kind'
    | '/governance/$universeId'
    | '/licensing/new'
    | '/order/$id'
    | '/play/$universeId'
    | '/product/$id'
    | '/profile/$username'
    | '/profile/edit'
    | '/sell/earnings'
    | '/sell/new'
    | '/shop/$universeId'
    | '/tokens/$address'
    | '/tokens/portfolio'
    | '/treasury/$universeId'
    | '/universe/$id'
    | '/ads/'
    | '/agents/'
    | '/bounties/'
    | '/collabs/'
    | '/create/'
    | '/licensing/'
    | '/sell/'
    | '/tokens/'
    | '/wiki/'
    | '/event/$universe/$event'
    | '/tokens/creator/$address'
    | '/universe/$id/deploy-token'
    | '/universe/$id/gallery'
    | '/universe/$id/gen-config'
    | '/wiki/character/$id'
    | '/wiki/entity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  CheckoutRoute: typeof CheckoutRoute
  CinematicUniverseCreateRoute: typeof CinematicUniverseCreateRoute
  ComingSoonRoute: typeof ComingSoonRoute
  CreditsRoute: typeof CreditsRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  DmcaRoute: typeof DmcaRoute
  DocsRoute: typeof DocsRoute
  GalleryRoute: typeof GalleryRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  MyWorksRoute: typeof MyWorksRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SandboxRoute: typeof SandboxRoute
  StakingRoute: typeof StakingRoute
  TermsRoute: typeof TermsRoute
  UploadRoute: typeof UploadRoute
  VideosRoute: typeof VideosRoute
  AdminModerationRoute: typeof AdminModerationRoute
  AdsSlotIdRoute: typeof AdsSlotIdRoute
  AdsNewRoute: typeof AdsNewRoute
  AgentsUidRoute: typeof AgentsUidRoute
  AgentsDashboardRoute: typeof AgentsDashboardRoute
  AgentsRegisterRoute: typeof AgentsRegisterRoute
  BountiesBountyIdRoute: typeof BountiesBountyIdRoute
  BountiesMineRoute: typeof BountiesMineRoute
  CanonUniverseIdRoute: typeof CanonUniverseIdRoute
  CollabsNewRoute: typeof CollabsNewRoute
  CreateKindRoute: typeof CreateKindRoute
  GovernanceUniverseIdRoute: typeof GovernanceUniverseIdRoute
  LicensingNewRoute: typeof LicensingNewRoute
  OrderIdRoute: typeof OrderIdRoute
  PlayUniverseIdRoute: typeof PlayUniverseIdRoute
  ProductIdRoute: typeof ProductIdRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ProfileEditRoute: typeof ProfileEditRoute
  SellEarningsRoute: typeof SellEarningsRoute
  SellNewRoute: typeof SellNewRoute
  ShopUniverseIdRoute: typeof ShopUniverseIdRoute
  TokensAddressRoute: typeof TokensAddressRoute
  TokensPortfolioRoute: typeof TokensPortfolioRoute
  TreasuryUniverseIdRoute: typeof TreasuryUniverseIdRoute
  UniverseIdRoute: typeof UniverseIdRouteWithChildren
  AdsIndexRoute: typeof AdsIndexRoute
  AgentsIndexRoute: typeof AgentsIndexRoute
  BountiesIndexRoute: typeof BountiesIndexRoute
  CollabsIndexRoute: typeof CollabsIndexRoute
  CreateIndexRoute: typeof CreateIndexRoute
  LicensingIndexRoute: typeof LicensingIndexRoute
  SellIndexRoute: typeof SellIndexRoute
  TokensIndexRoute: typeof TokensIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
  EventUniverseEventRoute: typeof EventUniverseEventRoute
  TokensCreatorAddressRoute: typeof TokensCreatorAddressRoute
  WikiCharacterIdRoute: typeof WikiCharacterIdRoute
  WikiEntityIdRoute: typeof WikiEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-works': {
      id: '/my-works'
      path: '/my-works'
      fullPath: '/my-works'
      preLoaderRoute: typeof MyWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dmca': {
      id: '/dmca'
      path: '/dmca'
      fullPath: '/dmca'
      preLoaderRoute: typeof DmcaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/credits': {
      id: '/credits'
      path: '/credits'
      fullPath: '/credits'
      preLoaderRoute: typeof CreditsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coming-soon': {
      id: '/coming-soon'
      path: '/coming-soon'
      fullPath: '/coming-soon'
      preLoaderRoute: typeof ComingSoonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinematicUniverseCreate': {
      id: '/cinematicUniverseCreate'
      path: '/cinematicUniverseCreate'
      fullPath: '/cinematicUniverseCreate'
      preLoaderRoute: typeof CinematicUniverseCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/': {
      id: '/tokens/'
      path: '/tokens'
      fullPath: '/tokens/'
      preLoaderRoute: typeof TokensIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/': {
      id: '/sell/'
      path: '/sell'
      fullPath: '/sell/'
      preLoaderRoute: typeof SellIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licensing/': {
      id: '/licensing/'
      path: '/licensing'
      fullPath: '/licensing/'
      preLoaderRoute: typeof LicensingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collabs/': {
      id: '/collabs/'
      path: '/collabs'
      fullPath: '/collabs/'
      preLoaderRoute: typeof CollabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/': {
      id: '/bounties/'
      path: '/bounties'
      fullPath: '/bounties/'
      preLoaderRoute: typeof BountiesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/': {
      id: '/ads/'
      path: '/ads'
      fullPath: '/ads/'
      preLoaderRoute: typeof AdsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe/$id': {
      id: '/universe/$id'
      path: '/universe/$id'
      fullPath: '/universe/$id'
      preLoaderRoute: typeof UniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury/$universeId': {
      id: '/treasury/$universeId'
      path: '/treasury/$universeId'
      fullPath: '/treasury/$universeId'
      preLoaderRoute: typeof TreasuryUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/portfolio': {
      id: '/tokens/portfolio'
      path: '/tokens/portfolio'
      fullPath: '/tokens/portfolio'
      preLoaderRoute: typeof TokensPortfolioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tokens/$address': {
      id: '/tokens/$address'
      path: '/tokens/$address'
      fullPath: '/tokens/$address'
      preLoaderRoute: typeof TokensAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$universeId': {
      id: '/shop/$universeId'
      path: '/shop/$universeId'
      fullPath: '/shop/$universeId'
      preLoaderRoute: typeof ShopUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/new': {
      id: '/sell/new'
      path: '/sell/new'
      fullPath: '/sell/new'
      preLoaderRoute: typeof SellNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell/earnings': {
      id: '/sell/earnings'
      path: '/sell/earnings'
      fullPath: '/sell/earnings'
      preLoaderRoute: typeof SellEarningsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/$universeId': {
      id: '/play/$universeId'
      path: '/play/$universeId'
      fullPath: '/play/$universeId'
      preLoaderRoute: typeof PlayUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licensing/new': {
      id: '/licensing/new'
      path: '/licensing/new'
      fullPath: '/licensing/new'
      preLoaderRoute: typeof LicensingNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/governance/$universeId': {
      id: '/governance/$universeId'
      path: '/governance/$universeId'
      fullPath: '/governance/$universeId'
      preLoaderRoute: typeof GovernanceUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$kind': {
      id: '/create/$kind'
      path: '/create/$kind'
      fullPath: '/create/$kind'
      preLoaderRoute: typeof CreateKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collabs/new': {
      id: '/collabs/new'
      path: '/collabs/new'
      fullPath: '/collabs/new'
      preLoaderRoute: typeof CollabsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canon/$universeId': {
      id: '/canon/$universeId'
      path: '/canon/$universeId'
      fullPath: '/canon/$universeId'
      preLoaderRoute: typeof CanonUniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/mine': {
      id: '/bounties/mine'
      path: '/bounties/mine'
      fullPath: '/bounties/mine'
      preLoaderRoute: typeof BountiesMineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bounties/$bountyId': {
      id: '/bounties/$bountyId'
      path: '/bounties/$bountyId'
      fullPath: '/bounties/$bountyId'
      preLoaderRoute: typeof BountiesBountyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/register': {
      id: '/agents/register'
      path: '/agents/register'
      fullPath: '/agents/register'
      preLoaderRoute: typeof AgentsRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/dashboard': {
      id: '/agents/dashboard'
      path: '/agents/dashboard'
      fullPath: '/agents/dashboard'
      preLoaderRoute: typeof AgentsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/$uid': {
      id: '/agents/$uid'
      path: '/agents/$uid'
      fullPath: '/agents/$uid'
      preLoaderRoute: typeof AgentsUidRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/new': {
      id: '/ads/new'
      path: '/ads/new'
      fullPath: '/ads/new'
      preLoaderRoute: typeof AdsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ads/$slotId': {
      id: '/ads/$slotId'
      path: '/ads/$slotId'
      fullPath: '/ads/$slotId'
      preLoaderRoute: typeof AdsSlotIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/moderation': {
      id: '/admin/moderation'
      path: '/admin/moderation'
      fullPath: '/admin/moderation'
      preLoaderRoute: typeof AdminModerationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/entity/$id': {
      id: '/wiki/entity/$id'
      path: '/wiki/entity/$id'
      fullPath: '/wiki/entity/$id'
      preLoaderRoute: typeof WikiEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/character/$id': {
      id: '/wiki/character/$id'
      path: '/wiki/character/$id'
      fullPath: '/wiki/character/$id'
      preLoaderRoute: typeof WikiCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe/$id/gen-config': {
      id: '/universe/$id/gen-config'
      path: '/gen-config'
      fullPath: '/universe/$id/gen-config'
      preLoaderRoute: typeof UniverseIdGenConfigRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/universe/$id/gallery': {
      id: '/universe/$id/gallery'
      path: '/gallery'
      fullPath: '/universe/$id/gallery'
      preLoaderRoute: typeof UniverseIdGalleryRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/universe/$id/deploy-token': {
      id: '/universe/$id/deploy-token'
      path: '/deploy-token'
      fullPath: '/universe/$id/deploy-token'
      preLoaderRoute: typeof UniverseIdDeployTokenRouteImport
      parentRoute: typeof UniverseIdRoute
    }
    '/tokens/creator/$address': {
      id: '/tokens/creator/$address'
      path: '/tokens/creator/$address'
      fullPath: '/tokens/creator/$address'
      preLoaderRoute: typeof TokensCreatorAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$universe/$event': {
      id: '/event/$universe/$event'
      path: '/event/$universe/$event'
      fullPath: '/event/$universe/$event'
      preLoaderRoute: typeof EventUniverseEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface UniverseIdRouteChildren {
  UniverseIdDeployTokenRoute: typeof UniverseIdDeployTokenRoute
  UniverseIdGalleryRoute: typeof UniverseIdGalleryRoute
  UniverseIdGenConfigRoute: typeof UniverseIdGenConfigRoute
}

const UniverseIdRouteChildren: UniverseIdRouteChildren = {
  UniverseIdDeployTokenRoute: UniverseIdDeployTokenRoute,
  UniverseIdGalleryRoute: UniverseIdGalleryRoute,
  UniverseIdGenConfigRoute: UniverseIdGenConfigRoute,
}

const UniverseIdRouteWithChildren = UniverseIdRoute._addFileChildren(
  UniverseIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  CheckoutRoute: CheckoutRoute,
  CinematicUniverseCreateRoute: CinematicUniverseCreateRoute,
  ComingSoonRoute: ComingSoonRoute,
  CreditsRoute: CreditsRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  DmcaRoute: DmcaRoute,
  DocsRoute: DocsRoute,
  GalleryRoute: GalleryRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  MyWorksRoute: MyWorksRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SandboxRoute: SandboxRoute,
  StakingRoute: StakingRoute,
  TermsRoute: TermsRoute,
  UploadRoute: UploadRoute,
  VideosRoute: VideosRoute,
  AdminModerationRoute: AdminModerationRoute,
  AdsSlotIdRoute: AdsSlotIdRoute,
  AdsNewRoute: AdsNewRoute,
  AgentsUidRoute: AgentsUidRoute,
  AgentsDashboardRoute: AgentsDashboardRoute,
  AgentsRegisterRoute: AgentsRegisterRoute,
  BountiesBountyIdRoute: BountiesBountyIdRoute,
  BountiesMineRoute: BountiesMineRoute,
  CanonUniverseIdRoute: CanonUniverseIdRoute,
  CollabsNewRoute: CollabsNewRoute,
  CreateKindRoute: CreateKindRoute,
  GovernanceUniverseIdRoute: GovernanceUniverseIdRoute,
  LicensingNewRoute: LicensingNewRoute,
  OrderIdRoute: OrderIdRoute,
  PlayUniverseIdRoute: PlayUniverseIdRoute,
  ProductIdRoute: ProductIdRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ProfileEditRoute: ProfileEditRoute,
  SellEarningsRoute: SellEarningsRoute,
  SellNewRoute: SellNewRoute,
  ShopUniverseIdRoute: ShopUniverseIdRoute,
  TokensAddressRoute: TokensAddressRoute,
  TokensPortfolioRoute: TokensPortfolioRoute,
  TreasuryUniverseIdRoute: TreasuryUniverseIdRoute,
  UniverseIdRoute: UniverseIdRouteWithChildren,
  AdsIndexRoute: AdsIndexRoute,
  AgentsIndexRoute: AgentsIndexRoute,
  BountiesIndexRoute: BountiesIndexRoute,
  CollabsIndexRoute: CollabsIndexRoute,
  CreateIndexRoute: CreateIndexRoute,
  LicensingIndexRoute: LicensingIndexRoute,
  SellIndexRoute: SellIndexRoute,
  TokensIndexRoute: TokensIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
  EventUniverseEventRoute: EventUniverseEventRoute,
  TokensCreatorAddressRoute: TokensCreatorAddressRoute,
  WikiCharacterIdRoute: WikiCharacterIdRoute,
  WikiEntityIdRoute: WikiEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
