/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VideosRouteImport } from './routes/videos'
import { Route as UploadRouteImport } from './routes/upload'
import { Route as SandboxRouteImport } from './routes/sandbox'
import { Route as MyWorksRouteImport } from './routes/my-works'
import { Route as MarketRouteImport } from './routes/market'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CinematicUniverseCreateRouteImport } from './routes/cinematicUniverseCreate'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as CreateIndexRouteImport } from './routes/create/index'
import { Route as UniverseIdRouteImport } from './routes/universe/$id'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as ProfileUsernameRouteImport } from './routes/profile/$username'
import { Route as CreateKindRouteImport } from './routes/create/$kind'
import { Route as WikiEntityIdRouteImport } from './routes/wiki/entity/$id'
import { Route as WikiCharacterIdRouteImport } from './routes/wiki/character/$id'
import { Route as EventUniverseEventRouteImport } from './routes/event.$universe.$event'

const VideosRoute = VideosRouteImport.update({
  id: '/videos',
  path: '/videos',
  getParentRoute: () => rootRouteImport,
} as any)
const UploadRoute = UploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const SandboxRoute = SandboxRouteImport.update({
  id: '/sandbox',
  path: '/sandbox',
  getParentRoute: () => rootRouteImport,
} as any)
const MyWorksRoute = MyWorksRouteImport.update({
  id: '/my-works',
  path: '/my-works',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketRoute = MarketRouteImport.update({
  id: '/market',
  path: '/market',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CinematicUniverseCreateRoute = CinematicUniverseCreateRouteImport.update({
  id: '/cinematicUniverseCreate',
  path: '/cinematicUniverseCreate',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/wiki/',
  path: '/wiki/',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateIndexRoute = CreateIndexRouteImport.update({
  id: '/create/',
  path: '/create/',
  getParentRoute: () => rootRouteImport,
} as any)
const UniverseIdRoute = UniverseIdRouteImport.update({
  id: '/universe/$id',
  path: '/universe/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileUsernameRoute = ProfileUsernameRouteImport.update({
  id: '/profile/$username',
  path: '/profile/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateKindRoute = CreateKindRouteImport.update({
  id: '/create/$kind',
  path: '/create/$kind',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiEntityIdRoute = WikiEntityIdRouteImport.update({
  id: '/wiki/entity/$id',
  path: '/wiki/entity/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiCharacterIdRoute = WikiCharacterIdRouteImport.update({
  id: '/wiki/character/$id',
  path: '/wiki/character/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const EventUniverseEventRoute = EventUniverseEventRouteImport.update({
  id: '/event/$universe/$event',
  path: '/event/$universe/$event',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cinematicUniverseCreate': typeof CinematicUniverseCreateRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/my-works': typeof MyWorksRoute
  '/sandbox': typeof SandboxRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/create/$kind': typeof CreateKindRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/universe/$id': typeof UniverseIdRoute
  '/create/': typeof CreateIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/event/$universe/$event': typeof EventUniverseEventRoute
  '/wiki/character/$id': typeof WikiCharacterIdRoute
  '/wiki/entity/$id': typeof WikiEntityIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cinematicUniverseCreate': typeof CinematicUniverseCreateRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/my-works': typeof MyWorksRoute
  '/sandbox': typeof SandboxRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/create/$kind': typeof CreateKindRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/universe/$id': typeof UniverseIdRoute
  '/create': typeof CreateIndexRoute
  '/wiki': typeof WikiIndexRoute
  '/event/$universe/$event': typeof EventUniverseEventRoute
  '/wiki/character/$id': typeof WikiCharacterIdRoute
  '/wiki/entity/$id': typeof WikiEntityIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cinematicUniverseCreate': typeof CinematicUniverseCreateRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/docs': typeof DocsRoute
  '/login': typeof LoginRoute
  '/market': typeof MarketRoute
  '/my-works': typeof MyWorksRoute
  '/sandbox': typeof SandboxRoute
  '/upload': typeof UploadRoute
  '/videos': typeof VideosRoute
  '/create/$kind': typeof CreateKindRoute
  '/profile/$username': typeof ProfileUsernameRoute
  '/profile/edit': typeof ProfileEditRoute
  '/universe/$id': typeof UniverseIdRoute
  '/create/': typeof CreateIndexRoute
  '/wiki/': typeof WikiIndexRoute
  '/event/$universe/$event': typeof EventUniverseEventRoute
  '/wiki/character/$id': typeof WikiCharacterIdRoute
  '/wiki/entity/$id': typeof WikiEntityIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cinematicUniverseCreate'
    | '/dashboard'
    | '/discover'
    | '/docs'
    | '/login'
    | '/market'
    | '/my-works'
    | '/sandbox'
    | '/upload'
    | '/videos'
    | '/create/$kind'
    | '/profile/$username'
    | '/profile/edit'
    | '/universe/$id'
    | '/create/'
    | '/wiki/'
    | '/event/$universe/$event'
    | '/wiki/character/$id'
    | '/wiki/entity/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cinematicUniverseCreate'
    | '/dashboard'
    | '/discover'
    | '/docs'
    | '/login'
    | '/market'
    | '/my-works'
    | '/sandbox'
    | '/upload'
    | '/videos'
    | '/create/$kind'
    | '/profile/$username'
    | '/profile/edit'
    | '/universe/$id'
    | '/create'
    | '/wiki'
    | '/event/$universe/$event'
    | '/wiki/character/$id'
    | '/wiki/entity/$id'
  id:
    | '__root__'
    | '/'
    | '/cinematicUniverseCreate'
    | '/dashboard'
    | '/discover'
    | '/docs'
    | '/login'
    | '/market'
    | '/my-works'
    | '/sandbox'
    | '/upload'
    | '/videos'
    | '/create/$kind'
    | '/profile/$username'
    | '/profile/edit'
    | '/universe/$id'
    | '/create/'
    | '/wiki/'
    | '/event/$universe/$event'
    | '/wiki/character/$id'
    | '/wiki/entity/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CinematicUniverseCreateRoute: typeof CinematicUniverseCreateRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  DocsRoute: typeof DocsRoute
  LoginRoute: typeof LoginRoute
  MarketRoute: typeof MarketRoute
  MyWorksRoute: typeof MyWorksRoute
  SandboxRoute: typeof SandboxRoute
  UploadRoute: typeof UploadRoute
  VideosRoute: typeof VideosRoute
  CreateKindRoute: typeof CreateKindRoute
  ProfileUsernameRoute: typeof ProfileUsernameRoute
  ProfileEditRoute: typeof ProfileEditRoute
  UniverseIdRoute: typeof UniverseIdRoute
  CreateIndexRoute: typeof CreateIndexRoute
  WikiIndexRoute: typeof WikiIndexRoute
  EventUniverseEventRoute: typeof EventUniverseEventRoute
  WikiCharacterIdRoute: typeof WikiCharacterIdRoute
  WikiEntityIdRoute: typeof WikiEntityIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/upload': {
      id: '/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof UploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/videos': {
      id: '/videos'
      path: '/videos'
      fullPath: '/videos'
      preLoaderRoute: typeof VideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sandbox': {
      id: '/sandbox'
      path: '/sandbox'
      fullPath: '/sandbox'
      preLoaderRoute: typeof SandboxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-works': {
      id: '/my-works'
      path: '/my-works'
      fullPath: '/my-works'
      preLoaderRoute: typeof MyWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/market': {
      id: '/market'
      path: '/market'
      fullPath: '/market'
      preLoaderRoute: typeof MarketRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cinematicUniverseCreate': {
      id: '/cinematicUniverseCreate'
      path: '/cinematicUniverseCreate'
      fullPath: '/cinematicUniverseCreate'
      preLoaderRoute: typeof CinematicUniverseCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/wiki'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/': {
      id: '/create/'
      path: '/create'
      fullPath: '/create/'
      preLoaderRoute: typeof CreateIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/universe/$id': {
      id: '/universe/$id'
      path: '/universe/$id'
      fullPath: '/universe/$id'
      preLoaderRoute: typeof UniverseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$username': {
      id: '/profile/$username'
      path: '/profile/$username'
      fullPath: '/profile/$username'
      preLoaderRoute: typeof ProfileUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create/$kind': {
      id: '/create/$kind'
      path: '/create/$kind'
      fullPath: '/create/$kind'
      preLoaderRoute: typeof CreateKindRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/entity/$id': {
      id: '/wiki/entity/$id'
      path: '/wiki/entity/$id'
      fullPath: '/wiki/entity/$id'
      preLoaderRoute: typeof WikiEntityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/character/$id': {
      id: '/wiki/character/$id'
      path: '/wiki/character/$id'
      fullPath: '/wiki/character/$id'
      preLoaderRoute: typeof WikiCharacterIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/event/$universe/$event': {
      id: '/event/$universe/$event'
      path: '/event/$universe/$event'
      fullPath: '/event/$universe/$event'
      preLoaderRoute: typeof EventUniverseEventRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CinematicUniverseCreateRoute: CinematicUniverseCreateRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  DocsRoute: DocsRoute,
  LoginRoute: LoginRoute,
  MarketRoute: MarketRoute,
  MyWorksRoute: MyWorksRoute,
  SandboxRoute: SandboxRoute,
  UploadRoute: UploadRoute,
  VideosRoute: VideosRoute,
  CreateKindRoute: CreateKindRoute,
  ProfileUsernameRoute: ProfileUsernameRoute,
  ProfileEditRoute: ProfileEditRoute,
  UniverseIdRoute: UniverseIdRoute,
  CreateIndexRoute: CreateIndexRoute,
  WikiIndexRoute: WikiIndexRoute,
  EventUniverseEventRoute: EventUniverseEventRoute,
  WikiCharacterIdRoute: WikiCharacterIdRoute,
  WikiEntityIdRoute: WikiEntityIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
