/**
 * Audio Model Registry — Central source of truth for all supported audio/music generation models.
 *
 * Dual-margin pricing model (matches video):
 * - providerCostUsd = what we pay the AI provider per generation
 * - fiatPriceUsd = providerCostUsd * 1.35 (35% margin for card/crypto)
 * - loarPriceUsd = providerCostUsd * 1.25 (25% margin for $LOAR payments)
 */
import type { AudioModelConfig, AudioGenerationMode } from './types';

export const FIAT_MARGIN = 1.35;
export const LOAR_MARGIN = 1.25;
export const LOAR_TO_USD = 0.01;

function withFiatMargin(providerCost: number): number {
  return Math.round(providerCost * FIAT_MARGIN * 100) / 100;
}

function withLoarMargin(providerCost: number): number {
  return Math.round(providerCost * LOAR_MARGIN * 100) / 100;
}

function usdToLoar(usd: number): number {
  return Math.ceil(usd / LOAR_TO_USD);
}

export const AUDIO_MODELS: AudioModelConfig[] = [
  // ── Music Generation ───────────────────────────────────────────────
  {
    id: 'stable-audio-2',
    provider: 'fal',
    displayName: 'Stable Audio 2.0',
    shortDescription: 'High-quality music & sound from text, up to 47s',
    falModelId: 'fal-ai/stable-audio',
    mode: ['text_to_music', 'text_to_sound'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxDurationSec: 47,
    supportedDurations: [5, 10, 15, 30, 47],
    creditCost: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'ambient', 'cinematic', 'sound-design'],
    bestFor: 'Theme music, ambient soundscapes, cinematic scores',
  },
  {
    id: 'musicgen-large',
    provider: 'fal',
    displayName: 'MusicGen Large',
    shortDescription: 'Meta music generation, versatile styles',
    falModelId: 'fal-ai/musicgen/large',
    mode: ['text_to_music'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxDurationSec: 30,
    supportedDurations: [5, 10, 15, 30],
    creditCost: usdToLoar(withFiatMargin(0.02)),
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'fast', 'versatile'],
    bestFor: 'Quick music drafts, background tracks',
  },
  {
    id: 'musicgen-stereo-large',
    provider: 'fal',
    displayName: 'MusicGen Stereo',
    shortDescription: 'Stereo music generation with richer spatial audio',
    falModelId: 'fal-ai/musicgen/stereo-large',
    mode: ['text_to_music'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    maxDurationSec: 30,
    supportedDurations: [5, 10, 15, 30],
    creditCost: usdToLoar(withFiatMargin(0.03)),
    providerCostUsd: 0.03,
    fiatPriceUsd: withFiatMargin(0.03),
    loarPriceUsd: withLoarMargin(0.03),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'stereo', 'spatial'],
    bestFor: 'Stereo music with spatial depth',
  },

  // ── Stable Audio 2.5 — supersedes 2.0 ─────────────────────────────────
  {
    id: 'stable-audio-25',
    provider: 'fal',
    displayName: 'Stable Audio 2.5',
    shortDescription: 'Long-form music & SFX up to 190s — text-to-audio',
    falModelId: 'fal-ai/stable-audio-25/text-to-audio',
    mode: ['text_to_music', 'text_to_sound'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxDurationSec: 190,
    supportedDurations: [5, 10, 30, 60, 90, 120, 190],
    creditCost: usdToLoar(withFiatMargin(0.2)),
    providerCostUsd: 0.2,
    fiatPriceUsd: withFiatMargin(0.2),
    loarPriceUsd: withLoarMargin(0.2),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'sound-design', 'long-form', 'cinematic'],
    bestFor: 'Long-form theme music, full-scene scores, ambient pieces up to 3 minutes',
  },
  {
    id: 'stable-audio-25-a2a',
    provider: 'fal',
    displayName: 'Stable Audio 2.5 A2A',
    shortDescription: 'Audio-to-audio variation / continuation on Stable Audio 2.5',
    falModelId: 'fal-ai/stable-audio-25/audio-to-audio',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxDurationSec: 190,
    supportedDurations: [30, 60, 120, 190],
    creditCost: usdToLoar(withFiatMargin(0.2)),
    providerCostUsd: 0.2,
    fiatPriceUsd: withFiatMargin(0.2),
    loarPriceUsd: withLoarMargin(0.2),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'a2a', 'variation', 'continuation'],
    bestFor: 'Generating variations of an existing music clip while keeping vibe',
  },

  // ── MiniMax Music (lyrics + vocals) ──────────────────────────────────
  {
    id: 'minimax-music-v2',
    provider: 'fal',
    displayName: 'MiniMax Music 2.0',
    shortDescription: 'Vocal songs with lyrics — full-song generation',
    falModelId: 'fal-ai/minimax-music/v2',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    maxDurationSec: 120,
    supportedDurations: [30, 60, 90, 120],
    creditCost: usdToLoar(withFiatMargin(0.03)),
    providerCostUsd: 0.03,
    fiatPriceUsd: withFiatMargin(0.03),
    loarPriceUsd: withLoarMargin(0.03),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'vocals', 'lyrics', 'song'],
    bestFor: 'Full songs with vocals + lyrics — episode theme songs, end credits',
  },
  {
    id: 'minimax-music-v25',
    provider: 'fal',
    displayName: 'MiniMax Music 2.5',
    shortDescription: 'Newer MiniMax — better vocals and instrumentation',
    falModelId: 'fal-ai/minimax-music/v2.5',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    maxDurationSec: 120,
    supportedDurations: [30, 60, 90, 120],
    creditCost: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'vocals', 'lyrics', 'song'],
    bestFor: 'Premium vocal songs with cleaner instrumentation',
  },
  {
    id: 'minimax-music-v26',
    provider: 'fal',
    displayName: 'MiniMax Music 2.6',
    shortDescription: 'Latest MiniMax — flagship vocal/instrumental gen',
    falModelId: 'fal-ai/minimax-music/v2.6',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxDurationSec: 120,
    supportedDurations: [30, 60, 90, 120],
    creditCost: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'vocals', 'lyrics', 'song', 'latest'],
    bestFor: 'Latest flagship — best for theme songs and trailer cues',
  },

  // ── Sonauto V2 ────────────────────────────────────────────────────────
  {
    id: 'sonauto-v2',
    provider: 'fal',
    displayName: 'Sonauto V2',
    shortDescription: 'Full songs with auto-generated lyrics',
    falModelId: 'fal-ai/sonauto/v2/text-to-music',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxDurationSec: 180,
    supportedDurations: [60, 120, 180],
    creditCost: usdToLoar(withFiatMargin(0.075)),
    providerCostUsd: 0.075,
    fiatPriceUsd: withFiatMargin(0.075),
    loarPriceUsd: withLoarMargin(0.075),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'vocals', 'lyrics', 'auto-lyrics'],
    bestFor: 'Hands-off full-song gen with auto-written lyrics',
  },

  // ── ElevenLabs Music (BYOK direct or FAL passthrough) ─────────────────
  {
    id: 'elevenlabs-music-fal',
    provider: 'fal',
    displayName: 'ElevenLabs Music (via FAL)',
    shortDescription: 'Section-level control, broadcast-quality music',
    falModelId: 'fal-ai/elevenlabs/music',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    maxDurationSec: 600,
    supportedDurations: [30, 60, 120, 180, 300, 600],
    creditCost: usdToLoar(withFiatMargin(0.8)), // $0.80/min — assume 1-min default
    providerCostUsd: 0.8,
    fiatPriceUsd: withFiatMargin(0.8),
    loarPriceUsd: withLoarMargin(0.8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'premium', 'broadcast', 'sections'],
    bestFor: 'Premium scene scoring with section-level structure (intro/verse/chorus)',
  },
  {
    id: 'elevenlabs-music-direct',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Music (Direct)',
    shortDescription: 'Direct ElevenLabs music_v1 — cheaper than FAL passthrough',
    elevenlabsModelId: 'music_v1',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    maxDurationSec: 600,
    supportedDurations: [3, 10, 30, 60, 120, 180, 300, 600],
    creditCost: usdToLoar(withFiatMargin(0.4)), // direct is roughly half of FAL passthrough
    providerCostUsd: 0.4,
    fiatPriceUsd: withFiatMargin(0.4),
    loarPriceUsd: withLoarMargin(0.4),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'premium', 'direct', 'byok', 'sections'],
    bestFor:
      'Premium music with section-level control — cheapest path when user has ElevenLabs BYOK',
  },

  // ── Google Lyria ──────────────────────────────────────────────────────
  {
    id: 'lyria-2-fal',
    provider: 'fal',
    displayName: 'Google Lyria 2 (via FAL)',
    shortDescription: 'Google Lyria 2 — 48kHz HQ music',
    falModelId: 'fal-ai/lyria2',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxDurationSec: 30,
    supportedDurations: [10, 20, 30],
    creditCost: usdToLoar(withFiatMargin(0.1)),
    providerCostUsd: 0.1,
    fiatPriceUsd: withFiatMargin(0.1),
    loarPriceUsd: withLoarMargin(0.1),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'google', 'lyria', 'hq'],
    bestFor: '48kHz high-quality short music cues',
  },
  {
    id: 'lyria-3-clip-google',
    provider: 'google',
    displayName: 'Google Lyria 3 Clip',
    shortDescription: '30s MP3 clip generation — preview',
    googleModelId: 'lyria-3-clip-preview',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    maxDurationSec: 30,
    supportedDurations: [30],
    creditCost: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'google', 'lyria', 'preview', 'clip'],
    bestFor: 'Short cue gen via Google direct — cheapest 30s music',
  },
  {
    id: 'lyria-3-pro-google',
    provider: 'google',
    displayName: 'Google Lyria 3 Pro',
    shortDescription: '~2-minute songs, MP3/WAV — preview',
    googleModelId: 'lyria-3-pro-preview',
    mode: ['text_to_music'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'low',
    maxDurationSec: 120,
    supportedDurations: [60, 90, 120],
    creditCost: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'google', 'lyria', 'preview', 'song'],
    bestFor: 'Full ~2-min songs via Google direct (preview)',
  },

  // ── ACE-Step ──────────────────────────────────────────────────────────
  {
    id: 'ace-step-fal',
    provider: 'fal',
    displayName: 'ACE-Step',
    shortDescription: 'Per-second ACE-Step music — cheapest long-form',
    falModelId: 'fal-ai/ace-step',
    mode: ['text_to_music'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxDurationSec: 240,
    supportedDurations: [30, 60, 120, 180, 240],
    creditCost: usdToLoar(withFiatMargin(0.012)), // $0.0002/s × 60s default
    providerCostUsd: 0.012,
    fiatPriceUsd: withFiatMargin(0.012),
    loarPriceUsd: withLoarMargin(0.012),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'fast', 'budget', 'long-form'],
    bestFor: 'Cheapest long-form music — backgrounds, montages, demos',
  },

  // ── Cassette / Beatoven (royalty-free background) ────────────────────
  {
    id: 'cassetteai-music',
    provider: 'fal',
    displayName: 'CassetteAI Music',
    shortDescription: 'Fast royalty-free instrumental beds',
    falModelId: 'fal-ai/cassetteai/music-generator',
    mode: ['text_to_music'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxDurationSec: 180,
    supportedDurations: [30, 60, 120, 180],
    creditCost: usdToLoar(withFiatMargin(0.02)),
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'royalty-free', 'background', 'fast'],
    bestFor: 'Cheap fast instrumental background music',
  },
  {
    id: 'beatoven-music',
    provider: 'fal',
    displayName: 'Beatoven Music',
    shortDescription: 'Beatoven royalty-free music generation',
    falModelId: 'fal-ai/beatoven/music-generation',
    mode: ['text_to_music'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    maxDurationSec: 240,
    supportedDurations: [30, 60, 120, 180, 240],
    creditCost: usdToLoar(withFiatMargin(0.1)),
    providerCostUsd: 0.1,
    fiatPriceUsd: withFiatMargin(0.1),
    loarPriceUsd: withLoarMargin(0.1),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['music', 'royalty-free', 'background'],
    bestFor: 'Royalty-free music with mood-based prompting',
  },

  // ── SFX (text-to-sound and video-conditioned foley) ──────────────────
  {
    id: 'elevenlabs-sfx-direct',
    provider: 'elevenlabs',
    displayName: 'ElevenLabs Sound Effects (Direct)',
    shortDescription: 'Text-to-SFX via ElevenLabs',
    elevenlabsModelId: 'sound_effects_v1',
    mode: ['text_to_sound'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'medium',
    maxDurationSec: 22,
    supportedDurations: [1, 3, 5, 10, 15, 22],
    creditCost: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['sfx', 'sound-effects', 'foley', 'direct', 'byok'],
    bestFor: 'High-quality short SFX (footsteps, ambience, impacts, magic)',
  },
  {
    id: 'controlfoley-fal',
    provider: 'fal',
    displayName: 'ControlFoley',
    shortDescription: 'Video-to-audio synced SFX (foley)',
    falModelId: 'fal-ai/controlfoley',
    mode: ['text_to_sound'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxDurationSec: 30,
    supportedDurations: [5, 10, 15, 20, 30],
    creditCost: usdToLoar(withFiatMargin(0.12)),
    providerCostUsd: 0.12,
    fiatPriceUsd: withFiatMargin(0.12),
    loarPriceUsd: withLoarMargin(0.12),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['sfx', 'foley', 'video-synced'],
    bestFor: 'Auto-foley for video — adds synced footsteps, doors, impacts',
  },
  {
    id: 'pixverse-sfx-fal',
    provider: 'fal',
    displayName: 'PixVerse Sound Effects',
    shortDescription: 'Add SFX layer to videos',
    falModelId: 'fal-ai/pixverse/sound-effects',
    mode: ['text_to_sound'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    maxDurationSec: 30,
    supportedDurations: [5, 10, 15, 20, 30],
    creditCost: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['sfx', 'video-overlay'],
    bestFor: 'Add SFX layer to existing PixVerse videos',
  },
];

// ── Lookup Helpers ───────────────────────────────────────────────────

export function getModelById(id: string): AudioModelConfig | undefined {
  return AUDIO_MODELS.find((m) => m.id === id);
}

export function getModelByFalId(falId: string): AudioModelConfig | undefined {
  return AUDIO_MODELS.find((m) => m.falModelId === falId);
}

export function getEnabledModels(): AudioModelConfig[] {
  return AUDIO_MODELS.filter((m) => m.isEnabled);
}

export function getVisibleModels(): AudioModelConfig[] {
  return AUDIO_MODELS.filter((m) => m.isEnabled && m.isVisibleToUsers);
}

export function getModelsForMode(mode: AudioGenerationMode): AudioModelConfig[] {
  return AUDIO_MODELS.filter((m) => m.isEnabled && m.mode.includes(mode));
}

export function getModelIds(): string[] {
  return AUDIO_MODELS.map((m) => m.id);
}
