/**
 * Video Editing Models Registry
 *
 * Central source of truth for all post-processing / editing models.
 * Covers: upscaling, frame interpolation, video-to-video restyle,
 * inpainting, background removal, and clip extension.
 *
 * All models are accessed via FAL.ai API.
 */
import type { EditingModelConfig, EditingOperation } from './types';

/** Margin for credit card / ETH / other crypto purchases */
const FIAT_MARGIN = 1.35;

/** Margin for $LOAR token purchases */
const LOAR_MARGIN = 1.25;

/** $LOAR token to USD conversion rate */
const LOAR_TO_USD = 0.01;

function withFiatMargin(cost: number): number {
  return Math.round(cost * FIAT_MARGIN * 100) / 100;
}
function withLoarMargin(cost: number): number {
  return Math.round(cost * LOAR_MARGIN * 100) / 100;
}
function usdToLoar(usd: number): number {
  return Math.ceil(usd / LOAR_TO_USD);
}

export const EDITING_MODELS: EditingModelConfig[] = [
  // ── Upscale ──────────────────────────────────────────────────────────
  {
    id: 'upscale-esrgan',
    operation: 'upscale',
    provider: 'fal',
    displayName: 'Real-ESRGAN 4×',
    shortDescription: 'Fast 4× super-resolution for images and video frames',
    falModelId: 'fal-ai/real-esrgan',
    tier: 'fast',
    providerCostUsd: 0.01,
    fiatPriceUsd: withFiatMargin(0.01),
    loarPriceUsd: withLoarMargin(0.01),
    creditCost: usdToLoar(withFiatMargin(0.01)),
    isEnabled: true,
    maxInputResolution: '1080p',
    outputResolution: '4k',
    supportsVideo: false,
    supportsImage: true,
    tags: ['upscale', '4k', 'super-resolution', 'fast'],
    bestFor: 'Quick 4× upscale of images and video frames',
  },
  {
    id: 'upscale-clarity',
    operation: 'upscale',
    provider: 'fal',
    displayName: 'Clarity Upscaler',
    shortDescription: 'AI-enhanced upscale with detail regeneration',
    falModelId: 'fal-ai/clarity-upscaler',
    tier: 'quality',
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    creditCost: usdToLoar(withFiatMargin(0.04)),
    isEnabled: true,
    maxInputResolution: '1080p',
    outputResolution: '4k',
    supportsVideo: false,
    supportsImage: true,
    tags: ['upscale', '4k', 'detail', 'quality'],
    bestFor: 'High-quality upscale with AI detail enhancement',
  },
  {
    id: 'upscale-creative',
    operation: 'upscale',
    provider: 'fal',
    displayName: 'Creative Upscaler',
    shortDescription: 'Prompt-guided upscale — adds detail based on description',
    falModelId: 'fal-ai/creative-upscaler',
    tier: 'quality',
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    creditCost: usdToLoar(withFiatMargin(0.05)),
    isEnabled: true,
    maxInputResolution: '1080p',
    outputResolution: '4k',
    supportsVideo: false,
    supportsImage: true,
    tags: ['upscale', '4k', 'creative', 'prompt-guided'],
    bestFor: 'Upscale with prompt-guided detail generation',
  },

  // ── Frame Interpolation ──────────────────────────────────────────────
  {
    id: 'interpolate-film',
    operation: 'interpolate',
    provider: 'fal',
    displayName: 'FILM Interpolation',
    shortDescription: 'Smooth slow-motion via frame interpolation (2× – 8×)',
    falModelId: 'fal-ai/frame-interpolation',
    tier: 'fast',
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    creditCost: usdToLoar(withFiatMargin(0.02)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['interpolation', 'slow-motion', 'smooth', 'frame-rate'],
    bestFor: 'Create smooth slow-motion from any video',
  },

  // ── Video-to-Video Restyle ───────────────────────────────────────────
  {
    id: 'restyle-wan-v2v',
    operation: 'restyle',
    provider: 'fal',
    displayName: 'WAN Video-to-Video',
    shortDescription: 'Restyle a video with a new prompt while preserving motion',
    falModelId: 'fal-ai/wan/v2.1/video-to-video',
    tier: 'standard',
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    creditCost: usdToLoar(withFiatMargin(0.08)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['restyle', 'video-to-video', 'style-transfer', 'motion-preserve'],
    bestFor: 'Restyle video while keeping original motion and structure',
  },
  {
    id: 'restyle-kling-v2v',
    operation: 'restyle',
    provider: 'fal',
    displayName: 'Kling Video-to-Video',
    shortDescription: 'Premium video restyling with Kling quality',
    falModelId: 'fal-ai/kling-video/v2/master/video-to-video',
    tier: 'quality',
    providerCostUsd: 0.15,
    fiatPriceUsd: withFiatMargin(0.15),
    loarPriceUsd: withLoarMargin(0.15),
    creditCost: usdToLoar(withFiatMargin(0.15)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['restyle', 'video-to-video', 'premium', 'kling'],
    bestFor: 'Premium quality video restyling',
  },

  // ── Inpainting (Image — applied to video keyframes) ──────────────────
  {
    id: 'inpaint-flux',
    operation: 'inpaint',
    provider: 'fal',
    displayName: 'FLUX Fill Inpaint',
    shortDescription: 'Paint over a region and describe the replacement',
    falModelId: 'fal-ai/flux/dev/inpainting',
    tier: 'standard',
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    creditCost: usdToLoar(withFiatMargin(0.02)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['inpaint', 'edit', 'region', 'replace'],
    bestFor: 'Replace objects or areas in video frames',
  },
  {
    id: 'inpaint-eraser',
    operation: 'inpaint',
    provider: 'fal',
    displayName: 'LAMA Object Eraser',
    shortDescription: 'Prompt-free clean object removal (no new content synthesized)',
    falModelId: 'fal-ai/lama',
    tier: 'fast',
    providerCostUsd: 0.005,
    fiatPriceUsd: withFiatMargin(0.005),
    loarPriceUsd: withLoarMargin(0.005),
    creditCost: usdToLoar(withFiatMargin(0.005)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['inpaint', 'erase', 'remove', 'lama', 'cleanup'],
    bestFor: 'Cleanly erase an object and fill with plausible surrounding texture',
  },

  // ── Background Removal ───────────────────────────────────────────────
  {
    id: 'remove-bg-birefnet',
    operation: 'remove_bg',
    provider: 'fal',
    displayName: 'BiRefNet Background Removal',
    shortDescription: 'Remove or replace video/image backgrounds',
    falModelId: 'fal-ai/birefnet',
    tier: 'fast',
    providerCostUsd: 0.005,
    fiatPriceUsd: withFiatMargin(0.005),
    loarPriceUsd: withLoarMargin(0.005),
    creditCost: usdToLoar(withFiatMargin(0.005)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['background', 'remove', 'mask', 'segment'],
    bestFor: 'Clean background removal for compositing',
  },

  // ── Relight (image — preserve subject, change lighting/backdrop/mood) ──
  {
    id: 'relight-nano-banana',
    operation: 'relight',
    provider: 'fal',
    displayName: 'Nano Banana Relight',
    shortDescription:
      'Change lighting, time of day, backdrop, or color mood while preserving subject identity',
    falModelId: 'fal-ai/nano-banana/edit',
    tier: 'standard',
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    creditCost: usdToLoar(withFiatMargin(0.04)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['relight', 'backdrop', 'time-of-day', 'color-mood', 'subject-preserve'],
    bestFor: 'Same character/scene, new lighting and atmosphere — trailers, ads, episode beats',
  },

  // ── Retexture (image — preserve subject, swap material/surface) ──────
  {
    id: 'retexture-nano-banana',
    operation: 'retexture',
    provider: 'fal',
    displayName: 'Nano Banana Retexture',
    shortDescription:
      'Swap surface materials, fabric, or texture while preserving subject geometry',
    falModelId: 'fal-ai/nano-banana/edit',
    tier: 'standard',
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    creditCost: usdToLoar(withFiatMargin(0.04)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['retexture', 'material', 'surface', 'subject-preserve'],
    bestFor: 'Same subject, different material — marble, metal, fabric swaps for concept variants',
  },

  // ── Video Extension ──────────────────────────────────────────────────
  {
    id: 'extend-wan',
    operation: 'extend',
    provider: 'fal',
    displayName: 'WAN Video Extend',
    shortDescription: 'Extend a video clip by generating continuation frames',
    falModelId: 'fal-ai/wan/v2.1/image-to-video',
    tier: 'standard',
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    creditCost: usdToLoar(withFiatMargin(0.08)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['extend', 'continuation', 'longer', 'video'],
    bestFor: 'Extend clips by generating continuation from last frame',
  },

  // ── Premium video upscalers ───────────────────────────────────────────
  {
    id: 'upscale-topaz-video',
    operation: 'upscale',
    provider: 'fal',
    displayName: 'Topaz Video Upscale',
    shortDescription: 'Premium video super-resolution — best-in-class',
    falModelId: 'fal-ai/topaz/upscale/video',
    tier: 'quality',
    providerCostUsd: 0.2, // assume ~10s video at $0.02/s 1080p
    fiatPriceUsd: withFiatMargin(0.2),
    loarPriceUsd: withLoarMargin(0.2),
    creditCost: usdToLoar(withFiatMargin(0.2)),
    isEnabled: true,
    maxInputResolution: '4k',
    outputResolution: '8k',
    supportsVideo: true,
    supportsImage: false,
    tags: ['upscale', 'video', '4k', '8k', 'topaz', 'premium'],
    bestFor: 'Hero-shot video upscaling to 4K/8K with temporal consistency',
  },
  {
    id: 'upscale-seedvr2-video',
    operation: 'upscale',
    provider: 'fal',
    displayName: 'SeedVR2 Video',
    shortDescription: 'Temporally consistent video upscale',
    falModelId: 'fal-ai/seedvr/upscale/video',
    tier: 'standard',
    providerCostUsd: 0.1,
    fiatPriceUsd: withFiatMargin(0.1),
    loarPriceUsd: withLoarMargin(0.1),
    creditCost: usdToLoar(withFiatMargin(0.1)),
    isEnabled: true,
    maxInputResolution: '1080p',
    outputResolution: '4k',
    supportsVideo: true,
    supportsImage: false,
    tags: ['upscale', 'video', 'temporal', 'seedvr2'],
    bestFor: 'Mid-tier video upscale with stable temporal coherence',
  },
  {
    id: 'upscale-flashvsr',
    operation: 'upscale',
    provider: 'fal',
    displayName: 'FlashVSR',
    shortDescription: 'Fastest video upscaler',
    falModelId: 'fal-ai/flashvsr/upscale/video',
    tier: 'fast',
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    creditCost: usdToLoar(withFiatMargin(0.05)),
    isEnabled: true,
    maxInputResolution: '1080p',
    outputResolution: '4k',
    supportsVideo: true,
    supportsImage: false,
    tags: ['upscale', 'video', 'fast', 'flashvsr'],
    bestFor: 'Cheapest fast video upscale',
  },
  {
    id: 'upscale-bria-video-8k',
    operation: 'upscale',
    provider: 'fal',
    displayName: 'Bria Video Up-to-8K',
    shortDescription: 'Bria video super-resolution to 8K',
    falModelId: 'bria/video/increase-resolution',
    tier: 'quality',
    providerCostUsd: 0.3,
    fiatPriceUsd: withFiatMargin(0.3),
    loarPriceUsd: withLoarMargin(0.3),
    creditCost: usdToLoar(withFiatMargin(0.3)),
    isEnabled: true,
    maxInputResolution: '4k',
    outputResolution: '8k',
    supportsVideo: true,
    supportsImage: false,
    tags: ['upscale', 'video', '8k', 'bria'],
    bestFor: '8K video upscaling for premium delivery',
  },
  {
    id: 'upscale-topaz-image',
    operation: 'upscale',
    provider: 'fal',
    displayName: 'Topaz Image Upscale',
    shortDescription: 'Premium image upscaler — Topaz Photo AI',
    falModelId: 'fal-ai/topaz/upscale/image',
    tier: 'quality',
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    creditCost: usdToLoar(withFiatMargin(0.04)),
    isEnabled: true,
    maxInputResolution: '4k',
    outputResolution: '8k',
    supportsVideo: false,
    supportsImage: true,
    tags: ['upscale', 'image', 'topaz', 'premium'],
    bestFor: 'Premium image super-resolution',
  },
  {
    id: 'upscale-seedvr2-image',
    operation: 'upscale',
    provider: 'fal',
    displayName: 'SeedVR2 Image',
    shortDescription: 'High-quality image upscaler',
    falModelId: 'fal-ai/seedvr/upscale/image',
    tier: 'standard',
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    creditCost: usdToLoar(withFiatMargin(0.02)),
    isEnabled: true,
    maxInputResolution: '1080p',
    outputResolution: '4k',
    supportsVideo: false,
    supportsImage: true,
    tags: ['upscale', 'image', 'seedvr2'],
    bestFor: 'Reliable image upscale at mid-tier price',
  },

  // ── Interpolation additions ───────────────────────────────────────────
  {
    id: 'interpolate-rife',
    operation: 'interpolate',
    provider: 'fal',
    displayName: 'RIFE Frame Interpolation',
    shortDescription: 'Cheap fast frame interpolation',
    falModelId: 'fal-ai/rife',
    tier: 'fast',
    providerCostUsd: 0.005,
    fiatPriceUsd: withFiatMargin(0.005),
    loarPriceUsd: withLoarMargin(0.005),
    creditCost: usdToLoar(withFiatMargin(0.005)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['interpolate', 'rife', 'fast', 'budget'],
    bestFor: 'Cheap 2×/4× frame interpolation for smooth motion',
  },
  {
    id: 'interpolate-amt',
    operation: 'interpolate',
    provider: 'fal',
    displayName: 'AMT Frame Interpolation',
    shortDescription: 'Quality frame interpolation',
    falModelId: 'fal-ai/amt-interpolation',
    tier: 'standard',
    providerCostUsd: 0.01,
    fiatPriceUsd: withFiatMargin(0.01),
    loarPriceUsd: withLoarMargin(0.01),
    creditCost: usdToLoar(withFiatMargin(0.01)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['interpolate', 'amt'],
    bestFor: 'Higher-quality frame interpolation',
  },

  // ── Lipsync ───────────────────────────────────────────────────────────
  {
    id: 'lipsync-sync-v3',
    operation: 'retexture', // closest existing op; consider a 'lipsync' op later
    provider: 'fal',
    displayName: 'Sync.so v3 Lipsync',
    shortDescription: 'Premium lipsync v3',
    falModelId: 'fal-ai/sync-lipsync/v3',
    tier: 'quality',
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    creditCost: usdToLoar(withFiatMargin(0.08)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: true,
    tags: ['lipsync', 'sync.so', 'v3', 'premium'],
    bestFor: 'High-quality lipsync of dialogue onto talking heads',
  },
  {
    id: 'lipsync-heygen-v3',
    operation: 'retexture',
    provider: 'fal',
    displayName: 'HeyGen v3 Lipsync',
    shortDescription: 'HeyGen v3 — precision or speed mode',
    falModelId: 'fal-ai/heygen/v3/lipsync/precision',
    tier: 'quality',
    providerCostUsd: 0.12,
    fiatPriceUsd: withFiatMargin(0.12),
    loarPriceUsd: withLoarMargin(0.12),
    creditCost: usdToLoar(withFiatMargin(0.12)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: true,
    tags: ['lipsync', 'heygen', 'v3', 'premium'],
    bestFor: 'Premium HeyGen lipsync for avatar / talking-head scenes',
  },
  {
    id: 'lipsync-kling-a2v',
    operation: 'retexture',
    provider: 'fal',
    displayName: 'Kling Lipsync Audio-to-Video',
    shortDescription: 'Kling lipsync — audio → talking head',
    falModelId: 'fal-ai/kling-video/lipsync/audio-to-video',
    tier: 'standard',
    providerCostUsd: 0.06,
    fiatPriceUsd: withFiatMargin(0.06),
    loarPriceUsd: withLoarMargin(0.06),
    creditCost: usdToLoar(withFiatMargin(0.06)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: true,
    tags: ['lipsync', 'kling', 'a2v'],
    bestFor: 'Generating talking-head video from audio + reference image',
  },
  {
    id: 'lipsync-pixverse',
    operation: 'retexture',
    provider: 'fal',
    displayName: 'PixVerse Lipsync',
    shortDescription: 'PixVerse lipsync',
    falModelId: 'fal-ai/pixverse/lipsync',
    tier: 'fast',
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    creditCost: usdToLoar(withFiatMargin(0.04)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: true,
    tags: ['lipsync', 'pixverse', 'fast'],
    bestFor: 'Cheap fast lipsync',
  },

  // ── Background removal / matting ─────────────────────────────────────
  {
    id: 'remove-bg-bria',
    operation: 'remove_bg',
    provider: 'fal',
    displayName: 'Bria Background Remove',
    shortDescription: 'Bria background removal — image',
    falModelId: 'bria/background/remove',
    tier: 'standard',
    providerCostUsd: 0.01,
    fiatPriceUsd: withFiatMargin(0.01),
    loarPriceUsd: withLoarMargin(0.01),
    creditCost: usdToLoar(withFiatMargin(0.01)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['bg-removal', 'bria', 'image'],
    bestFor: 'Image background removal with clean masks',
  },
  {
    id: 'remove-bg-bria-video',
    operation: 'remove_bg',
    provider: 'fal',
    displayName: 'Bria Video Background Removal',
    shortDescription: 'Video matte / background removal',
    falModelId: 'bria/video/background-removal',
    tier: 'quality',
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    creditCost: usdToLoar(withFiatMargin(0.08)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['bg-removal', 'bria', 'video', 'matte'],
    bestFor: 'Pull a clean matte for video subjects',
  },
  {
    id: 'remove-bg-veed-video',
    operation: 'remove_bg',
    provider: 'fal',
    displayName: 'Veed Video BG Removal',
    shortDescription: 'Veed video matting',
    falModelId: 'veed/video-background-removal',
    tier: 'standard',
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    creditCost: usdToLoar(withFiatMargin(0.05)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['bg-removal', 'veed', 'video', 'matte'],
    bestFor: 'Mid-tier video matting',
  },
  {
    id: 'remove-bg-birefnet-v2',
    operation: 'remove_bg',
    provider: 'fal',
    displayName: 'BiRefNet v2',
    shortDescription: 'BiRefNet v2 — successor to BiRefNet',
    falModelId: 'fal-ai/birefnet/v2',
    tier: 'fast',
    providerCostUsd: 0.005,
    fiatPriceUsd: withFiatMargin(0.005),
    loarPriceUsd: withLoarMargin(0.005),
    creditCost: usdToLoar(withFiatMargin(0.005)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['bg-removal', 'birefnet', 'v2', 'fast'],
    bestFor: 'Cheap fast BG removal — newer than v1',
  },

  // ── Inpaint / Eraser additions ───────────────────────────────────────
  {
    id: 'inpaint-bria-eraser',
    operation: 'inpaint',
    provider: 'fal',
    displayName: 'Bria Eraser',
    shortDescription: 'Removes objects/text with clean inpainting',
    falModelId: 'bria/eraser',
    tier: 'standard',
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    creditCost: usdToLoar(withFiatMargin(0.02)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['inpaint', 'eraser', 'bria'],
    bestFor: 'Clean object removal with inpainting',
  },
  {
    id: 'inpaint-finegrain-eraser',
    operation: 'inpaint',
    provider: 'fal',
    displayName: 'Finegrain Eraser',
    shortDescription: 'Removes objects + shadows + reflections',
    falModelId: 'fal-ai/finegrain-eraser',
    tier: 'quality',
    providerCostUsd: 0.03,
    fiatPriceUsd: withFiatMargin(0.03),
    loarPriceUsd: withLoarMargin(0.03),
    creditCost: usdToLoar(withFiatMargin(0.03)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['inpaint', 'eraser', 'finegrain', 'shadows'],
    bestFor: 'Eraser that also handles shadows + reflections',
  },
  {
    id: 'inpaint-bria-video-eraser',
    operation: 'inpaint',
    provider: 'fal',
    displayName: 'Bria Video Eraser',
    shortDescription: 'Per-frame video eraser (prompt/mask/keypoints)',
    falModelId: 'bria/bria_video_eraser/erase/prompt',
    tier: 'quality',
    providerCostUsd: 0.1,
    fiatPriceUsd: withFiatMargin(0.1),
    loarPriceUsd: withLoarMargin(0.1),
    creditCost: usdToLoar(withFiatMargin(0.1)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['inpaint', 'eraser', 'bria', 'video'],
    bestFor: 'Video object removal across frames',
  },

  // ── Relight additions ─────────────────────────────────────────────────
  {
    id: 'relight-lightx',
    operation: 'relight',
    provider: 'fal',
    displayName: 'LightX Relight',
    shortDescription: 'Video relight via LightX',
    falModelId: 'fal-ai/lightx/relight',
    tier: 'quality',
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    creditCost: usdToLoar(withFiatMargin(0.08)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: true,
    tags: ['relight', 'lightx', 'video'],
    bestFor: 'Relighting video shots without re-rendering',
  },
  {
    id: 'relight-recamera-lightx',
    operation: 'relight',
    provider: 'fal',
    displayName: 'LightX ReCamera',
    shortDescription: 'Re-frame video camera angle',
    falModelId: 'fal-ai/lightx/recamera',
    tier: 'quality',
    providerCostUsd: 0.1,
    fiatPriceUsd: withFiatMargin(0.1),
    loarPriceUsd: withLoarMargin(0.1),
    creditCost: usdToLoar(withFiatMargin(0.1)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['relight', 'recamera', 'lightx', 'reframe'],
    bestFor: 'Changing camera angle on existing footage',
  },
  {
    id: 'relight-bria-fibo',
    operation: 'relight',
    provider: 'fal',
    displayName: 'Bria FIBO Relight',
    shortDescription: 'Image relight via Bria FIBO',
    falModelId: 'bria/fibo-edit/relight',
    tier: 'standard',
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    creditCost: usdToLoar(withFiatMargin(0.04)),
    isEnabled: true,
    supportsVideo: false,
    supportsImage: true,
    tags: ['relight', 'bria', 'fibo'],
    bestFor: 'Single-image relighting',
  },

  // ── Video extend additions ───────────────────────────────────────────
  {
    id: 'extend-veo-31',
    operation: 'extend',
    provider: 'fal',
    displayName: 'Veo 3.1 Extend',
    shortDescription: 'Extend video continuity via Veo 3.1',
    falModelId: 'fal-ai/veo3.1/extend-video',
    tier: 'quality',
    providerCostUsd: 0.8,
    fiatPriceUsd: withFiatMargin(0.8),
    loarPriceUsd: withLoarMargin(0.8),
    creditCost: usdToLoar(withFiatMargin(0.8)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['extend', 'veo', '3.1', 'premium'],
    bestFor: 'High-quality video extension via Veo 3.1',
  },
  {
    id: 'extend-pixverse',
    operation: 'extend',
    provider: 'fal',
    displayName: 'PixVerse Extend',
    shortDescription: 'Extend video via PixVerse',
    falModelId: 'fal-ai/pixverse/v6/extend',
    tier: 'standard',
    providerCostUsd: 0.2,
    fiatPriceUsd: withFiatMargin(0.2),
    loarPriceUsd: withLoarMargin(0.2),
    creditCost: usdToLoar(withFiatMargin(0.2)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['extend', 'pixverse'],
    bestFor: 'Mid-tier video extension',
  },
  {
    id: 'extend-ltx-2',
    operation: 'extend',
    provider: 'fal',
    displayName: 'LTX-2 Extend',
    shortDescription: 'Extend via LTX-2',
    falModelId: 'fal-ai/ltx-2/extend-video',
    tier: 'fast',
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    creditCost: usdToLoar(withFiatMargin(0.05)),
    isEnabled: true,
    supportsVideo: true,
    supportsImage: false,
    tags: ['extend', 'ltx', 'fast', 'budget'],
    bestFor: 'Cheap fast video extension',
  },
];

// ── Lookup helpers ──────────────────────────────────────────────────────

export function getEditingModelById(id: string): EditingModelConfig | undefined {
  return EDITING_MODELS.find((m) => m.id === id);
}

export function getEditingModelsForOperation(op: EditingOperation): EditingModelConfig[] {
  return EDITING_MODELS.filter((m) => m.operation === op && m.isEnabled);
}

export function getEnabledEditingModels(): EditingModelConfig[] {
  return EDITING_MODELS.filter((m) => m.isEnabled);
}

export function getDefaultModelForOperation(op: EditingOperation): EditingModelConfig | undefined {
  const models = getEditingModelsForOperation(op);
  // Prefer 'standard' tier, then 'fast', then 'quality'
  return (
    models.find((m) => m.tier === 'standard') || models.find((m) => m.tier === 'fast') || models[0]
  );
}
