/**
 * Image Model Registry — all supported image generation models.
 *
 * Pricing mirrors the video registry dual-margin model:
 *   providerCostUsd — what we pay fal per image
 *   fiatPriceUsd    — providerCostUsd × 1.35 (card / ETH / crypto)
 *   loarPriceUsd    — providerCostUsd × 1.25 ($LOAR payments)
 *   creditCostPerImage — internal credits per single image
 */
import { FIAT_MARGIN, LOAR_MARGIN, LOAR_TO_USD } from '../video-models/registry';
import type { ImageModelConfig, ImageGenerationTask } from './types';

function withFiatMargin(cost: number) {
  return Math.round(cost * FIAT_MARGIN * 100) / 100;
}
function withLoarMargin(cost: number) {
  return Math.round(cost * LOAR_MARGIN * 100) / 100;
}
function usdToLoar(usd: number) {
  return Math.ceil(usd / LOAR_TO_USD);
}

export const IMAGE_MODELS: ImageModelConfig[] = [
  // ── Draft / Fast ─────────────────────────────────────────────────────
  {
    id: 'flux-schnell',
    provider: 'fal',
    displayName: 'FLUX Schnell',
    shortDescription: 'Fastest drafts — 4-step inference',
    falModelId: 'fal-ai/flux/schnell',
    tasks: ['text_to_image'],
    qualityTier: 'draft',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.003)),
    providerCostUsd: 0.003,
    fiatPriceUsd: withFiatMargin(0.003),
    loarPriceUsd: withLoarMargin(0.003),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['draft', 'fast', 'flux', 'iteration'],
    bestFor: 'Rapid iteration and concept sketching',
  },

  // ── Standard ─────────────────────────────────────────────────────────
  {
    id: 'nano-banana',
    provider: 'fal',
    displayName: 'Nano Banana',
    shortDescription: 'Default — great balance of quality and speed',
    falModelId: 'fal-ai/nano-banana',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.006)),
    providerCostUsd: 0.006,
    fiatPriceUsd: withFiatMargin(0.006),
    loarPriceUsd: withLoarMargin(0.006),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'default', 'character', 'scene'],
    bestFor: 'Character portraits, scene concepts, and entity artwork',
  },
  {
    id: 'flux-dev',
    provider: 'fal',
    displayName: 'FLUX Dev',
    shortDescription: 'High-detail research-grade output',
    falModelId: 'fal-ai/flux/dev',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.025)),
    providerCostUsd: 0.025,
    fiatPriceUsd: withFiatMargin(0.025),
    loarPriceUsd: withLoarMargin(0.025),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'detail', 'flux', 'negative-prompt'],
    bestFor: 'Detailed character art and high-fidelity concept renders',
  },

  {
    id: 'nano-banana-2',
    provider: 'fal',
    displayName: 'Nano Banana 2',
    shortDescription: 'Next-gen versatile image generation and editing',
    falModelId: 'fal-ai/nano-banana-2',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'versatile', 'character', 'scene'],
    bestFor: 'Versatile image generation and editing with improved quality',
  },
  {
    id: 'nano-banana-pro',
    provider: 'fal',
    displayName: 'Nano Banana Pro',
    shortDescription: 'Premium Nano Banana with top-tier quality',
    falModelId: 'fal-ai/nano-banana-pro',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.15)),
    providerCostUsd: 0.15,
    fiatPriceUsd: withFiatMargin(0.15),
    loarPriceUsd: withLoarMargin(0.15),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'fast', 'versatile', 'google'],
    bestFor: 'Premium image generation with state-of-the-art quality',
  },
  {
    id: 'wan27',
    provider: 'fal',
    displayName: 'WAN 2.7',
    shortDescription: 'Alibaba text-to-image generation',
    falModelId: 'fal-ai/wan/v2.7/text-to-image',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.01)),
    providerCostUsd: 0.01,
    fiatPriceUsd: withFiatMargin(0.01),
    loarPriceUsd: withLoarMargin(0.01),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'alibaba', 'wan'],
    bestFor: 'Cost-effective text-to-image generation',
  },
  {
    id: 'qwen-image',
    provider: 'fal',
    displayName: 'Qwen Image',
    shortDescription: 'Alibaba multimodal image generation',
    falModelId: 'fal-ai/qwen-image',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.02)),
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'alibaba', 'qwen', 'multimodal'],
    bestFor: 'Multimodal image generation with strong text understanding',
  },

  // ── Premium ───────────────────────────────────────────────────────────
  {
    id: 'flux-pro',
    provider: 'fal',
    displayName: 'FLUX Pro',
    shortDescription: 'Commercial-grade, highest FLUX quality',
    falModelId: 'fal-ai/flux-pro',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'commercial', 'flux', 'nft', 'final'],
    bestFor: 'Final renders, NFT art, and premium entity visuals',
  },
  {
    id: 'flux-11-pro',
    provider: 'fal',
    displayName: 'FLUX 1.1 Pro',
    shortDescription: 'Enhanced FLUX with superior detail',
    falModelId: 'fal-ai/flux-pro/v1.1',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'flux', 'enhanced', 'detail'],
    bestFor: 'Enhanced FLUX with superior composition and artistic fidelity',
  },
  {
    id: 'flux-2-pro',
    provider: 'fal',
    displayName: 'FLUX 2 Pro',
    shortDescription: 'Latest FLUX — maximum quality and photorealism',
    falModelId: 'fal-ai/flux-2-pro',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.03)),
    providerCostUsd: 0.03,
    fiatPriceUsd: withFiatMargin(0.03),
    loarPriceUsd: withLoarMargin(0.03),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'flux', 'photorealism', 'latest'],
    bestFor: 'Maximum quality photorealistic images and artistic compositions',
  },
  {
    id: 'flux-kontext-pro',
    provider: 'fal',
    displayName: 'FLUX Kontext Pro',
    shortDescription: 'Context-aware image editing and transformation',
    falModelId: 'fal-ai/flux-pro/kontext',
    tasks: ['image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'flux', 'editing', 'context-aware'],
    bestFor: 'Context-aware image editing and character consistency',
  },
  {
    id: 'recraft-v4',
    provider: 'fal',
    displayName: 'Recraft V4',
    shortDescription: 'Professional design with typography and vector',
    falModelId: 'fal-ai/recraft/v4/pro/text-to-image',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.25)),
    providerCostUsd: 0.25,
    fiatPriceUsd: withFiatMargin(0.25),
    loarPriceUsd: withLoarMargin(0.25),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'design', 'typography', 'vector', 'brand'],
    bestFor: 'Professional design with long text, vector art, and brand styles',
  },
  {
    id: 'ideogram-v3',
    provider: 'fal',
    displayName: 'Ideogram V3',
    shortDescription: 'Best-in-class text rendering in images',
    falModelId: 'fal-ai/ideogram/v3/generate',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'text-rendering', 'typography', 'ideogram'],
    bestFor: 'Images with accurate text rendering, logos, and posters',
  },
  {
    id: 'seedream-v5',
    provider: 'fal',
    displayName: 'Seedream 5.0 Lite (FAL)',
    shortDescription: 'ByteDance unified generation and editing via FAL',
    falModelId: 'fal-ai/bytedance/seedream/v5/lite/edit',
    tasks: ['image_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.03)),
    providerCostUsd: 0.03,
    fiatPriceUsd: withFiatMargin(0.03),
    loarPriceUsd: withLoarMargin(0.03),
    isEnabled: false, // superseded by direct ByteDance API
    isVisibleToUsers: false,
    allowedPlans: [],
    tags: ['standard', 'bytedance', 'editing', 'seedream', 'fal-legacy'],
    bestFor: 'Unified image generation and editing in one model',
  },

  // ── Seedream 5.0 (ByteDance Direct API — $0 provider cost) ──────────
  {
    id: 'seedream-5-direct',
    provider: 'bytedance',
    displayName: 'Seedream 5.0',
    shortDescription: 'Premium image gen — keyframes, storyboards, concept art',
    bytedanceModelId: 'seedream-5.0',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'bytedance', 'seedream', 'keyframes', 'storyboard', 'free'],
    bestFor: 'Premium keyframes, storyboards, and concept art — free via direct API',
  },
  {
    id: 'gpt-image',
    provider: 'fal',
    displayName: 'GPT Image 1.5',
    shortDescription: 'OpenAI high-fidelity image editing',
    falModelId: 'fal-ai/gpt-image-1.5/edit',
    tasks: ['image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: false,
    creditCostPerImage: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'editing', 'gpt'],
    bestFor: 'High-fidelity image editing with strong prompt adherence',
  },
];

// ── Lookup Helpers ────────────────────────────────────────────────────

const modelsById = new Map(IMAGE_MODELS.map((m) => [m.id, m]));

export function getImageModelById(id: string): ImageModelConfig | undefined {
  return modelsById.get(id);
}

export function getEnabledImageModels(): ImageModelConfig[] {
  return IMAGE_MODELS.filter((m) => m.isEnabled);
}

export function getVisibleImageModels(): ImageModelConfig[] {
  return IMAGE_MODELS.filter((m) => m.isEnabled && m.isVisibleToUsers);
}

export function getImageModelsForTask(task: ImageGenerationTask): ImageModelConfig[] {
  return getVisibleImageModels().filter((m) => m.tasks.includes(task));
}

export function getImageModelIds(): string[] {
  return IMAGE_MODELS.map((m) => m.id);
}
