/**
 * Image Model Registry — all supported image generation models.
 *
 * Pricing mirrors the video registry dual-margin model:
 *   providerCostUsd — what we pay fal per image
 *   fiatPriceUsd    — providerCostUsd × 1.35 (card / ETH / crypto)
 *   loarPriceUsd    — providerCostUsd × 1.25 ($LOAR payments)
 *   creditCostPerImage — internal credits per single image
 */
import { FIAT_MARGIN, LOAR_MARGIN, LOAR_TO_USD } from '../video-models/registry';
import type { ImageModelConfig, ImageGenerationTask } from './types';

function withFiatMargin(cost: number) {
  return Math.round(cost * FIAT_MARGIN * 100) / 100;
}
function withLoarMargin(cost: number) {
  return Math.round(cost * LOAR_MARGIN * 100) / 100;
}
function usdToLoar(usd: number) {
  return Math.ceil(usd / LOAR_TO_USD);
}

export const IMAGE_MODELS: ImageModelConfig[] = [
  // ── Draft / Fast ─────────────────────────────────────────────────────
  {
    id: 'flux-schnell',
    provider: 'fal',
    displayName: 'FLUX Schnell',
    shortDescription: 'Fastest drafts — 4-step inference',
    falModelId: 'fal-ai/flux/schnell',
    tasks: ['text_to_image'],
    qualityTier: 'draft',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.003)),
    providerCostUsd: 0.003,
    fiatPriceUsd: withFiatMargin(0.003),
    loarPriceUsd: withLoarMargin(0.003),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['draft', 'fast', 'flux', 'iteration'],
    bestFor: 'Rapid iteration and concept sketching',
  },

  // ── Standard ─────────────────────────────────────────────────────────
  {
    id: 'nano-banana',
    provider: 'fal',
    displayName: 'Nano Banana',
    shortDescription: 'Default — great balance of quality and speed',
    falModelId: 'fal-ai/nano-banana',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.006)),
    providerCostUsd: 0.006,
    fiatPriceUsd: withFiatMargin(0.006),
    loarPriceUsd: withLoarMargin(0.006),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'default', 'character', 'scene'],
    bestFor: 'Character portraits, scene concepts, and entity artwork',
  },
  {
    id: 'flux-dev',
    provider: 'fal',
    displayName: 'FLUX Dev',
    shortDescription: 'High-detail research-grade output',
    falModelId: 'fal-ai/flux/dev',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.025)),
    providerCostUsd: 0.025,
    fiatPriceUsd: withFiatMargin(0.025),
    loarPriceUsd: withLoarMargin(0.025),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'detail', 'flux', 'negative-prompt'],
    bestFor: 'Detailed character art and high-fidelity concept renders',
  },

  {
    // Per Google's own docs, `gemini-3.1-flash-image-preview` is the
    // canonical "Nano Banana 2" identifier. The earlier mapping to
    // `nano-banana-pro-preview` was wrong — that ID is the Pro tier
    // (see `nano-banana-pro-google` below).
    id: 'nano-banana-2',
    provider: 'google',
    displayName: 'Nano Banana 2',
    shortDescription: 'Gemini 3.1 Flash Image — 4K output, 14-image fusion, Preview',
    googleModelId: 'gemini-3.1-flash-image-preview',
    falModelId: 'fal-ai/nano-banana-2', // FAL fallback if Google is unavailable
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: [
      'standard',
      'fast',
      'versatile',
      'character',
      'scene',
      'google',
      'preview',
      '4k',
      'fusion',
    ],
    bestFor: 'Versatile image generation, up to 14-image multi-reference fusion, 4K output',
  },
  {
    id: 'nano-banana-pro-google',
    provider: 'google',
    displayName: 'Nano Banana Pro (Google Direct)',
    shortDescription: 'Gemini 3 Pro Image — premium fusion + inpaint, 4K, Preview',
    googleModelId: 'gemini-3-pro-image-preview',
    falModelId: 'fal-ai/nano-banana-pro',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.15)),
    providerCostUsd: 0.15,
    fiatPriceUsd: withFiatMargin(0.15),
    loarPriceUsd: withLoarMargin(0.15),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'medium', 'versatile', 'google', 'preview', '4k', 'fusion', 'inpaint'],
    bestFor:
      'Premium image generation via Google direct API — top-tier quality with 14-image fusion + inpaint',
  },
  {
    id: 'nano-banana-google-ga',
    provider: 'google',
    displayName: 'Nano Banana (Google Direct, GA)',
    shortDescription: 'Gemini 2.5 Flash Image — original Nano Banana, the only image-gen GA tier',
    googleModelId: 'gemini-2.5-flash-image',
    falModelId: 'fal-ai/nano-banana',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.039)),
    providerCostUsd: 0.039,
    fiatPriceUsd: withFiatMargin(0.039),
    loarPriceUsd: withLoarMargin(0.039),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'google', 'ga', 'fusion'],
    bestFor: 'GA Nano Banana via Google direct — 3-image fusion, 10 aspect ratios, batch-friendly',
  },
  {
    id: 'nano-banana-pro',
    provider: 'fal',
    displayName: 'Nano Banana Pro',
    shortDescription: 'Premium Nano Banana with top-tier quality',
    falModelId: 'fal-ai/nano-banana-pro',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.15)),
    providerCostUsd: 0.15,
    fiatPriceUsd: withFiatMargin(0.15),
    loarPriceUsd: withLoarMargin(0.15),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'fast', 'versatile', 'google'],
    bestFor: 'Premium image generation with state-of-the-art quality',
  },
  {
    id: 'wan27',
    provider: 'fal',
    displayName: 'WAN 2.7',
    shortDescription: 'Alibaba text-to-image generation',
    falModelId: 'fal-ai/wan/v2.7/text-to-image',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.01)),
    providerCostUsd: 0.01,
    fiatPriceUsd: withFiatMargin(0.01),
    loarPriceUsd: withLoarMargin(0.01),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'alibaba', 'wan'],
    bestFor: 'Cost-effective text-to-image generation',
  },
  {
    id: 'qwen-image',
    provider: 'fal',
    displayName: 'Qwen Image',
    shortDescription: 'Alibaba multimodal image generation',
    falModelId: 'fal-ai/qwen-image',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.02)),
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'alibaba', 'qwen', 'multimodal'],
    bestFor: 'Multimodal image generation with strong text understanding',
  },

  // ── Premium ───────────────────────────────────────────────────────────
  {
    id: 'flux-pro',
    provider: 'fal',
    displayName: 'FLUX Pro',
    shortDescription: 'Commercial-grade, highest FLUX quality',
    falModelId: 'fal-ai/flux-pro',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: false, // superseded by flux-11-pro / flux-2-pro
    allowedPlans: [],
    tags: ['premium', 'commercial', 'flux', 'nft', 'final', 'legacy'],
    bestFor: 'Final renders, NFT art, and premium entity visuals',
  },
  {
    id: 'flux-11-pro',
    provider: 'fal',
    displayName: 'FLUX 1.1 Pro',
    shortDescription: 'Enhanced FLUX with superior detail',
    falModelId: 'fal-ai/flux-pro/v1.1',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'flux', 'enhanced', 'detail'],
    bestFor: 'Enhanced FLUX with superior composition and artistic fidelity',
  },
  {
    id: 'flux-2-pro',
    provider: 'fal',
    displayName: 'FLUX 2 Pro',
    shortDescription: 'Latest FLUX — maximum quality and photorealism',
    falModelId: 'fal-ai/flux-2-pro',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.03)),
    providerCostUsd: 0.03,
    fiatPriceUsd: withFiatMargin(0.03),
    loarPriceUsd: withLoarMargin(0.03),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'flux', 'photorealism', 'latest'],
    bestFor: 'Maximum quality photorealistic images and artistic compositions',
  },
  {
    id: 'flux-kontext-pro',
    provider: 'fal',
    displayName: 'FLUX Kontext Pro',
    shortDescription: 'Context-aware image editing and transformation',
    falModelId: 'fal-ai/flux-pro/kontext',
    tasks: ['image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'flux', 'editing', 'context-aware'],
    bestFor: 'Context-aware image editing and character consistency',
  },
  {
    id: 'recraft-v4',
    provider: 'fal',
    displayName: 'Recraft V4',
    shortDescription: 'Professional design with typography and vector',
    falModelId: 'fal-ai/recraft/v4/pro/text-to-image',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.25)),
    providerCostUsd: 0.25,
    fiatPriceUsd: withFiatMargin(0.25),
    loarPriceUsd: withLoarMargin(0.25),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'design', 'typography', 'vector', 'brand'],
    bestFor: 'Professional design with long text, vector art, and brand styles',
  },
  {
    id: 'ideogram-v3',
    provider: 'fal',
    displayName: 'Ideogram V3',
    shortDescription: 'Best-in-class text rendering in images',
    falModelId: 'fal-ai/ideogram/v3/generate',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'text-rendering', 'typography', 'ideogram'],
    bestFor: 'Images with accurate text rendering, logos, and posters',
  },
  {
    id: 'seedream-v5',
    provider: 'fal',
    displayName: 'Seedream 5.0 Lite (FAL)',
    shortDescription: 'ByteDance unified generation and editing via FAL',
    falModelId: 'fal-ai/bytedance/seedream/v5/lite/edit',
    tasks: ['image_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.03)),
    providerCostUsd: 0.03,
    fiatPriceUsd: withFiatMargin(0.03),
    loarPriceUsd: withLoarMargin(0.03),
    isEnabled: false, // superseded by direct ByteDance API
    isVisibleToUsers: false,
    allowedPlans: [],
    tags: ['standard', 'bytedance', 'editing', 'seedream', 'fal-legacy'],
    bestFor: 'Unified image generation and editing in one model',
  },

  // ── Seedream 5.0 (ByteDance Direct API — $0 provider cost) ──────────
  {
    id: 'seedream-5-direct',
    provider: 'bytedance',
    displayName: 'Seedream 5.0',
    shortDescription: 'Premium image gen — keyframes, storyboards, concept art',
    bytedanceModelId: 'seedream-5-0-260128',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'bytedance', 'seedream', 'keyframes', 'storyboard', 'free'],
    bestFor: 'Premium keyframes, storyboards, and concept art — free via direct API',
  },
  {
    id: 'gpt-image',
    provider: 'fal',
    displayName: 'GPT Image 1.5',
    shortDescription: 'OpenAI high-fidelity image editing',
    falModelId: 'fal-ai/gpt-image-1.5/edit',
    tasks: ['image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: false,
    creditCostPerImage: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'editing', 'gpt'],
    bestFor: 'High-fidelity image editing with strong prompt adherence',
  },

  // ── Z.AI / Zhipu — GLM image stack ──────────────────────────────────
  // Live-confirmed against api.z.ai paas/v4 on 2026-04-26: only `glm-image`
  // is exposed. `cogview-4`, `cogview-3*`, `cogview-flash`, `cogview-pro`
  // all return code 1211 "Unknown Model".
  // ── FLUX 2 family ────────────────────────────────────────────────────
  {
    id: 'flux-2-dev',
    provider: 'fal',
    displayName: 'FLUX.2 [dev]',
    shortDescription: 'Open-weights flagship FLUX 2 with LoRA support',
    falModelId: 'fal-ai/flux-2',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.03)),
    providerCostUsd: 0.03,
    fiatPriceUsd: withFiatMargin(0.03),
    loarPriceUsd: withLoarMargin(0.03),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'flux', 'lora', 'open'],
    bestFor: 'Standard FLUX 2 with LoRA training support',
  },
  {
    id: 'flux-2-klein',
    provider: 'fal',
    displayName: 'FLUX.2 [klein] 9B',
    shortDescription: 'Distilled 9B FLUX 2 — faster, slightly smaller',
    falModelId: 'fal-ai/flux-2/klein/9b',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.015)),
    providerCostUsd: 0.015,
    fiatPriceUsd: withFiatMargin(0.015),
    loarPriceUsd: withLoarMargin(0.015),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'flux', 'fast', 'distilled', 'budget'],
    bestFor: 'Cheap fast FLUX 2 drafts',
  },
  {
    id: 'flux-2-pro-edit',
    provider: 'fal',
    displayName: 'FLUX.2 [pro] Edit',
    shortDescription: 'FLUX 2 Pro image editing — premium tier',
    falModelId: 'fal-ai/flux-2-pro/edit',
    tasks: ['image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'flux', 'editing', 'pro'],
    bestFor: 'Premium FLUX 2 Pro image editing',
  },
  {
    id: 'flux-2-pro-outpaint',
    provider: 'fal',
    displayName: 'FLUX.2 [pro] Outpaint',
    shortDescription: 'FLUX 2 Pro outpainting — extend image canvas',
    falModelId: 'fal-ai/flux-2-pro/outpaint',
    tasks: ['image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.06)),
    providerCostUsd: 0.06,
    fiatPriceUsd: withFiatMargin(0.06),
    loarPriceUsd: withLoarMargin(0.06),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'flux', 'outpaint', 'extend-canvas'],
    bestFor: 'Extending image canvas (aspect ratio change, scene extension)',
  },
  {
    id: 'flux-11-pro-ultra',
    provider: 'fal',
    displayName: 'FLUX 1.1 Pro Ultra',
    shortDescription: 'Higher-res sibling of FLUX 1.1 Pro',
    falModelId: 'fal-ai/flux-pro/v1.1-ultra',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.06)),
    providerCostUsd: 0.06,
    fiatPriceUsd: withFiatMargin(0.06),
    loarPriceUsd: withLoarMargin(0.06),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'flux', 'ultra-res'],
    bestFor: 'High-resolution premium FLUX 1.1 Pro renders',
  },

  // ── Seedream 4.x (direct ByteDance) ──────────────────────────────────
  {
    id: 'seedream-40-direct',
    provider: 'bytedance',
    displayName: 'Seedream 4.0',
    shortDescription: 'Seedream 4.0 — unified t2i + edit, up to 4K',
    bytedanceModelId: 'doubao-seedream-4-0-250828',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: false, // hidden by default — Seedream 5.0 Lite is current
    allowedPlans: [],
    tags: ['standard', 'bytedance', 'seedream', 'legacy'],
    bestFor: 'Legacy Seedream 4.0 — use Seedream 5.0 Lite instead',
  },
  {
    id: 'seedream-45-direct',
    provider: 'bytedance',
    displayName: 'Seedream 4.5',
    shortDescription: 'Better small-text + face rendering than 4.0',
    bytedanceModelId: 'doubao-seedream-4-5-251128',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'bytedance', 'seedream', 'faces', 'small-text'],
    bestFor: 'Character portraits with text/signage — better face rendering than 4.0',
  },
  {
    id: 'seedream-40-fal',
    provider: 'fal',
    displayName: 'Seedream 4.0 (FAL)',
    shortDescription: 'Seedream 4.0 via FAL',
    falModelId: 'fal-ai/bytedance/seedream/v4/text-to-image',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.03)),
    providerCostUsd: 0.03,
    fiatPriceUsd: withFiatMargin(0.03),
    loarPriceUsd: withLoarMargin(0.03),
    isEnabled: true,
    isVisibleToUsers: false,
    allowedPlans: [],
    tags: ['standard', 'bytedance', 'seedream', 'fal-passthrough', 'legacy'],
    bestFor: 'FAL passthrough fallback for Seedream 4.0',
  },
  {
    id: 'seedream-45-fal',
    provider: 'fal',
    displayName: 'Seedream 4.5 (FAL)',
    shortDescription: 'Seedream 4.5 via FAL',
    falModelId: 'fal-ai/bytedance/seedream/v4.5/text-to-image',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'bytedance', 'seedream', 'fal'],
    bestFor: 'FAL-hosted Seedream 4.5 for non-BYOK users',
  },
  {
    id: 'seedream-5-lite-fal',
    provider: 'fal',
    displayName: 'Seedream 5.0 Lite (FAL T2I)',
    shortDescription: 'Seedream 5.0 Lite via FAL',
    falModelId: 'fal-ai/bytedance/seedream/v5/lite/text-to-image',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.035)),
    providerCostUsd: 0.035,
    fiatPriceUsd: withFiatMargin(0.035),
    loarPriceUsd: withLoarMargin(0.035),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'bytedance', 'seedream', 'lite', 'fal'],
    bestFor: 'Seedream 5.0 Lite t2i (FAL passthrough)',
  },

  // ── Google Imagen 4 family ───────────────────────────────────────────
  {
    id: 'imagen-4-fast',
    provider: 'google',
    displayName: 'Imagen 4 Fast',
    shortDescription: 'Cheapest Imagen 4 tier — text-to-image',
    googleModelId: 'imagen-4.0-fast-generate-001',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.02)),
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'google', 'imagen', 'fast', 'ga'],
    bestFor: 'Fast cheap Imagen 4 drafts',
  },
  {
    id: 'imagen-4',
    provider: 'google',
    displayName: 'Imagen 4',
    shortDescription: 'Google Imagen 4 standard tier',
    googleModelId: 'imagen-4.0-generate-001',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'google', 'imagen', 'ga'],
    bestFor: 'Standard Imagen 4 quality',
  },
  {
    id: 'imagen-4-ultra',
    provider: 'google',
    displayName: 'Imagen 4 Ultra',
    shortDescription: 'Top-tier Imagen 4',
    googleModelId: 'imagen-4.0-ultra-generate-001',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.06)),
    providerCostUsd: 0.06,
    fiatPriceUsd: withFiatMargin(0.06),
    loarPriceUsd: withLoarMargin(0.06),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'google', 'imagen', 'ultra', 'ga'],
    bestFor: 'Best Imagen 4 quality for hero renders',
  },

  // ── OpenAI direct ────────────────────────────────────────────────────
  {
    id: 'gpt-image-1',
    provider: 'openai',
    displayName: 'GPT Image 1',
    shortDescription: 'OpenAI gpt-image-1 — generate + edit',
    openaiModelId: 'gpt-image-1',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: false,
    creditCostPerImage: usdToLoar(withFiatMargin(0.042)),
    providerCostUsd: 0.042,
    fiatPriceUsd: withFiatMargin(0.042),
    loarPriceUsd: withLoarMargin(0.042),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'generate', 'edit'],
    bestFor: 'OpenAI image gen with strong prompt adherence + edit support',
  },
  {
    id: 'gpt-image-1-mini',
    provider: 'openai',
    displayName: 'GPT Image 1 Mini',
    shortDescription: 'Cheaper tier of gpt-image-1',
    openaiModelId: 'gpt-image-1-mini',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: false,
    creditCostPerImage: usdToLoar(withFiatMargin(0.011)),
    providerCostUsd: 0.011,
    fiatPriceUsd: withFiatMargin(0.011),
    loarPriceUsd: withLoarMargin(0.011),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'openai', 'budget'],
    bestFor: 'Cheap OpenAI image gen at the standard tier',
  },
  {
    id: 'gpt-image-15',
    provider: 'openai',
    displayName: 'GPT Image 1.5',
    shortDescription: 'Latest OpenAI image flagship',
    openaiModelId: 'gpt-image-1.5',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: false,
    creditCostPerImage: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'latest'],
    bestFor: 'Latest OpenAI flagship — best prompt adherence + edit',
  },
  {
    id: 'dall-e-3',
    provider: 'openai',
    displayName: 'DALL·E 3',
    shortDescription: 'Legacy OpenAI flagship — generate only',
    openaiModelId: 'dall-e-3',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 1,
    supportedSizes: ['square_hd', 'square', 'portrait_16_9', 'landscape_16_9'],
    supportsNegativePrompt: false,
    supportsSeed: false,
    creditCostPerImage: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: false, // hidden — gpt-image-1.5 supersedes
    allowedPlans: [],
    tags: ['premium', 'openai', 'legacy'],
    bestFor: 'Legacy DALL·E 3 parity — prefer gpt-image-1.5 for new code',
  },
  {
    id: 'gpt-image-2-fal',
    provider: 'fal',
    displayName: 'GPT Image 2 (via FAL)',
    shortDescription: 'OpenAI gpt-image successor via FAL hosting',
    falModelId: 'openai/gpt-image-2',
    tasks: ['text_to_image', 'image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: false,
    creditCostPerImage: usdToLoar(withFiatMargin(0.1)),
    providerCostUsd: 0.1,
    fiatPriceUsd: withFiatMargin(0.1),
    loarPriceUsd: withLoarMargin(0.1),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'gpt-image-2', 'fal'],
    bestFor: 'gpt-image-2 quality without managing an OpenAI key',
  },

  // ── Z.AI / Zhipu image additions ─────────────────────────────────────
  {
    id: 'cogview-4',
    provider: 'zai',
    displayName: 'CogView-4 (Z.AI)',
    shortDescription: 'CogView 4 — strong Chinese-text rendering, prompt-faithful',
    zaiModelId: 'cogview-4-250304',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    maxImages: 1,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: false,
    creditCostPerImage: usdToLoar(withFiatMargin(0.02)),
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'zai', 'cogview', 'chinese-text', 'cinematic'],
    bestFor: 'Chinese-text-heavy prompts, calligraphy, East-Asian aesthetics',
  },

  // ── xAI Grok Imagine ─────────────────────────────────────────────────
  {
    id: 'grok-imagine-image',
    provider: 'fal',
    displayName: 'Grok Imagine Image',
    shortDescription: 'xAI Grok image generation',
    falModelId: 'xai/grok-imagine-image',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'xai', 'grok', 'imagine'],
    bestFor: 'xAI Grok image gen with Grok prompt-style',
  },
  {
    id: 'grok-imagine-edit',
    provider: 'fal',
    displayName: 'Grok Imagine Edit',
    shortDescription: 'Image-to-image edit via Grok Imagine',
    falModelId: 'fal-ai/xai/grok-imagine-image/edit',
    tasks: ['image_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'xai', 'grok', 'edit'],
    bestFor: 'Grok-style image editing',
  },

  // ── Z-Image Turbo (fast) ─────────────────────────────────────────────
  {
    id: 'z-image-turbo',
    provider: 'fal',
    displayName: 'Z-Image Turbo',
    shortDescription: 'Fast Z-Image — cheap draft tier',
    falModelId: 'fal-ai/z-image/turbo',
    tasks: ['text_to_image'],
    qualityTier: 'draft',
    speedTier: 'fast',
    priceTier: 'low',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.005)),
    providerCostUsd: 0.005,
    fiatPriceUsd: withFiatMargin(0.005),
    loarPriceUsd: withLoarMargin(0.005),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['draft', 'fast', 'z-image', 'turbo', 'budget'],
    bestFor: 'Cheapest fastest drafts — single-image previews',
  },

  // ── Ideogram extras (transparent, reframe, replace-bg, upscale) ─────
  {
    id: 'ideogram-v3-transparent',
    provider: 'fal',
    displayName: 'Ideogram V3 Transparent',
    shortDescription: 'Alpha-channel image output',
    falModelId: 'fal-ai/ideogram/v3/generate-transparent',
    tasks: ['text_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.1)),
    providerCostUsd: 0.1,
    fiatPriceUsd: withFiatMargin(0.1),
    loarPriceUsd: withLoarMargin(0.1),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'ideogram', 'transparent', 'alpha'],
    bestFor: 'Logos, stickers, alpha overlays',
  },
  {
    id: 'ideogram-v3-reframe',
    provider: 'fal',
    displayName: 'Ideogram V3 Reframe',
    shortDescription: 'Outpaint/reframe via Ideogram',
    falModelId: 'fal-ai/ideogram/v3/reframe',
    tasks: ['image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    maxImages: 4,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: true,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'ideogram', 'reframe', 'outpaint'],
    bestFor: 'Reframing existing images while preserving subject',
  },

  // ── Bria FIBO (editing-ish but classified as image edit) ─────────────
  {
    id: 'bria-fibo-edit',
    provider: 'fal',
    displayName: 'Bria FIBO Edit',
    shortDescription: 'JSON/mask/image-conditioned image editing',
    falModelId: 'bria/fibo-edit/edit',
    tasks: ['image_to_image'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    maxImages: 1,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: true,
    creditCostPerImage: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'bria', 'fibo', 'edit', 'mask'],
    bestFor: 'Structured image editing with JSON/mask/image conditioning',
  },

  // ── Original glm-image kept below ────────────────────────────────────
  {
    id: 'glm-image',
    provider: 'zai',
    displayName: 'GLM-Image (Z.AI)',
    shortDescription: 'Z.AI flagship image model — strong prompt adherence, broad subject coverage',
    zaiModelId: 'glm-image',
    tasks: ['text_to_image'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    maxImages: 1,
    supportedSizes: [
      'square_hd',
      'square',
      'portrait_4_3',
      'portrait_16_9',
      'landscape_4_3',
      'landscape_16_9',
    ],
    supportsNegativePrompt: false,
    supportsSeed: false,
    creditCostPerImage: usdToLoar(withFiatMargin(0.015)),
    providerCostUsd: 0.015,
    fiatPriceUsd: withFiatMargin(0.015),
    loarPriceUsd: withLoarMargin(0.015),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'zai', 'glm', 'cinematic'],
    bestFor: 'Cinematic stills, prompt-faithful renders, East-Asian aesthetics',
  },
];

// ── Lookup Helpers ────────────────────────────────────────────────────

const modelsById = new Map(IMAGE_MODELS.map((m) => [m.id, m]));

export function getImageModelById(id: string): ImageModelConfig | undefined {
  return modelsById.get(id);
}

export function getEnabledImageModels(): ImageModelConfig[] {
  return IMAGE_MODELS.filter((m) => m.isEnabled);
}

export function getVisibleImageModels(): ImageModelConfig[] {
  return IMAGE_MODELS.filter((m) => m.isEnabled && m.isVisibleToUsers);
}

export function getImageModelsForTask(task: ImageGenerationTask): ImageModelConfig[] {
  return getVisibleImageModels().filter((m) => m.tasks.includes(task));
}

export function getImageModelIds(): string[] {
  return IMAGE_MODELS.map((m) => m.id);
}
