/**
 * Outpaint / Reframe / Pan / Zoom-out Router
 *
 * Expands an existing image beyond its original boundaries for posters,
 * episode covers, widescreen shots, and social crops. The source image is
 * passed as inline data to nano-banana-pro-preview (Google Gemini) with a
 * structured prompt describing the target aspect, anchor, zoom factor, and
 * mode (preserve vs creative).
 *
 * The new canvas is generated by the model — there is no mask compositing
 * on our side. The model handles seamless blending natively.
 *
 * Flow mirrors image.generate: credit deduction → dispatch → auto-publish
 * to gallery → persist to permanent storage. On any failure credits are
 * refunded.
 */
import { randomUUID } from 'crypto';
import { z } from 'zod';
import { TRPCError } from '@trpc/server';
import { FieldValue } from 'firebase-admin/firestore';

import { router, protectedProcedure, publicProcedure, requirePermission } from '../../lib/trpc';
import { db } from '../../lib/firebase';
import { googleImagenService } from '../../services/google-imagen';
import { falService } from '../../services/fal';
import { getStorageManager } from '../../services/storage';
import { signWithProvenance } from '../../services/provenance';
import { publishToGallery } from '../../lib/gallery-publish';
import { sanitizePrompt } from '../../lib/prompt-sanitize';
import { logFailedRefund } from '../../lib/refund-audit';
import { reserveClientToken } from '../../lib/jobIdempotency';
import { fireJobWebhook, validateWebhookUrl, webhookUrlSchema } from '../../lib/webhooks';
import { getImageModelById } from '../../services/image-models';

// ── Schemas ────────────────────────────────────────────────────────────

export const TARGET_ASPECTS = ['1:1', '4:5', '16:9', '9:16', '21:9'] as const;
export type OutpaintAspect = (typeof TARGET_ASPECTS)[number];

const expandSchema = z.object({
  sourceImageUrl: z.string().url(),
  targetAspect: z.enum(TARGET_ASPECTS),
  /** 0 = source pinned to left, 0.5 = centered, 1 = pinned to right */
  anchorX: z.number().min(0).max(1).default(0.5),
  /** 0 = top, 0.5 = centered, 1 = bottom */
  anchorY: z.number().min(0).max(1).default(0.5),
  /** 1 = source fills target, >1 = zoomed out (source shrinks, more canvas fills in) */
  zoomFactor: z.number().min(1).max(4).default(1),
  mode: z.enum(['preserve', 'creative']).default('preserve'),
  prompt: z.string().max(1000).default(''),
  negativePrompt: z.string().max(500).optional(),
  universeId: z.string().optional(),
  entityId: z.string().optional(),
  clientToken: z
    .string()
    .min(16)
    .max(128)
    .regex(/^[A-Za-z0-9_-]+$/, 'clientToken must match [A-Za-z0-9_-]{16,128}')
    .optional(),
  webhookUrl: webhookUrlSchema.optional(),
});

type ExpandInput = z.infer<typeof expandSchema>;

// ── Pricing ────────────────────────────────────────────────────────────
//
// Outpainting is a single image-to-image call to nano-banana-pro-preview.
// We price it at parity with the `nano-banana-2` registry entry so users
// who understand the image.generate costs see a familiar number.

const OUTPAINT_MODEL_ID = 'nano-banana-2';

function resolveModel() {
  const model = getImageModelById(OUTPAINT_MODEL_ID);
  if (!model) throw new Error(`Outpaint model "${OUTPAINT_MODEL_ID}" missing from registry`);
  return model;
}

// ── Prompt construction ────────────────────────────────────────────────

function describeAnchor(anchorX: number, anchorY: number): string {
  const x = anchorX < 0.33 ? 'left' : anchorX > 0.66 ? 'right' : 'horizontally centered';
  const y = anchorY < 0.33 ? 'top' : anchorY > 0.66 ? 'bottom' : 'vertically centered';
  if (x === 'horizontally centered' && y === 'vertically centered') return 'centered';
  return `anchored to the ${y}-${x}`
    .replace('horizontally centered-', '')
    .replace('-vertically centered', '');
}

function buildOutpaintPrompt(input: ExpandInput): string {
  const { targetAspect, anchorX, anchorY, zoomFactor, mode, prompt } = input;
  const anchor = describeAnchor(anchorX, anchorY);
  const zoom =
    zoomFactor <= 1.05
      ? 'fits the new canvas edge-to-edge'
      : zoomFactor < 1.6
        ? `is zoomed out ~${zoomFactor.toFixed(1)}x, leaving room around it to be filled in`
        : `is zoomed out ${zoomFactor.toFixed(1)}x — the original occupies the center region and new background fills the rest`;

  const intent =
    mode === 'preserve'
      ? 'Preserve the original subject, composition, and style exactly. Extend the scene outward by generating new content that seamlessly continues the existing environment, lighting, perspective, and color grading. Do not alter the original region.'
      : 'Use the original image as creative inspiration for the center region. Extend outward with new scenery that matches the overall mood and tone, but you may enrich details and add cinematic elements consistent with the user guidance.';

  const guidance = prompt.trim() ? `User guidance for the expanded regions: ${prompt.trim()}` : '';

  return [
    `Reframe this image to a ${targetAspect} aspect ratio.`,
    `The original image ${anchor} within the new canvas and ${zoom}.`,
    intent,
    guidance,
    'The result must be a single cohesive image with seamless blending at the original boundaries — no visible seams, no duplicated subjects, no text overlays, no watermarks.',
  ]
    .filter(Boolean)
    .join(' ');
}

// ── Source image fetch ────────────────────────────────────────────────

async function fetchAsInlineImage(url: string): Promise<{ base64: string; mimeType: string }> {
  const { validateUploadUrl } = await import('../../lib/url-validator');
  await validateUploadUrl(url);
  const response = await fetch(url, { redirect: 'error' });
  if (!response.ok) {
    throw new Error(`Failed to fetch source image (${response.status})`);
  }
  const contentType = response.headers.get('content-type') || '';
  const mimeType = contentType.startsWith('image/')
    ? contentType.split(';')[0].trim()
    : url.match(/\.jpe?g(?:[?#]|$)/i)
      ? 'image/jpeg'
      : 'image/png';
  const buf = Buffer.from(new Uint8Array(await response.arrayBuffer()));
  if (buf.length === 0) throw new Error('Source image is empty');
  if (buf.length > 20 * 1024 * 1024) {
    throw new Error('Source image exceeds 20MB — use a smaller image');
  }
  return { base64: buf.toString('base64'), mimeType };
}

// ── Provider dispatch ─────────────────────────────────────────────────

interface DispatchOk {
  status: 'ok';
  imageUrl: string;
  provider: 'google' | 'fal';
}
interface DispatchErr {
  status: 'error';
  error: string;
}
type DispatchResult = DispatchOk | DispatchErr;

async function dispatchOutpaint(opts: {
  prompt: string;
  negativePrompt?: string;
  source: { base64: string; mimeType: string };
  sourceUrl: string;
  userId: string;
  jobId: string;
}): Promise<DispatchResult> {
  // Primary: nano-banana-pro-preview (Gemini endpoint supports inline image input)
  if (googleImagenService.isConfigured()) {
    try {
      const result = await googleImagenService.generate({
        prompt: opts.prompt,
        negativePrompt: opts.negativePrompt,
        numberOfImages: 1,
        model: 'nano-banana-pro-preview',
        inputImages: [opts.source],
      });

      const img = result.images[0];
      if (!img) return { status: 'error', error: 'Google returned no image' };

      const buffer = Buffer.from(img.base64, 'base64');
      const filename = `outpaint-${opts.jobId}.png`;
      const signed = await signWithProvenance(buffer, filename, {
        model: 'nano-banana-pro-preview',
        prompt: opts.prompt,
        generatedAt: new Date().toISOString(),
        mimeType: img.mimeType || 'image/png',
      });
      const manifest = await getStorageManager().upload(
        signed,
        filename,
        img.mimeType || 'image/png',
        opts.userId
      );
      const url = manifest.uploads[0]?.url;
      if (!url) return { status: 'error', error: 'Storage upload returned no URL' };
      return { status: 'ok', imageUrl: url, provider: 'google' };
    } catch (err) {
      console.error('[outpaint] google dispatch failed, trying fal fallback:', err);
      // fall through to fal
    }
  }

  // Fallback: FAL kontext (image-to-image that respects source composition)
  if (process.env.FAL_KEY) {
    try {
      const result = await falService.imageToImage({
        prompt: opts.prompt,
        imageUrls: [opts.sourceUrl],
        numImages: 1,
      });
      const url = result.images?.[0]?.url || result.imageUrl;
      if (!url) return { status: 'error', error: result.error || 'FAL returned no image' };
      return { status: 'ok', imageUrl: url, provider: 'fal' };
    } catch (err) {
      return {
        status: 'error',
        error: err instanceof Error ? err.message : 'FAL fallback failed',
      };
    }
  }

  return { status: 'error', error: 'No image provider configured (GOOGLE_API_KEY or FAL_KEY)' };
}

// ── Firestore collection ──────────────────────────────────────────────

const outpaintJobsCol = () => {
  if (!db) throw new Error('Firebase is not configured');
  return db.collection('outpaintJobs');
};

// ── Router ────────────────────────────────────────────────────────────

export const outpaintRouter = router({
  estimateCost: publicProcedure.query(() => {
    const model = resolveModel();
    return {
      credits: model.creditCostPerImage,
      fiatPriceUsd: model.fiatPriceUsd,
      loarPriceUsd: model.loarPriceUsd,
      modelId: model.id,
      modelName: model.displayName,
    };
  }),

  expand: protectedProcedure
    .use(requirePermission('generation.image'))
    .input(expandSchema)
    .mutation(async ({ input, ctx }) => {
      if (!db) {
        throw new TRPCError({
          code: 'SERVICE_UNAVAILABLE',
          message: 'Server storage is not configured',
        });
      }

      input.prompt = sanitizePrompt(input.prompt);
      if (input.negativePrompt) input.negativePrompt = sanitizePrompt(input.negativePrompt);

      const model = resolveModel();
      const cost = model.creditCostPerImage;
      const jobId = randomUUID();

      // Idempotency check before any credit deduction.
      if (input.clientToken) {
        const reservation = await reserveClientToken({
          ownerUid: ctx.user.uid,
          clientToken: input.clientToken,
          jobId,
          procedure: 'outpaint.expand',
        });
        if (reservation?.existing) {
          const existing = await outpaintJobsCol().doc(reservation.existing.jobId).get();
          const d = existing.exists ? (existing.data() as any) : {};
          return {
            jobId: reservation.existing.jobId,
            status: 'completed' as const,
            imageUrl: (d.outputImageUrl ?? d.imageUrl ?? null) as string | null,
            provider: (d.provider ?? 'unknown') as string,
            targetAspect: (d.targetAspect ?? input.targetAspect) as typeof input.targetAspect,
            creditsCharged: (d.creditsCharged ?? 0) as number,
            idempotentReplay: true as const,
          };
        }
      }

      // Validate webhookUrl.
      let validatedWebhookUrl: string | undefined;
      if (input.webhookUrl) {
        const check = validateWebhookUrl(input.webhookUrl);
        if (!check.ok) {
          throw new TRPCError({ code: 'BAD_REQUEST', message: check.reason });
        }
        validatedWebhookUrl = check.url;
      }

      const startTime = Date.now();

      // ── Persist initial record ────────────────────────────────────────
      await outpaintJobsCol()
        .doc(jobId)
        .set({
          id: jobId,
          userId: ctx.user.uid,
          status: 'queued',
          sourceImageUrl: input.sourceImageUrl,
          targetAspect: input.targetAspect,
          anchorX: input.anchorX,
          anchorY: input.anchorY,
          zoomFactor: input.zoomFactor,
          mode: input.mode,
          prompt: input.prompt,
          negativePrompt: input.negativePrompt ?? null,
          universeId: input.universeId ?? null,
          entityId: input.entityId ?? null,
          modelId: model.id,
          creditsCharged: cost,
          providerCostUsd: model.providerCostUsd,
          fiatPriceUsd: model.fiatPriceUsd,
          createdAt: new Date(),
          ...(validatedWebhookUrl ? { webhookUrl: validatedWebhookUrl } : {}),
          ...(input.clientToken ? { clientToken: input.clientToken } : {}),
        });

      // ── Deduct credits (atomic) ───────────────────────────────────────
      const userCreditsRef = db.collection('userCredits').doc(ctx.user.uid);
      let insufficient = false;
      try {
        await db.runTransaction(async (tx) => {
          const doc = await tx.get(userCreditsRef);
          const balance = doc.exists ? doc.data()?.balance || 0 : 0;
          if (balance < cost) {
            insufficient = true;
            throw new Error(
              `Insufficient credits. Need ${cost}, have ${balance}. Purchase more credits to continue.`
            );
          }
          tx.update(userCreditsRef, {
            balance: balance - cost,
            totalSpent: (doc.data()?.totalSpent || 0) + cost,
            updatedAt: new Date(),
          });
        });
      } catch (err) {
        const message = err instanceof Error ? err.message : 'Credit deduction failed';
        await outpaintJobsCol()
          .doc(jobId)
          .update({ status: 'failed', failureReason: message, completedAt: new Date() });
        if (insufficient) throw new TRPCError({ code: 'PRECONDITION_FAILED', message });
        throw new TRPCError({ code: 'INTERNAL_SERVER_ERROR', message });
      }

      // ── Generate ──────────────────────────────────────────────────────
      try {
        await outpaintJobsCol().doc(jobId).update({ status: 'running' });

        const source = await fetchAsInlineImage(input.sourceImageUrl);
        const composed = buildOutpaintPrompt(input);

        const result = await dispatchOutpaint({
          prompt: composed,
          negativePrompt: input.negativePrompt,
          source,
          sourceUrl: input.sourceImageUrl,
          userId: ctx.user.uid,
          jobId,
        });

        if (result.status !== 'ok') {
          // Refund on failure
          try {
            await userCreditsRef.update({
              balance: FieldValue.increment(cost),
              totalSpent: FieldValue.increment(-cost),
              updatedAt: new Date(),
            });
          } catch (refundErr) {
            logFailedRefund({
              userId: ctx.user.uid,
              credits: cost,
              source: 'outpaint.expand',
              generationId: jobId,
              error: refundErr instanceof Error ? refundErr.message : 'Unknown',
            });
          }
          await outpaintJobsCol()
            .doc(jobId)
            .update({
              status: 'failed',
              creditsRefunded: true,
              failureReason: result.error,
              latencyMs: Date.now() - startTime,
              completedAt: new Date(),
            });
          const isConfig = /API_KEY|FAL_KEY|GOOGLE_API_KEY|not configured/i.test(result.error);
          throw new TRPCError({
            code: isConfig ? 'SERVICE_UNAVAILABLE' : 'INTERNAL_SERVER_ERROR',
            message: result.error,
          });
        }

        await outpaintJobsCol()
          .doc(jobId)
          .update({
            status: 'completed',
            outputImageUrl: result.imageUrl,
            provider: result.provider,
            latencyMs: Date.now() - startTime,
            completedAt: new Date(),
          });

        // Fire-and-forget: auto-publish to gallery
        publishToGallery({
          creatorUid: ctx.user.uid,
          mediaUrl: result.imageUrl,
          thumbnailUrl: result.imageUrl,
          mediaType: 'ai-image',
          title: input.prompt.slice(0, 100) || `Reframed to ${input.targetAspect}`,
          description:
            input.prompt ||
            `Outpainted from ${input.sourceImageUrl} to ${input.targetAspect} (${input.mode})`,
          universeId: input.universeId ?? null,
          generationId: jobId,
          generationModel: `outpaint:${result.provider}`,
          tags: ['outpaint', 'reframe', input.targetAspect, input.mode],
          sourceImageUrl: input.sourceImageUrl,
        }).catch((err) => console.error('[outpaint] gallery publish failed:', err?.message || err));

        fireJobWebhook({
          ownerUid: ctx.user.uid,
          webhookUrl: validatedWebhookUrl,
          clientToken: input.clientToken,
          event: 'job.completed',
          jobId,
          kind: 'image',
          payload: {
            operation: 'outpaint',
            status: 'completed',
            resultUrl: result.imageUrl,
            provider: result.provider,
            targetAspect: input.targetAspect,
            creditsCharged: cost,
          },
        });

        return {
          jobId,
          status: 'completed' as const,
          imageUrl: result.imageUrl as string | null,
          provider: result.provider,
          targetAspect: input.targetAspect,
          creditsCharged: cost,
          idempotentReplay: false as const,
        };
      } catch (error) {
        // Blanket catch: refund if we haven't already
        const latencyMs = Date.now() - startTime;
        const errorMessage = error instanceof Error ? error.message : 'Unknown error';

        const doc = await outpaintJobsCol().doc(jobId).get();
        const alreadyRefunded = doc.exists && doc.data()?.creditsRefunded === true;
        if (!alreadyRefunded) {
          try {
            await userCreditsRef.update({
              balance: FieldValue.increment(cost),
              totalSpent: FieldValue.increment(-cost),
              updatedAt: new Date(),
            });
          } catch (refundErr) {
            logFailedRefund({
              userId: ctx.user.uid,
              credits: cost,
              source: 'outpaint.expand',
              generationId: jobId,
              error: refundErr instanceof Error ? refundErr.message : 'Unknown',
            });
          }
          await outpaintJobsCol().doc(jobId).update({
            status: 'failed',
            creditsRefunded: true,
            failureReason: errorMessage,
            latencyMs,
            completedAt: new Date(),
          });
        }
        fireJobWebhook({
          ownerUid: ctx.user.uid,
          webhookUrl: validatedWebhookUrl,
          clientToken: input.clientToken,
          event: 'job.failed',
          jobId,
          kind: 'image',
          payload: {
            operation: 'outpaint',
            status: 'failed',
            errorMessage,
            creditsRefunded: !alreadyRefunded,
          },
        });
        throw error;
      }
    }),

  history: protectedProcedure
    .input(z.object({ limit: z.number().min(1).max(50).default(20) }))
    .query(async ({ input, ctx }) => {
      const snap = await outpaintJobsCol()
        .where('userId', '==', ctx.user.uid)
        .orderBy('createdAt', 'desc')
        .limit(input.limit)
        .get();
      return snap.docs.map((d) => ({ id: d.id, ...d.data() }));
    }),
});
