/**
 * Video Model Registry — Central source of truth for all supported video generation models.
 *
 * Dual-margin pricing model:
 * - providerCostUsd = what we pay the AI provider (FAL) per generation
 * - userPriceUsd = providerCostUsd * 1.35 (35% margin for card/crypto)
 * - loarPriceUsd = providerCostUsd * 1.25 (25% margin for $LOAR payments)
 * - creditCost = internal credits (1 credit ≈ provider cost, margin on purchase)
 *
 * Users buy credits with either:
 *   Card / ETH / other crypto → 35% margin
 *   $LOAR token → 25% margin (+ 10% bonus credits)
 */
import type { VideoModelConfig, VideoGenerationMode } from './types';

/** Margin for credit card / ETH / other crypto purchases */
export const FIAT_MARGIN = 1.35;

/** Margin for $LOAR token purchases (incentivized) */
export const LOAR_MARGIN = 1.25;

/** $LOAR token to USD conversion rate (1 $LOAR = $0.01) */
export const LOAR_TO_USD = 0.01;

/** Calculate user price from provider cost at fiat margin */
function withFiatMargin(providerCost: number): number {
  return Math.round(providerCost * FIAT_MARGIN * 100) / 100;
}

/** Calculate user price from provider cost at $LOAR margin */
function withLoarMargin(providerCost: number): number {
  return Math.round(providerCost * LOAR_MARGIN * 100) / 100;
}

/** Calculate $LOAR tokens from USD price */
function usdToLoar(usd: number): number {
  return Math.ceil(usd / LOAR_TO_USD);
}

export const VIDEO_MODELS: VideoModelConfig[] = [
  // ── Draft / Fast / Cheap ────────────────────────────────────────────
  {
    id: 'ltx-video',
    provider: 'fal',
    displayName: 'LTX Video',
    shortDescription: 'Cheapest drafts, fast previews',
    falModelId: 'fal-ai/ltx-video',
    mode: ['text_to_video'],
    qualityTier: 'draft',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 5,
    supportedDurations: [5],
    supportedAspectRatios: ['16:9'],
    supportedResolutions: ['512p'],
    creditCost: usdToLoar(withFiatMargin(0.02)),
    providerCostUsd: 0.02,
    fiatPriceUsd: withFiatMargin(0.02),
    loarPriceUsd: withLoarMargin(0.02), // $0.03
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['draft', 'fast', 'cheap', 'preview'],
    bestFor: 'Quick previews and drafts',
  },
  {
    id: 'hunyuan',
    provider: 'fal',
    displayName: 'HunYuan Video',
    shortDescription: 'Budget text-to-video',
    falModelId: 'fal-ai/hunyuan-video',
    mode: ['text_to_video'],
    qualityTier: 'draft',
    speedTier: 'medium',
    priceTier: 'low',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 5,
    supportedDurations: [5],
    supportedAspectRatios: ['16:9'],
    supportedResolutions: ['512p'],
    creditCost: usdToLoar(withFiatMargin(0.04)),
    providerCostUsd: 0.04,
    fiatPriceUsd: withFiatMargin(0.04),
    loarPriceUsd: withLoarMargin(0.04),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['draft', 'budget'],
    bestFor: 'Budget text-to-video generation',
  },

  // ── Standard / Balanced ─────────────────────────────────────────────
  {
    id: 'wan25-t2v',
    provider: 'fal',
    displayName: 'Wan 2.5',
    shortDescription: 'Good quality, prompt expansion',
    falModelId: 'fal-ai/wan-25-preview/text-to-video',
    mode: ['text_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'balanced', 'prompt-expansion'],
    bestFor: 'Balanced quality with prompt expansion',
  },
  {
    id: 'wan25-i2v',
    provider: 'fal',
    displayName: 'Wan 2.5',
    shortDescription: 'Good quality image animation',
    falModelId: 'fal-ai/wan-25-preview/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'balanced', 'image-animation'],
    bestFor: 'Balanced quality image animation',
  },
  {
    id: 'kling-t2v',
    provider: 'fal',
    displayName: 'Kling 2.5 Turbo',
    shortDescription: 'Fast, balanced quality and speed',
    falModelId: 'fal-ai/kling-video/v2.5-turbo/pro/text-to-video',
    mode: ['text_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.1)),
    providerCostUsd: 0.1,
    fiatPriceUsd: withFiatMargin(0.1),
    loarPriceUsd: withLoarMargin(0.1),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'turbo'],
    bestFor: 'Fast, balanced quality and speed',
  },
  {
    id: 'kling-i2v',
    provider: 'fal',
    displayName: 'Kling 2.5 Turbo',
    shortDescription: 'Fast image-to-video animation',
    falModelId: 'fal-ai/kling-video/v2.5-turbo/pro/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.1)),
    providerCostUsd: 0.1,
    fiatPriceUsd: withFiatMargin(0.1),
    loarPriceUsd: withLoarMargin(0.1),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'turbo', 'image-animation'],
    bestFor: 'Fast image-to-video animation',
  },
  {
    id: 'cogvideox',
    provider: 'fal',
    displayName: 'CogVideoX-5B',
    shortDescription: 'Open-source standard model',
    falModelId: 'fal-ai/cogvideox-5b',
    mode: ['text_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 5,
    supportedDurations: [5],
    supportedAspectRatios: ['16:9'],
    supportedResolutions: ['512p'],
    creditCost: usdToLoar(withFiatMargin(0.05)),
    providerCostUsd: 0.05,
    fiatPriceUsd: withFiatMargin(0.05),
    loarPriceUsd: withLoarMargin(0.05),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'open-source'],
    bestFor: 'Open-source standard quality',
  },

  // ── Premium / High Quality ──────────────────────────────────────────
  {
    id: 'veo31-t2v',
    provider: 'fal',
    displayName: 'Veo 3.1 Fast',
    shortDescription: 'Premium cinematic with audio',
    falModelId: 'fal-ai/veo3.1/fast',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [8],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.25)),
    providerCostUsd: 0.25,
    fiatPriceUsd: withFiatMargin(0.25),
    loarPriceUsd: withLoarMargin(0.25),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'cinematic', 'audio', 'google'],
    bestFor: 'Premium cinematic video with audio',
  },
  {
    id: 'veo31-i2v',
    provider: 'fal',
    displayName: 'Veo 3.1 Fast',
    shortDescription: 'Premium image animation with audio',
    falModelId: 'fal-ai/veo3.1/fast/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [8],
    supportedAspectRatios: ['16:9', '9:16', '1:1', 'auto'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.25)),
    providerCostUsd: 0.25,
    fiatPriceUsd: withFiatMargin(0.25),
    loarPriceUsd: withLoarMargin(0.25),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'cinematic', 'audio', 'google', 'image-animation'],
    bestFor: 'Premium image animation with audio',
  },
  {
    id: 'sora2-t2v',
    provider: 'fal',
    displayName: 'Sora 2',
    shortDescription: 'OpenAI premium, strict aspect ratios',
    falModelId: 'fal-ai/sora-2/text-to-video',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 12,
    supportedDurations: [4, 8, 12],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p'],
    creditCost: usdToLoar(withFiatMargin(0.3)),
    providerCostUsd: 0.3,
    fiatPriceUsd: withFiatMargin(0.3),
    loarPriceUsd: withLoarMargin(0.3),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'strict-aspect-ratio'],
    bestFor: 'OpenAI premium quality (16:9 or 9:16 only)',
  },
  {
    id: 'sora2-i2v',
    provider: 'fal',
    displayName: 'Sora 2',
    shortDescription: 'OpenAI premium image animation',
    falModelId: 'fal-ai/sora-2/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 12,
    supportedDurations: [4, 8, 12],
    supportedAspectRatios: ['16:9', '9:16', 'auto'],
    supportedResolutions: ['720p', 'auto'],
    creditCost: usdToLoar(withFiatMargin(0.3)),
    providerCostUsd: 0.3,
    fiatPriceUsd: withFiatMargin(0.3),
    loarPriceUsd: withLoarMargin(0.3),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'image-animation'],
    bestFor: 'OpenAI premium image animation',
  },
  // ── Seedance 2.0 (ByteDance Direct API — $0 provider cost) ──────────
  {
    id: 'seedance2-t2v',
    provider: 'bytedance',
    displayName: 'Seedance 2.0',
    shortDescription: 'Cinematic video with native audio',
    falModelId: 'bytedance/seedance-2.0/text-to-video', // kept for legacy compat
    bytedanceModelId: 'dreamina-seedance-2-0-260128',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    supportedAspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    supportedResolutions: ['480p', '720p'],
    creditCost: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'cinematic', 'audio', 'bytedance', 'seedance', 'free'],
    bestFor: 'Cinematic video with native audio, multi-shot cuts, realistic physics',
  },
  {
    id: 'seedance2-i2v',
    provider: 'bytedance',
    displayName: 'Seedance 2.0',
    shortDescription: 'Cinematic image animation with audio',
    falModelId: 'bytedance/seedance-2.0/image-to-video',
    bytedanceModelId: 'dreamina-seedance-2-0-260128',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    supportedAspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    supportedResolutions: ['480p', '720p'],
    creditCost: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'cinematic', 'audio', 'bytedance', 'seedance', 'image-animation', 'free'],
    bestFor: 'Cinematic image animation with native audio and end-frame control',
  },
  {
    id: 'seedance2-fast-t2v',
    provider: 'bytedance',
    displayName: 'Seedance 2.0 Fast',
    shortDescription: 'Fast cinematic video with audio',
    falModelId: 'bytedance/seedance-2.0/fast/text-to-video',
    bytedanceModelId: 'dreamina-seedance-2-0-fast-260128',
    mode: ['text_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    supportedAspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    supportedResolutions: ['480p', '720p'],
    creditCost: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'audio', 'bytedance', 'seedance', 'free'],
    bestFor: 'Fast cinematic video with audio for production workloads',
  },
  {
    id: 'seedance2-fast-i2v',
    provider: 'bytedance',
    displayName: 'Seedance 2.0 Fast',
    shortDescription: 'Fast image animation with audio',
    falModelId: 'bytedance/seedance-2.0/fast/image-to-video',
    bytedanceModelId: 'dreamina-seedance-2-0-fast-260128',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    supportedAspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    supportedResolutions: ['480p', '720p'],
    creditCost: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'audio', 'bytedance', 'seedance', 'image-animation', 'free'],
    bestFor: 'Fast image animation with audio and end-frame control',
  },

  // ── Seedance 2.0 Reference-to-Video (ByteDance Direct) ─────────────
  {
    id: 'seedance2-ref',
    provider: 'bytedance',
    displayName: 'Seedance 2.0 Reference',
    shortDescription: 'Character-consistent video from reference image',
    falModelId: 'bytedance/seedance-2.0/reference-to-video',
    bytedanceModelId: 'dreamina-seedance-2-0-260128',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    supportedAspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    supportedResolutions: ['480p', '720p'],
    creditCost: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: [
      'premium',
      'cinematic',
      'audio',
      'bytedance',
      'seedance',
      'reference',
      'character-consistent',
      'free',
    ],
    bestFor: 'Character-consistent video generation from reference images',
  },
  {
    id: 'seedance2-fast-ref',
    provider: 'bytedance',
    displayName: 'Seedance 2.0 Fast Reference',
    shortDescription: 'Fast character-consistent video',
    falModelId: 'bytedance/seedance-2.0/fast/reference-to-video',
    bytedanceModelId: 'dreamina-seedance-2-0-fast-260128',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    supportedAspectRatios: ['21:9', '16:9', '4:3', '1:1', '3:4', '9:16'],
    supportedResolutions: ['480p', '720p'],
    creditCost: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'audio', 'bytedance', 'seedance', 'reference', 'free'],
    bestFor: 'Fast character-consistent video from reference images',
  },

  // ── Veo 3.1 Standard (non-fast) ───────────────────────────────────
  {
    id: 'veo31-std-t2v',
    provider: 'fal',
    displayName: 'Veo 3.1',
    shortDescription: 'Maximum quality cinematic with audio',
    falModelId: 'fal-ai/veo3.1',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [8],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.4 * 8)),
    providerCostUsd: 0.4 * 8,
    fiatPriceUsd: withFiatMargin(0.4 * 8),
    loarPriceUsd: withLoarMargin(0.4 * 8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'cinematic', 'audio', 'google', 'max-quality'],
    bestFor: 'Maximum quality cinematic video — best Veo output',
  },
  {
    id: 'veo31-std-i2v',
    provider: 'fal',
    displayName: 'Veo 3.1',
    shortDescription: 'Maximum quality image animation with audio',
    falModelId: 'fal-ai/veo3.1/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [8],
    supportedAspectRatios: ['16:9', '9:16', '1:1', 'auto'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.4 * 8)),
    providerCostUsd: 0.4 * 8,
    fiatPriceUsd: withFiatMargin(0.4 * 8),
    loarPriceUsd: withLoarMargin(0.4 * 8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'cinematic', 'audio', 'google', 'max-quality', 'image-animation'],
    bestFor: 'Maximum quality image animation with audio',
  },
  {
    id: 'veo31-lite-t2v',
    provider: 'fal',
    displayName: 'Veo 3.1 Lite',
    shortDescription: 'Budget Veo with good quality',
    falModelId: 'fal-ai/veo3.1/lite',
    mode: ['text_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 6, 8],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.05 * 8)),
    providerCostUsd: 0.05 * 8,
    fiatPriceUsd: withFiatMargin(0.05 * 8),
    loarPriceUsd: withLoarMargin(0.05 * 8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'audio', 'google', 'budget'],
    bestFor: 'Budget Veo video with decent quality and audio',
  },
  {
    id: 'veo31-lite-i2v',
    provider: 'fal',
    displayName: 'Veo 3.1 Lite',
    shortDescription: 'Budget Veo image animation',
    falModelId: 'fal-ai/veo3.1/lite/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 6, 8],
    supportedAspectRatios: ['16:9', '9:16', 'auto'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.05 * 8)),
    providerCostUsd: 0.05 * 8,
    fiatPriceUsd: withFiatMargin(0.05 * 8),
    loarPriceUsd: withLoarMargin(0.05 * 8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'audio', 'google', 'budget', 'image-animation'],
    bestFor: 'Budget Veo image animation with audio',
  },

  // ── Sora 2 Pro ─────────────────────────────────────────────────────
  {
    id: 'sora2-pro-t2v',
    provider: 'fal',
    displayName: 'Sora 2 Pro',
    shortDescription: 'Top-tier OpenAI text-to-video',
    falModelId: 'fal-ai/sora-2/text-to-video/pro',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 20,
    supportedDurations: [4, 8, 12, 16, 20],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.3 * 8)),
    providerCostUsd: 0.3 * 8,
    fiatPriceUsd: withFiatMargin(0.3 * 8),
    loarPriceUsd: withLoarMargin(0.3 * 8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'pro', 'max-quality'],
    bestFor: 'Top-tier OpenAI video quality',
  },
  {
    id: 'sora2-pro-i2v',
    provider: 'fal',
    displayName: 'Sora 2 Pro',
    shortDescription: 'Top-tier OpenAI image animation',
    falModelId: 'fal-ai/sora-2/image-to-video/pro',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 20,
    supportedDurations: [4, 8, 12, 16, 20],
    supportedAspectRatios: ['16:9', '9:16', 'auto'],
    supportedResolutions: ['720p', '1080p', 'auto'],
    creditCost: usdToLoar(withFiatMargin(0.3 * 8)),
    providerCostUsd: 0.3 * 8,
    fiatPriceUsd: withFiatMargin(0.3 * 8),
    loarPriceUsd: withLoarMargin(0.3 * 8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'pro', 'image-animation'],
    bestFor: 'Top-tier OpenAI image animation',
  },

  // ── Kling 3.0 Pro ──────────────────────────────────────────────────
  {
    id: 'kling3-i2v',
    provider: 'fal',
    displayName: 'Kling 3.0 Pro',
    shortDescription: 'Latest Kling with cinematic visuals and audio',
    falModelId: 'fal-ai/kling-video/v3/pro/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.15)),
    providerCostUsd: 0.15,
    fiatPriceUsd: withFiatMargin(0.15),
    loarPriceUsd: withLoarMargin(0.15),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'kling', 'cinematic', 'audio', 'image-animation'],
    bestFor: 'Latest Kling with cinematic visuals, fluid motion, and audio',
  },

  // ── PixVerse V6 ────────────────────────────────────────────────────
  {
    id: 'pixverse-v6-t2v',
    provider: 'fal',
    displayName: 'PixVerse V6',
    shortDescription: 'Fast, affordable video generation',
    falModelId: 'fal-ai/pixverse/v6/text-to-video',
    mode: ['text_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 8],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'pixverse', 'affordable'],
    bestFor: 'Fast and affordable text-to-video generation',
  },
  {
    id: 'pixverse-v6-i2v',
    provider: 'fal',
    displayName: 'PixVerse V6',
    shortDescription: 'Fast, affordable image animation',
    falModelId: 'fal-ai/pixverse/v6/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 8],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'fast', 'pixverse', 'affordable', 'image-animation'],
    bestFor: 'Fast and affordable image-to-video animation',
  },

  // ── WAN 2.7 ────────────────────────────────────────────────────────
  {
    id: 'wan27-t2v',
    provider: 'fal',
    displayName: 'WAN 2.7',
    shortDescription: 'Latest Alibaba text-to-video',
    falModelId: 'fal-ai/wan/v2.7/text-to-video',
    mode: ['text_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['480p', '720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.1 * 5)),
    providerCostUsd: 0.1 * 5,
    fiatPriceUsd: withFiatMargin(0.1 * 5),
    loarPriceUsd: withLoarMargin(0.1 * 5),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'alibaba', 'wan', 'balanced'],
    bestFor: 'Latest WAN model with improved quality and prompt expansion',
  },
  {
    id: 'wan27-i2v',
    provider: 'fal',
    displayName: 'WAN 2.7',
    shortDescription: 'Latest Alibaba image animation',
    falModelId: 'fal-ai/wan/v2.7/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.1 * 5)),
    providerCostUsd: 0.1 * 5,
    fiatPriceUsd: withFiatMargin(0.1 * 5),
    loarPriceUsd: withLoarMargin(0.1 * 5),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'alibaba', 'wan', 'image-animation'],
    bestFor: 'Latest WAN image-to-video animation',
  },

  // ── Runway Gen-3 ───────────────────────────────────────────────────
  {
    id: 'runway-gen3',
    provider: 'fal',
    displayName: 'Runway Gen-3',
    shortDescription: 'Runway premium generation',
    falModelId: 'fal-ai/runway-gen3',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.25)),
    providerCostUsd: 0.25,
    fiatPriceUsd: withFiatMargin(0.25),
    loarPriceUsd: withLoarMargin(0.25),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'runway'],
    bestFor: 'Runway premium text-to-video',
  },

  // ── Z.AI / Zhipu — Vidu Q1 + CogVideoX-3 ────────────────────────────
  // Live-confirmed against api.z.ai paas/v4 on 2026-04-26: `viduq1-text`,
  // `viduq1-image`, and `cogvideox-3` all accept jobs. CogVideoX-3 requires
  // duration ≥5 (rejects 2). `vidu2-*`, `viduq2-*`, and `cogvideox-2` are
  // rejected (1211 / 1214).
  {
    id: 'viduq1-t2v',
    provider: 'zai',
    displayName: 'Vidu Q1 (Z.AI)',
    shortDescription: 'Z.AI text-to-video — Vidu Q1 standard quality',
    falModelId: '',
    zaiModelId: 'viduq1-text',
    mode: ['text_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 8],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p'],
    creditCost: usdToLoar(withFiatMargin(0.16)),
    providerCostUsd: 0.16,
    fiatPriceUsd: withFiatMargin(0.16),
    loarPriceUsd: withLoarMargin(0.16),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'zai', 'vidu'],
    bestFor: 'Standard text-to-video with cinematic motion',
  },
  {
    id: 'viduq1-i2v',
    provider: 'zai',
    displayName: 'Vidu Q1 (image-to-video, Z.AI)',
    shortDescription: 'Z.AI image-conditioned video — preserves the source frame',
    falModelId: '',
    zaiModelId: 'viduq1-image',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 8],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p'],
    creditCost: usdToLoar(withFiatMargin(0.18)),
    providerCostUsd: 0.18,
    fiatPriceUsd: withFiatMargin(0.18),
    loarPriceUsd: withLoarMargin(0.18),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'zai', 'vidu', 'image-animation'],
    bestFor: 'Animate a still frame — preserves character + scene identity',
  },
  {
    id: 'cogvideox-3',
    provider: 'zai',
    displayName: 'CogVideoX-3 (Z.AI)',
    shortDescription: 'Z.AI premium video — cinematic motion + inline audio support',
    falModelId: '',
    zaiModelId: 'cogvideox-3',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: true, // CogVideoX-3 confirmed at 4K (per Z.AI docs)
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p', '4k'],
    creditCost: usdToLoar(withFiatMargin(0.22)),
    providerCostUsd: 0.22,
    fiatPriceUsd: withFiatMargin(0.22),
    loarPriceUsd: withLoarMargin(0.22),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'zai', 'cogvideox', 'audio', '4k'],
    bestFor: 'Premium cinematic video with optional inline audio track, up to 4K',
  },
  {
    id: 'cogvideox-flash',
    provider: 'zai',
    displayName: 'CogVideoX Flash (Z.AI)',
    shortDescription: 'Free tier — fast previews via Z.AI',
    falModelId: '',
    zaiModelId: 'cogvideox-flash',
    mode: ['text_to_video'],
    qualityTier: 'draft',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 5,
    supportedDurations: [5],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['480p', '720p'],
    creditCost: 0,
    providerCostUsd: 0,
    fiatPriceUsd: 0,
    loarPriceUsd: 0,
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['draft', 'zai', 'cogvideox', 'flash', 'free'],
    bestFor: 'Free preview-tier video drafts',
  },

  // ── Seedance 2.0 (direct ByteDance, GA Apr 2026) ─────────────────────
  {
    id: 'seedance-2-0-std-t2v',
    provider: 'bytedance',
    displayName: 'Seedance 2.0',
    shortDescription: 'Seedance 2.0 standard — native audio, multi-shot, real-world physics',
    falModelId: '',
    bytedanceModelId: 'doubao-seedance-2-0-260128',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [5, 8, 10, 15],
    supportedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.7)), // ~$0.14/s × 5s
    providerCostUsd: 0.7,
    fiatPriceUsd: withFiatMargin(0.7),
    loarPriceUsd: withLoarMargin(0.7),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'bytedance', 'seedance', 'audio', 'multi-shot', '15s'],
    bestFor: 'Premium narrative scenes with native audio and 15s continuous duration',
  },
  {
    id: 'seedance-2-0-std-i2v',
    provider: 'bytedance',
    displayName: 'Seedance 2.0 I2V',
    shortDescription: 'Seedance 2.0 image-to-video with native audio',
    falModelId: '',
    bytedanceModelId: 'doubao-seedance-2-0-260128',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [5, 8, 10, 15],
    supportedAspectRatios: ['16:9', '9:16', '1:1', '4:3', '3:4'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.7)),
    providerCostUsd: 0.7,
    fiatPriceUsd: withFiatMargin(0.7),
    loarPriceUsd: withLoarMargin(0.7),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'bytedance', 'seedance', 'audio', 'i2v', '15s'],
    bestFor: 'Image-to-video with native audio + 15s continuous',
  },
  {
    id: 'seedance-2-0-fast-t2v',
    provider: 'bytedance',
    displayName: 'Seedance 2.0 Fast',
    shortDescription: 'Seedance 2.0 Fast — cheaper 720p',
    falModelId: '',
    bytedanceModelId: 'doubao-seedance-2-0-fast-260128',
    mode: ['text_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 8, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p'],
    creditCost: usdToLoar(withFiatMargin(0.3)),
    providerCostUsd: 0.3,
    fiatPriceUsd: withFiatMargin(0.3),
    loarPriceUsd: withLoarMargin(0.3),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'bytedance', 'seedance', 'fast', 'budget'],
    bestFor: 'Fast 720p drafts via direct ByteDance',
  },
  {
    id: 'seedance-2-0-fast-i2v',
    provider: 'bytedance',
    displayName: 'Seedance 2.0 Fast I2V',
    shortDescription: 'Seedance 2.0 Fast image-to-video',
    falModelId: '',
    bytedanceModelId: 'doubao-seedance-2-0-fast-260128',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 8, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p'],
    creditCost: usdToLoar(withFiatMargin(0.3)),
    providerCostUsd: 0.3,
    fiatPriceUsd: withFiatMargin(0.3),
    loarPriceUsd: withLoarMargin(0.3),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'bytedance', 'seedance', 'fast', 'i2v'],
    bestFor: 'Fast 720p image-to-video',
  },

  // ── Seedance 2.0 via FAL passthrough ─────────────────────────────────
  {
    id: 'seedance-2-0-fal-t2v',
    provider: 'fal',
    displayName: 'Seedance 2.0 T2V (via FAL)',
    shortDescription: 'Seedance 2.0 via FAL — fallback when no Volces key',
    falModelId: 'bytedance/seedance-2.0/text-to-video',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [5, 8, 10, 15],
    supportedAspectRatios: ['16:9', '9:16', '1:1', '4:3'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(1.05)),
    providerCostUsd: 1.05,
    fiatPriceUsd: withFiatMargin(1.05),
    loarPriceUsd: withLoarMargin(1.05),
    isEnabled: true,
    isVisibleToUsers: false, // direct is preferred
    allowedPlans: [],
    tags: ['premium', 'fal', 'seedance', 'fallback'],
    bestFor: 'Fallback for Seedance 2.0 when direct ByteDance unavailable',
  },
  {
    id: 'seedance-2-0-fal-i2v',
    provider: 'fal',
    displayName: 'Seedance 2.0 I2V (via FAL)',
    shortDescription: 'Seedance 2.0 I2V via FAL — fallback',
    falModelId: 'bytedance/seedance-2.0/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 15,
    supportedDurations: [5, 8, 10, 15],
    supportedAspectRatios: ['16:9', '9:16', '1:1', '4:3'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(1.05)),
    providerCostUsd: 1.05,
    fiatPriceUsd: withFiatMargin(1.05),
    loarPriceUsd: withLoarMargin(1.05),
    isEnabled: true,
    isVisibleToUsers: false,
    allowedPlans: [],
    tags: ['premium', 'fal', 'seedance', 'i2v', 'fallback'],
    bestFor: 'Fallback for Seedance 2.0 I2V',
  },

  // ── Veo 3.1 (Google direct + FAL passthrough) ────────────────────────
  {
    id: 'veo-31-preview-google',
    provider: 'google',
    displayName: 'Veo 3.1 (Google Direct)',
    shortDescription: 'Veo 3.1 preview — native audio, up to 4K (8s)',
    falModelId: '',
    googleModelId: 'veo-3.1-generate-preview',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: true,
    maxDurationSec: 8,
    supportedDurations: [4, 6, 8],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p', '4k'],
    creditCost: usdToLoar(withFiatMargin(2.4)), // $0.40/s avg × 6s
    providerCostUsd: 2.4,
    fiatPriceUsd: withFiatMargin(2.4),
    loarPriceUsd: withLoarMargin(2.4),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'google', 'veo', '3.1', 'audio', '4k', 'preview'],
    bestFor: 'Premium cinematic with native audio + 4K (up to 8s)',
  },
  {
    id: 'veo-31-fast-preview-google',
    provider: 'google',
    displayName: 'Veo 3.1 Fast (Google Direct)',
    shortDescription: 'Veo 3.1 Fast — cheaper preview tier',
    falModelId: '',
    googleModelId: 'veo-3.1-fast-generate-preview',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: true,
    maxDurationSec: 8,
    supportedDurations: [4, 6, 8],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p', '4k'],
    creditCost: usdToLoar(withFiatMargin(0.9)), // ~$0.15/s × 6s
    providerCostUsd: 0.9,
    fiatPriceUsd: withFiatMargin(0.9),
    loarPriceUsd: withLoarMargin(0.9),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'google', 'veo', '3.1', 'fast', 'preview'],
    bestFor: 'Cheaper Veo 3.1 — fast premium drafts',
  },
  {
    id: 'veo-31-lite-preview-google',
    provider: 'google',
    displayName: 'Veo 3.1 Lite (Google Direct)',
    shortDescription: 'Veo 3.1 Lite — cheapest Veo 3.1 tier',
    falModelId: '',
    googleModelId: 'veo-3.1-lite-generate-preview',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 6, 8],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.6)),
    providerCostUsd: 0.6,
    fiatPriceUsd: withFiatMargin(0.6),
    loarPriceUsd: withLoarMargin(0.6),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'google', 'veo', '3.1', 'lite'],
    bestFor: 'Cheap Veo 3.1 drafts',
  },
  {
    id: 'veo-30-google',
    provider: 'google',
    displayName: 'Veo 3.0 (Google Direct, GA)',
    shortDescription: 'Veo 3.0 GA — native audio, 720p+1080p',
    falModelId: '',
    googleModelId: 'veo-3.0-generate-001',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 6, 8],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(2.4)),
    providerCostUsd: 2.4,
    fiatPriceUsd: withFiatMargin(2.4),
    loarPriceUsd: withLoarMargin(2.4),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'google', 'veo', '3.0', 'ga', 'audio'],
    bestFor: 'Veo 3.0 GA premium with audio',
  },
  {
    id: 'veo-30-fast-google',
    provider: 'google',
    displayName: 'Veo 3.0 Fast (Google Direct, GA)',
    shortDescription: 'Veo 3.0 Fast GA',
    falModelId: '',
    googleModelId: 'veo-3.0-fast-generate-001',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 6, 8],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(1.2)),
    providerCostUsd: 1.2,
    fiatPriceUsd: withFiatMargin(1.2),
    loarPriceUsd: withLoarMargin(1.2),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'google', 'veo', '3.0', 'fast', 'ga'],
    bestFor: 'Veo 3.0 Fast GA — best balance of cost and quality',
  },
  {
    id: 'veo-20-google',
    provider: 'google',
    displayName: 'Veo 2.0 (Google Direct, GA)',
    shortDescription: 'Veo 2.0 — silent, 720p',
    falModelId: '',
    googleModelId: 'veo-2.0-generate-001',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [4, 6, 8],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p'],
    creditCost: usdToLoar(withFiatMargin(2.1)),
    providerCostUsd: 2.1,
    fiatPriceUsd: withFiatMargin(2.1),
    loarPriceUsd: withLoarMargin(2.1),
    isEnabled: true,
    isVisibleToUsers: false, // hidden — Veo 3 supersedes
    allowedPlans: [],
    tags: ['standard', 'google', 'veo', '2.0', 'legacy'],
    bestFor: 'Legacy Veo 2.0 parity',
  },
  {
    id: 'veo-31-fal',
    provider: 'fal',
    displayName: 'Veo 3.1 (via FAL)',
    shortDescription: 'Veo 3.1 via FAL — alternative to Google direct',
    falModelId: 'fal-ai/veo3.1',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: true,
    maxDurationSec: 8,
    supportedDurations: [4, 6, 8],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p', '4k'],
    creditCost: usdToLoar(withFiatMargin(2.4)),
    providerCostUsd: 2.4,
    fiatPriceUsd: withFiatMargin(2.4),
    loarPriceUsd: withLoarMargin(2.4),
    isEnabled: true,
    isVisibleToUsers: false, // prefer Google direct
    allowedPlans: [],
    tags: ['premium', 'fal', 'veo', '3.1', 'fallback'],
    bestFor: 'Fallback for Veo 3.1 via FAL',
  },

  // ── Kling v3 family (FAL) ────────────────────────────────────────────
  {
    id: 'kling-v3-pro-t2v',
    provider: 'fal',
    displayName: 'Kling v3 Pro T2V',
    shortDescription: 'Kling v3 Pro — native audio',
    falModelId: 'fal-ai/kling-video/v3/pro/text-to-video',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['1080p'],
    creditCost: usdToLoar(withFiatMargin(1.6)),
    providerCostUsd: 1.6,
    fiatPriceUsd: withFiatMargin(1.6),
    loarPriceUsd: withLoarMargin(1.6),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'kling', 'v3', 'audio'],
    bestFor: 'Premium Kling v3 Pro with native audio',
  },
  {
    id: 'kling-v3-pro-i2v',
    provider: 'fal',
    displayName: 'Kling v3 Pro I2V',
    shortDescription: 'Kling v3 Pro image-to-video with native audio',
    falModelId: 'fal-ai/kling-video/v3/pro/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['1080p'],
    creditCost: usdToLoar(withFiatMargin(1.6)),
    providerCostUsd: 1.6,
    fiatPriceUsd: withFiatMargin(1.6),
    loarPriceUsd: withLoarMargin(1.6),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'kling', 'v3', 'audio', 'i2v'],
    bestFor: 'Premium Kling v3 Pro I2V with native audio',
  },
  {
    id: 'kling-v3-4k-t2v',
    provider: 'fal',
    displayName: 'Kling v3 4K T2V',
    shortDescription: 'Native 4K Kling v3',
    falModelId: 'fal-ai/kling-video/v3/4k/text-to-video',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: true,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9'],
    supportedResolutions: ['4k'],
    creditCost: usdToLoar(withFiatMargin(3.0)),
    providerCostUsd: 3.0,
    fiatPriceUsd: withFiatMargin(3.0),
    loarPriceUsd: withLoarMargin(3.0),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'kling', 'v3', '4k', 'flagship'],
    bestFor: 'Hero shots at native 4K',
  },
  {
    id: 'kling-v3-4k-i2v',
    provider: 'fal',
    displayName: 'Kling v3 4K I2V',
    shortDescription: 'Native 4K Kling v3 image-to-video',
    falModelId: 'fal-ai/kling-video/v3/4k/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    supportsAudio: true,
    supports1080p: true,
    supports4k: true,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9'],
    supportedResolutions: ['4k'],
    creditCost: usdToLoar(withFiatMargin(3.0)),
    providerCostUsd: 3.0,
    fiatPriceUsd: withFiatMargin(3.0),
    loarPriceUsd: withLoarMargin(3.0),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'kling', 'v3', '4k', 'i2v'],
    bestFor: '4K hero I2V',
  },

  // ── Sora 2 (OpenAI direct + FAL) ─────────────────────────────────────
  {
    id: 'sora-2-openai',
    provider: 'openai',
    displayName: 'Sora 2 (OpenAI Direct)',
    shortDescription: 'OpenAI Sora 2 native — 720p, $0.10/sec',
    falModelId: '',
    openaiModelId: 'sora-2',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: false,
    supports1080p: false,
    supports4k: false,
    maxDurationSec: 12,
    supportedDurations: [4, 8, 12],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p'],
    creditCost: usdToLoar(withFiatMargin(0.8)), // $0.10/s × 8s
    providerCostUsd: 0.8,
    fiatPriceUsd: withFiatMargin(0.8),
    loarPriceUsd: withLoarMargin(0.8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'sora', 'direct'],
    bestFor: 'OpenAI Sora 2 direct — no FAL passthrough cost',
  },
  {
    id: 'sora-2-pro-openai',
    provider: 'openai',
    displayName: 'Sora 2 Pro (OpenAI Direct)',
    shortDescription: 'Sora 2 Pro — extended duration up to 25s, native 1024p',
    falModelId: '',
    openaiModelId: 'sora-2-pro',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'high',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 25,
    supportedDurations: [4, 8, 12, 16, 20, 25],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(4.0)), // $0.50/s × 8s 1024p
    providerCostUsd: 4.0,
    fiatPriceUsd: withFiatMargin(4.0),
    loarPriceUsd: withLoarMargin(4.0),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'openai', 'sora', 'pro', 'direct', 'long-form'],
    bestFor: 'Long-form Sora 2 Pro renders up to 25s at 1024p',
  },

  // ── LTX-2 family ─────────────────────────────────────────────────────
  {
    id: 'ltx-2',
    provider: 'fal',
    displayName: 'LTX-2',
    shortDescription: 'Latest LTX — successor to ltx-video',
    falModelId: 'fal-ai/ltx-2',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.08)),
    providerCostUsd: 0.08,
    fiatPriceUsd: withFiatMargin(0.08),
    loarPriceUsd: withLoarMargin(0.08),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'ltx', 'fast', 'budget', 'open'],
    bestFor: 'Cheap fast drafts on the LTX successor',
  },
  {
    id: 'ltx-2-19b',
    provider: 'fal',
    displayName: 'LTX-2 19B',
    shortDescription: 'LTX-2 with 19B params — better quality',
    falModelId: 'fal-ai/ltx-2-19b',
    mode: ['text_to_video', 'image_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    supportsAudio: false,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.12)),
    providerCostUsd: 0.12,
    fiatPriceUsd: withFiatMargin(0.12),
    loarPriceUsd: withLoarMargin(0.12),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'ltx', '19b'],
    bestFor: 'Higher-quality LTX with 19B param budget',
  },

  // ── Happy Horse (Alibaba, 1080p + lipsync) ───────────────────────────
  {
    id: 'happy-horse-t2v',
    provider: 'fal',
    displayName: 'Happy Horse 1.0 T2V',
    shortDescription: 'Alibaba Happy Horse — 1080p, synced audio + multilingual lipsync',
    falModelId: 'alibaba/happy-horse/text-to-video',
    mode: ['text_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.8)),
    providerCostUsd: 0.8,
    fiatPriceUsd: withFiatMargin(0.8),
    loarPriceUsd: withLoarMargin(0.8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'alibaba', 'happy-horse', 'lipsync', 'audio'],
    bestFor: '1080p video with synced multilingual lipsync',
  },
  {
    id: 'happy-horse-i2v',
    provider: 'fal',
    displayName: 'Happy Horse 1.0 I2V',
    shortDescription: 'Happy Horse image-to-video with synced audio',
    falModelId: 'alibaba/happy-horse/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 10,
    supportedDurations: [5, 10],
    supportedAspectRatios: ['16:9', '9:16'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.8)),
    providerCostUsd: 0.8,
    fiatPriceUsd: withFiatMargin(0.8),
    loarPriceUsd: withLoarMargin(0.8),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['premium', 'alibaba', 'happy-horse', 'i2v', 'audio'],
    bestFor: 'Happy Horse I2V with synced audio',
  },

  // ── PixVerse v6 ──────────────────────────────────────────────────────
  {
    id: 'pixverse-v6-i2v',
    provider: 'fal',
    displayName: 'PixVerse V6 I2V',
    shortDescription: 'PixVerse V6 image-to-video',
    falModelId: 'fal-ai/pixverse/v6/image-to-video',
    mode: ['image_to_video'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'medium',
    supportsAudio: true,
    supports1080p: true,
    supports4k: false,
    maxDurationSec: 8,
    supportedDurations: [5, 8],
    supportedAspectRatios: ['16:9', '9:16', '1:1'],
    supportedResolutions: ['720p', '1080p'],
    creditCost: usdToLoar(withFiatMargin(0.4)),
    providerCostUsd: 0.4,
    fiatPriceUsd: withFiatMargin(0.4),
    loarPriceUsd: withLoarMargin(0.4),
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    tags: ['standard', 'pixverse', 'v6', 'i2v'],
    bestFor: 'Mid-tier PixVerse I2V with audio',
  },
];

// ── Lookup Helpers ────────────────────────────────────────────────────

const modelsById = new Map(VIDEO_MODELS.map((m) => [m.id, m]));

export function getModelById(id: string): VideoModelConfig | undefined {
  return modelsById.get(id);
}

export function getModelByFalId(falModelId: string): VideoModelConfig | undefined {
  return VIDEO_MODELS.find((m) => m.falModelId === falModelId);
}

export function getEnabledModels(): VideoModelConfig[] {
  return VIDEO_MODELS.filter((m) => m.isEnabled);
}

export function getVisibleModels(): VideoModelConfig[] {
  return VIDEO_MODELS.filter((m) => m.isEnabled && m.isVisibleToUsers);
}

export function getModelsForMode(mode: VideoGenerationMode): VideoModelConfig[] {
  return getVisibleModels().filter((m) => m.mode.includes(mode));
}

export function getModelIds(): string[] {
  return VIDEO_MODELS.map((m) => m.id);
}
