[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.devnet]
episode = "voLiAXoYbq8go1CUS9UshQRZnNu9Y44qNBZ6czgn8Bs"
payment = "9xWo4djcHmGFkJnLQF9phdpsUhj6BQFW6yR8sHUsKVbj"
universe = "6YTQVSeauk4x5gycMM2wzkR8mdHEnHAYsz3Ygg26UPtD"
rights = "NDpYpB49e3yzEcsPK1o34h9Zgrw9CPnVTnZLvDowL4m"
licensing = "HTQhzknwF5mnnhHVSaF5ckRbeviwX2UuwayPNjiQybTp"
split_router = "7hcFnt2Tgzi1Sc3PDWqAQRFb6BoRmEtmoizBSLaYCGkr"
staking = "9EjnngPFpE3QaUgS3zspXwkLby2AnNwyC2UjPFL9zBqJ"
credit_manager = "71rtSGzuBENiQa1cdmBbrN5F496CGQ46TnRGbGNpQ3xs"
subscription = "Hnnkuf933sv2rEucpCLaLbXxA1zPNxTNpUsp1WX9Fwbm"
remix_fees = "5JdzozEXeto8CRgUZmLqrtwkGtt8smpaM4vhahW1gNLs"
bonding_curve = "seJzMSz9EkVYuNN9Nu3eJF3UgepeWzfgGvDnzrp2Uiw"
canon_market = "2T6WzMCrSRLzUp6zwPhWPuguk84pDqozs6VwrykTR25u"

[programs.localnet]
episode = "voLiAXoYbq8go1CUS9UshQRZnNu9Y44qNBZ6czgn8Bs"
payment = "9xWo4djcHmGFkJnLQF9phdpsUhj6BQFW6yR8sHUsKVbj"
universe = "6YTQVSeauk4x5gycMM2wzkR8mdHEnHAYsz3Ygg26UPtD"
rights = "NDpYpB49e3yzEcsPK1o34h9Zgrw9CPnVTnZLvDowL4m"
licensing = "HTQhzknwF5mnnhHVSaF5ckRbeviwX2UuwayPNjiQybTp"
split_router = "7hcFnt2Tgzi1Sc3PDWqAQRFb6BoRmEtmoizBSLaYCGkr"
staking = "9EjnngPFpE3QaUgS3zspXwkLby2AnNwyC2UjPFL9zBqJ"
credit_manager = "71rtSGzuBENiQa1cdmBbrN5F496CGQ46TnRGbGNpQ3xs"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[workspace]
members = ["programs/universe", "programs/episode", "programs/payment", "programs/rights", "programs/licensing", "programs/split_router", "programs/staking", "programs/credit_manager", "programs/subscription", "programs/remix_fees", "programs/bonding_curve", "programs/canon_market"]

[scripts]
test = "pnpm exec mocha --require tsx/cjs -t 1000000 tests/**/*.ts"
