/**
 * LLM (chat/reasoning/vision) model registry.
 *
 * Covers every model that drives the canon-check, script-gen, agent
 * runtime, and worldbuilding helpers. Pricing units are USD per million
 * tokens — split into input / cached-input / output, with margin-derived
 * fiat + $LOAR rates.
 */
import type { LlmModelConfig } from './types';

export { FIAT_MARGIN, LOAR_MARGIN, LOAR_TO_USD } from '../video-models/registry';
import { FIAT_MARGIN, LOAR_MARGIN, LOAR_TO_USD } from '../video-models/registry';

function withFiatMargin(c: number): number {
  return Math.round(c * FIAT_MARGIN * 100) / 100;
}
function withLoarMargin(c: number): number {
  return Math.round(c * LOAR_MARGIN * 100) / 100;
}
function usdToCreditsPer1kTok(perMtok: number): number {
  const perThousandUsd = perMtok / 1000;
  return Math.max(1, Math.ceil(perThousandUsd / LOAR_TO_USD));
}

interface InitArgs {
  inputUsd: number;
  cachedInputUsd: number;
  outputUsd: number;
}

function pricing(args: InitArgs) {
  return {
    providerInputUsdPerMtok: args.inputUsd,
    providerCachedInputUsdPerMtok: args.cachedInputUsd,
    providerOutputUsdPerMtok: args.outputUsd,
    fiatInputUsdPerMtok: withFiatMargin(args.inputUsd),
    fiatOutputUsdPerMtok: withFiatMargin(args.outputUsd),
    loarInputUsdPerMtok: withLoarMargin(args.inputUsd),
    loarOutputUsdPerMtok: withLoarMargin(args.outputUsd),
    creditCostPer1kInputTokens: usdToCreditsPer1kTok(args.inputUsd),
    creditCostPer1kOutputTokens: usdToCreditsPer1kTok(args.outputUsd),
  };
}

export const LLM_MODELS: LlmModelConfig[] = [
  // ── OpenAI flagship reasoning ────────────────────────────────────────
  {
    id: 'gpt-5',
    provider: 'openai',
    displayName: 'GPT-5',
    shortDescription: 'OpenAI flagship — 400K context, reasoning + vision',
    providerModelId: 'gpt-5',
    contextTokens: 400_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'vision', 'tools', 'structured_outputs', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'high',
    ...pricing({ inputUsd: 1.25, cachedInputUsd: 0.125, outputUsd: 10.0 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['openai', 'flagship', 'reasoning', 'vision', 'long-context'],
    bestFor: 'Flagship reasoning, multi-modal worldbuilding, agent runtime',
  },
  {
    id: 'gpt-5-mini',
    provider: 'openai',
    displayName: 'GPT-5 Mini',
    shortDescription: 'GPT-5 balanced tier — 400K context',
    providerModelId: 'gpt-5-mini',
    contextTokens: 400_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'vision', 'tools', 'structured_outputs', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'medium',
    ...pricing({ inputUsd: 0.25, cachedInputUsd: 0.025, outputUsd: 2.0 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['openai', 'mini', 'reasoning', 'vision', 'long-context'],
    bestFor: 'Default agent runtime — best price/quality balance',
  },
  {
    id: 'gpt-5-nano',
    provider: 'openai',
    displayName: 'GPT-5 Nano',
    shortDescription: 'Cheapest GPT-5 — classification, formatting',
    providerModelId: 'gpt-5-nano',
    contextTokens: 400_000,
    maxOutputTokens: 128_000,
    capabilities: ['chat', 'vision', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.05, cachedInputUsd: 0.005, outputUsd: 0.4 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['openai', 'nano', 'vision', 'budget', 'long-context'],
    bestFor: 'Cheap bulk: classification, formatting, summarization',
  },
  {
    id: 'o3',
    provider: 'openai',
    displayName: 'OpenAI o3',
    shortDescription: 'Deep reasoning — beats GPT-5 on math/code',
    providerModelId: 'o3',
    contextTokens: 200_000,
    maxOutputTokens: 100_000,
    capabilities: ['chat', 'reasoning', 'vision', 'tools', 'structured_outputs'],
    qualityTier: 'premium',
    speedTier: 'slow',
    priceTier: 'medium',
    ...pricing({ inputUsd: 2.0, cachedInputUsd: 0.5, outputUsd: 8.0 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['openai', 'o3', 'reasoning', 'vision', 'deep-think'],
    bestFor: 'Hard reasoning passes — math, code, planning',
  },
  {
    id: 'o4-mini',
    provider: 'openai',
    displayName: 'OpenAI o4-mini',
    shortDescription: 'Cheaper reasoning tier',
    providerModelId: 'o4-mini',
    contextTokens: 200_000,
    maxOutputTokens: 100_000,
    capabilities: ['chat', 'reasoning', 'vision', 'tools'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    ...pricing({ inputUsd: 1.1, cachedInputUsd: 0.275, outputUsd: 4.4 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['openai', 'o4-mini', 'reasoning'],
    bestFor: 'Best-value reasoning at mid tier',
  },
  {
    id: 'gpt-4-1',
    provider: 'openai',
    displayName: 'GPT-4.1',
    shortDescription: 'Long-context flagship — 1M tokens, vision',
    providerModelId: 'gpt-4.1',
    contextTokens: 1_000_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'vision', 'tools', 'structured_outputs', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    ...pricing({ inputUsd: 2.0, cachedInputUsd: 0.5, outputUsd: 8.0 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['openai', 'gpt-4.1', 'long-context', 'vision', '1m'],
    bestFor: 'Long-context lore + script docs (universe-wide passes)',
  },
  {
    id: 'gpt-4-1-mini',
    provider: 'openai',
    displayName: 'GPT-4.1 Mini',
    shortDescription: 'Long-context Mini — 1M tokens',
    providerModelId: 'gpt-4.1-mini',
    contextTokens: 1_000_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'vision', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.4, cachedInputUsd: 0.1, outputUsd: 1.6 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['openai', 'gpt-4.1', 'mini', 'long-context'],
    bestFor: 'Cheap long-context lore agent',
  },
  {
    id: 'gpt-4-1-nano',
    provider: 'openai',
    displayName: 'GPT-4.1 Nano',
    shortDescription: 'Cheapest long-context — 1M tokens',
    providerModelId: 'gpt-4.1-nano',
    contextTokens: 1_000_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'vision', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.1, cachedInputUsd: 0.025, outputUsd: 0.4 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['openai', 'gpt-4.1', 'nano', 'budget', 'long-context'],
    bestFor: 'Cheap bulk long-context retrieval / RAG',
  },

  // ── Google Gemini family ─────────────────────────────────────────────
  {
    id: 'gemini-3-1-pro',
    provider: 'google',
    displayName: 'Gemini 3.1 Pro',
    shortDescription: 'Google flagship — multimodal, long-context',
    providerModelId: 'gemini-3.1-pro-preview',
    contextTokens: 2_000_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'vision', 'tools', 'structured_outputs', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    ...pricing({ inputUsd: 2.0, cachedInputUsd: 0.2, outputUsd: 12.0 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['google', 'gemini', '3.1', 'pro', 'vision', 'long-context', 'preview'],
    bestFor: 'Premium multimodal — vision + reasoning + 2M ctx',
  },
  {
    id: 'gemini-3-1-flash-lite',
    provider: 'google',
    displayName: 'Gemini 3.1 Flash Lite',
    shortDescription: 'Cheap fast Gemini 3.1 — GA',
    providerModelId: 'gemini-3.1-flash-lite',
    contextTokens: 1_000_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'vision', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.25, cachedInputUsd: 0.025, outputUsd: 1.5 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['google', 'gemini', '3.1', 'flash-lite', 'budget', 'ga'],
    bestFor: 'Cheap fast Gemini for bulk text + vision tasks',
  },
  {
    id: 'gemini-2-5-pro',
    provider: 'google',
    displayName: 'Gemini 2.5 Pro',
    shortDescription: 'GA Gemini Pro — vision + reasoning, 1M ctx',
    providerModelId: 'gemini-2.5-pro',
    contextTokens: 2_000_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'vision', 'tools', 'structured_outputs', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    ...pricing({ inputUsd: 1.25, cachedInputUsd: 0.125, outputUsd: 10.0 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['google', 'gemini', '2.5', 'pro', 'vision', 'long-context', 'ga'],
    bestFor: 'GA Gemini Pro — production canon checks & long-form lore',
  },
  {
    id: 'gemini-2-5-flash',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash',
    shortDescription: 'Fast Gemini Flash GA — multimodal',
    providerModelId: 'gemini-2.5-flash',
    contextTokens: 1_000_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'vision', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.3, cachedInputUsd: 0.03, outputUsd: 2.5 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['google', 'gemini', '2.5', 'flash', 'ga'],
    bestFor: 'Mid-tier multimodal — agent default',
  },
  {
    id: 'gemini-2-5-flash-lite',
    provider: 'google',
    displayName: 'Gemini 2.5 Flash Lite',
    shortDescription: 'Cheapest Gemini Flash GA',
    providerModelId: 'gemini-2.5-flash-lite',
    contextTokens: 1_000_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'vision', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.1, cachedInputUsd: 0.01, outputUsd: 0.4 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['google', 'gemini', '2.5', 'flash-lite', 'budget', 'ga'],
    bestFor: 'Cheapest Gemini for high-volume tasks',
  },

  // ── Z.AI / Zhipu GLM ─────────────────────────────────────────────────
  {
    id: 'glm-5-1',
    provider: 'zai',
    displayName: 'GLM-5.1 (Z.AI)',
    shortDescription: 'Z.AI flagship — 754B, 200K context',
    providerModelId: 'glm-5.1',
    contextTokens: 200_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'tools', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    ...pricing({ inputUsd: 1.4, cachedInputUsd: 0.35, outputUsd: 4.4 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['zai', 'glm', '5.1', 'flagship', 'long-context'],
    bestFor: 'Premium Z.AI reasoning — 200K context',
  },
  {
    id: 'glm-5',
    provider: 'zai',
    displayName: 'GLM-5 (Z.AI)',
    shortDescription: 'GLM-5 — 200K MoE flagship',
    providerModelId: 'glm-5',
    contextTokens: 200_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'tools', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'medium',
    ...pricing({ inputUsd: 1.0, cachedInputUsd: 0.25, outputUsd: 3.2 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['zai', 'glm', '5', 'moe'],
    bestFor: 'GLM flagship with 40B-active MoE',
  },
  {
    id: 'glm-4-7',
    provider: 'zai',
    displayName: 'GLM-4.7 (Z.AI)',
    shortDescription: 'GLM-4.7 — reasoning + 200K context',
    providerModelId: 'glm-4.7',
    contextTokens: 200_000,
    maxOutputTokens: 131_072,
    capabilities: ['chat', 'reasoning', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'medium',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.4, cachedInputUsd: 0.1, outputUsd: 1.75 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['zai', 'glm', '4.7', 'reasoning'],
    bestFor: 'Default Z.AI reasoning agent — strong cost/quality',
  },
  {
    id: 'glm-4-7-flash',
    provider: 'zai',
    displayName: 'GLM-4.7 Flash (Z.AI)',
    shortDescription: 'Cheapest fast Z.AI tier',
    providerModelId: 'glm-4.7-flash',
    contextTokens: 200_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.06, cachedInputUsd: 0.015, outputUsd: 0.4 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['zai', 'glm', '4.7', 'flash', 'budget'],
    bestFor: 'Cheapest fast Z.AI for bulk extraction / formatting',
  },
  {
    id: 'glm-4-5-flash',
    provider: 'zai',
    displayName: 'GLM-4.5 Flash (Z.AI)',
    shortDescription: 'Free tier — basic completions',
    providerModelId: 'glm-4.5-flash',
    contextTokens: 128_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'tools'],
    qualityTier: 'draft',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0, cachedInputUsd: 0, outputUsd: 0 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['zai', 'glm', '4.5', 'flash', 'free'],
    bestFor: 'Free canary / format-only tasks',
  },
  {
    id: 'glm-4-5-air',
    provider: 'zai',
    displayName: 'GLM-4.5 Air (Z.AI)',
    shortDescription: 'GLM-4.5 Air — 131K context, lightweight',
    providerModelId: 'glm-4.5-air',
    contextTokens: 131_072,
    maxOutputTokens: 96_000,
    capabilities: ['chat', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.13, cachedInputUsd: 0.03, outputUsd: 0.85 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['zai', 'glm', '4.5', 'air', 'long-context'],
    bestFor: 'Long-context summarization at cheap rate',
  },

  // ── Z.AI Vision ──────────────────────────────────────────────────────
  {
    id: 'glm-4-6v',
    provider: 'zai',
    displayName: 'GLM-4.6V (Z.AI Vision)',
    shortDescription: 'Z.AI flagship VLM — 128K, function calling',
    providerModelId: 'glm-4.6v',
    contextTokens: 128_000,
    maxOutputTokens: 24_000,
    capabilities: ['chat', 'vision', 'tools', 'structured_outputs'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.6, cachedInputUsd: 0.15, outputUsd: 0.9 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['zai', 'glm', '4.6v', 'vision', 'canon-check'],
    bestFor: 'Canon-check + episode visual review (50% cheaper output than 4.5v)',
  },
  {
    id: 'glm-4-6v-flash',
    provider: 'zai',
    displayName: 'GLM-4.6V Flash (Z.AI)',
    shortDescription: 'Free-tier vision — 9B, 128K context',
    providerModelId: 'glm-4.6v-flash',
    contextTokens: 128_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'vision'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0, cachedInputUsd: 0, outputUsd: 0 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['zai', 'glm', '4.6v', 'flash', 'free', 'vision'],
    bestFor: 'Free bulk vision review',
  },

  // ── Doubao Seed (ByteDance) ──────────────────────────────────────────
  {
    id: 'doubao-seed-2-0-pro',
    provider: 'bytedance',
    displayName: 'Doubao Seed 2.0 Pro',
    shortDescription: 'Doubao Seed 2.0 Pro — flagship agent LLM',
    providerModelId: 'doubao-seed-2-0-pro',
    contextTokens: 256_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'tools', 'structured_outputs', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.5, cachedInputUsd: 0.1, outputUsd: 1.5 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['bytedance', 'doubao', 'seed', '2.0', 'pro', 'reasoning'],
    bestFor: 'Cost-effective premium reasoning (GPT-5.2 / Gemini 3 Pro tier)',
  },
  {
    id: 'doubao-seed-2-0-lite',
    provider: 'bytedance',
    displayName: 'Doubao Seed 2.0 Lite',
    shortDescription: 'Lite tier — ~5× cheaper than Pro, 93 AIME-2025',
    providerModelId: 'doubao-seed-2-0-lite',
    contextTokens: 128_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.1, cachedInputUsd: 0.02, outputUsd: 0.3 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['bytedance', 'doubao', 'seed', '2.0', 'lite', 'budget'],
    bestFor: 'Cheap Doubao tier with strong math/code',
  },
  {
    id: 'doubao-seed-1-6-vision',
    provider: 'bytedance',
    displayName: 'Doubao Seed 1.6 Vision',
    shortDescription: '50% cheaper than 1.5-thinking-vision-pro, adds tool-calling',
    providerModelId: 'doubao-seed-1-6-vision',
    contextTokens: 128_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'vision', 'tools', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'medium',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.4, cachedInputUsd: 0.1, outputUsd: 1.2 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: true,
    tags: ['bytedance', 'doubao', 'seed', '1.6', 'vision', 'tool-calling'],
    bestFor: 'Vision + tool-calling for canon-check at the cheapest premium tier',
  },

  // ── Groq-hosted open LLMs ────────────────────────────────────────────
  {
    id: 'llama-3-3-70b-versatile-groq',
    provider: 'groq',
    displayName: 'Llama 3.3 70B (Groq)',
    shortDescription: 'Llama 3.3 versatile — tools + JSON, 128K ctx',
    providerModelId: 'llama-3.3-70b-versatile',
    contextTokens: 128_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'tools', 'json_mode', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.59, cachedInputUsd: 0.3, outputUsd: 0.79 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: false,
    tags: ['groq', 'llama', '3.3', '70b', 'fast'],
    bestFor: 'Open Llama 3.3 via Groq at high throughput',
  },
  {
    id: 'llama-3-1-8b-instant-groq',
    provider: 'groq',
    displayName: 'Llama 3.1 8B Instant (Groq)',
    shortDescription: 'Cheapest Groq LLM — 750+ tok/s',
    providerModelId: 'llama-3.1-8b-instant',
    contextTokens: 128_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.05, cachedInputUsd: 0.025, outputUsd: 0.08 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: false,
    tags: ['groq', 'llama', '3.1', '8b', 'instant', 'budget'],
    bestFor: 'Ultra-cheap fast chat for bulk processing',
  },
  {
    id: 'gpt-oss-120b-groq',
    provider: 'groq',
    displayName: 'GPT-OSS 120B (Groq)',
    shortDescription: 'OpenAI open-weights 120B — reasoning + tools',
    providerModelId: 'openai/gpt-oss-120b',
    contextTokens: 131_000,
    maxOutputTokens: 65_000,
    capabilities: ['chat', 'reasoning', 'tools', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.15, cachedInputUsd: 0.075, outputUsd: 0.6 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: false,
    tags: ['groq', 'gpt-oss', '120b', 'reasoning', 'open'],
    bestFor: 'OpenAI open-weights reasoning at Groq speed',
  },
  {
    id: 'gpt-oss-20b-groq',
    provider: 'groq',
    displayName: 'GPT-OSS 20B (Groq)',
    shortDescription: 'OpenAI open-weights 20B MoE — fastest open tier',
    providerModelId: 'openai/gpt-oss-20b',
    contextTokens: 131_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.075, cachedInputUsd: 0.0375, outputUsd: 0.3 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: false,
    tags: ['groq', 'gpt-oss', '20b', 'fast', 'budget'],
    bestFor: 'Cheap fast open-weights chat',
  },
  {
    id: 'qwen-3-32b-groq',
    provider: 'groq',
    displayName: 'Qwen 3 32B (Groq)',
    shortDescription: 'Qwen 3 — reasoning, 128K ctx',
    providerModelId: 'qwen/qwen3-32b',
    contextTokens: 128_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'tools', 'long_context'],
    qualityTier: 'standard',
    speedTier: 'fast',
    priceTier: 'low',
    ...pricing({ inputUsd: 0.29, cachedInputUsd: 0.145, outputUsd: 0.59 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: false,
    tags: ['groq', 'qwen', '3', 'reasoning'],
    bestFor: 'Cheap reasoning for code + math',
  },
  {
    id: 'kimi-k2-instruct-groq',
    provider: 'groq',
    displayName: 'Kimi K2 Instruct (Groq)',
    shortDescription: '256K context, agentic + coding',
    providerModelId: 'moonshotai/kimi-k2-instruct',
    contextTokens: 256_000,
    maxOutputTokens: null,
    capabilities: ['chat', 'reasoning', 'tools', 'long_context'],
    qualityTier: 'premium',
    speedTier: 'fast',
    priceTier: 'medium',
    ...pricing({ inputUsd: 0.6, cachedInputUsd: 0.3, outputUsd: 2.5 }),
    lastVerified: '2026-05-17',
    isEnabled: true,
    isVisibleToUsers: true,
    allowedPlans: [],
    serverPoolAvailable: false,
    tags: ['groq', 'kimi', 'k2', 'long-context', 'agent'],
    bestFor: 'Long-context coding/agent runs at Groq speed',
  },
];

// ── Lookup helpers ────────────────────────────────────────────────────

export function getLlmModelById(id: string): LlmModelConfig | undefined {
  return LLM_MODELS.find((m) => m.id === id);
}

export function getEnabledLlmModels(): LlmModelConfig[] {
  return LLM_MODELS.filter((m) => m.isEnabled);
}

export function getVisibleLlmModels(): LlmModelConfig[] {
  return LLM_MODELS.filter((m) => m.isEnabled && m.isVisibleToUsers);
}

export function getLlmModelIds(): string[] {
  return LLM_MODELS.map((m) => m.id);
}
