/**
 * Kind-specific detail fields for world entities. Shared by the per-kind
 * create form (/create/$kind) and the /create console's world workspaces so
 * both collect the same structured metadata.
 */
import type { EntityKind } from '@/lib/random-entity';

export interface FieldDef {
  key: string;
  label: string;
  placeholder: string;
  type: 'input' | 'textarea';
  metadataKey?: boolean; /** If true, stored in metadata rather than root fields */
}

export const FIELDS_BY_KIND: Record<EntityKind, FieldDef[]> = {
  person: [
    {
      key: 'role',
      label: 'Role / Archetype',
      placeholder: 'e.g. Protagonist, Villain, Mentor',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'appearance',
      label: 'Appearance',
      placeholder: 'Physical description...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'motivations',
      label: 'Motivations',
      placeholder: 'What drives them?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'abilities',
      label: 'Abilities / Skills',
      placeholder: 'Powers, skills, talents...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'homePlace',
      label: 'Home / Origin',
      placeholder: 'Where are they from?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'affiliations',
      label: 'Affiliations',
      placeholder: 'Factions, groups, loyalties...',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'personality',
      label: 'Personality',
      placeholder: 'Temperament, how they behave...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'backstory',
      label: 'Backstory',
      placeholder: 'What made them who they are?',
      type: 'textarea',
      metadataKey: true,
    },
  ],
  place: [
    {
      key: 'placeType',
      label: 'Type',
      placeholder: 'e.g. City, Planet, Dungeon, Kingdom',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'atmosphere',
      label: 'Atmosphere',
      placeholder: 'Mood, climate, feel...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'rulesAndDangers',
      label: 'Rules / Dangers',
      placeholder: 'What to know before entering...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'inhabitants',
      label: 'Inhabitants',
      placeholder: 'Who lives here?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'governingFaction',
      label: 'Governing Faction',
      placeholder: 'Who controls this place?',
      type: 'input',
      metadataKey: true,
    },
  ],
  thing: [
    {
      key: 'thingType',
      label: 'Type',
      placeholder: 'e.g. Weapon, Relic, Book, Tool',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'origin',
      label: 'Origin',
      placeholder: 'How was it made / where did it come from?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'powersAndUse',
      label: 'Powers / Use',
      placeholder: 'What does it do?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'rarity',
      label: 'Rarity',
      placeholder: 'e.g. Unique, Legendary, Common',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'currentOwner',
      label: 'Current Owner',
      placeholder: 'Who holds it now?',
      type: 'input',
      metadataKey: true,
    },
  ],
  faction: [
    {
      key: 'mission',
      label: 'Mission',
      placeholder: 'What do they stand for?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'ideology',
      label: 'Ideology',
      placeholder: 'Beliefs, values, worldview...',
      type: 'textarea',
      metadataKey: true,
    },
    { key: 'leader', label: 'Leader', placeholder: 'Who leads?', type: 'input', metadataKey: true },
    {
      key: 'rivals',
      label: 'Rivals / Enemies',
      placeholder: 'Who do they oppose?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'hq',
      label: 'Headquarters',
      placeholder: 'Where are they based?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'resources',
      label: 'Resources',
      placeholder: 'What assets do they command?',
      type: 'textarea',
      metadataKey: true,
    },
  ],
  event: [
    {
      key: 'era',
      label: 'Date / Era',
      placeholder: 'When did this happen?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'participants',
      label: 'Participants',
      placeholder: 'Who was involved?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'location',
      label: 'Location',
      placeholder: 'Where did it happen?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'causes',
      label: 'Causes',
      placeholder: 'What led to this?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'outcome',
      label: 'Outcome',
      placeholder: 'What resulted?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'canonStatus',
      label: 'Canon Status',
      placeholder: 'e.g. Canon, Apocrypha, Alternate Timeline',
      type: 'input',
      metadataKey: true,
    },
  ],
  lore: [
    {
      key: 'loreType',
      label: 'Type',
      placeholder: 'e.g. Magic System, Religion, Law, Prophecy',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'article',
      label: 'Article Body',
      placeholder: 'The full lore entry...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'relatedConcepts',
      label: 'Related Concepts',
      placeholder: 'Connected ideas, terms, entities...',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'canonWeight',
      label: 'Canon Weight',
      placeholder: 'e.g. Hard Canon, Soft Canon, Fanon',
      type: 'input',
      metadataKey: true,
    },
  ],
  species: [
    {
      key: 'biologicalType',
      label: 'Biological Type',
      placeholder: 'e.g. Mammalian, Insectoid, Energy Being',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'traits',
      label: 'Defining Traits',
      placeholder: 'Physical and behavioral traits...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'homeworld',
      label: 'Homeworld / Origin',
      placeholder: 'Where did they evolve?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'culture',
      label: 'Culture',
      placeholder: 'Society, customs, beliefs...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'abilities',
      label: 'Abilities',
      placeholder: 'Special powers or weaknesses...',
      type: 'textarea',
      metadataKey: true,
    },
  ],
  vehicle: [
    {
      key: 'vehicleType',
      label: 'Type',
      placeholder: 'e.g. Starship, Mech, Mount, Submarine',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'crew',
      label: 'Crew / Operator',
      placeholder: 'Who pilots or commands it?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'capabilities',
      label: 'Capabilities',
      placeholder: 'Speed, weapons, special functions...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'origin',
      label: 'Origin',
      placeholder: 'Who built it? Where?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'currentStatus',
      label: 'Current Status',
      placeholder: 'Active, destroyed, legendary...',
      type: 'input',
      metadataKey: true,
    },
  ],
  technology: [
    {
      key: 'techType',
      label: 'Type',
      placeholder: 'e.g. Weapon, Communication, Energy, Transport',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'inventor',
      label: 'Inventor / Origin',
      placeholder: 'Who created it?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'howItWorks',
      label: 'How It Works',
      placeholder: 'Mechanism, principles, rules...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'limitations',
      label: 'Limitations',
      placeholder: 'Costs, weaknesses, side effects...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'users',
      label: 'Primary Users',
      placeholder: 'Who uses this technology?',
      type: 'input',
      metadataKey: true,
    },
  ],
  // ── Visual-language kinds — PRD 5 ──────────────────────────────────
  moodboard: [
    {
      key: 'referenceImages',
      label: 'Reference Image URLs',
      placeholder: 'One URL per line — drop in Pinterest, Unsplash, IPFS, or LOAR upload URLs...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'tags',
      label: 'Tags',
      placeholder: 'neon, overcast, low-contrast, wet streets',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'notes',
      label: 'Notes on the Mood',
      placeholder: 'What feel should generators pull from this board?',
      type: 'textarea',
      metadataKey: true,
    },
  ],
  style_pack: [
    {
      key: 'basePreset',
      label: 'Base Preset',
      placeholder: 'anime, gritty-scifi, graphic-novel, clay, painterly, vhs...',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'stylePrompt',
      label: 'Style Prompt',
      placeholder: 'e.g. hand-drawn ink linework, heavy shadow, muted palette, grainy film texture',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'negativePrompt',
      label: 'Negative Prompt',
      placeholder: 'what this look avoids — smooth render, photoreal, 3D...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'styleKeywords',
      label: 'Style Keywords',
      placeholder: 'ink lines, rim light, matte colors',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'referenceImages',
      label: 'Reference Image URLs',
      placeholder: 'One URL per line — images that define this pack',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'defaultStrength',
      label: 'Default Strength (0.0 – 1.0)',
      placeholder: '0.7',
      type: 'input',
      metadataKey: true,
    },
  ],
  organization: [
    {
      key: 'orgType',
      label: 'Type',
      placeholder: 'e.g. Government, Secret Society, Corporation',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'purpose',
      label: 'Purpose',
      placeholder: 'What is this organization for?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'structure',
      label: 'Structure',
      placeholder: 'Hierarchy, leadership, ranks...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'members',
      label: 'Notable Members',
      placeholder: 'Key figures...',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'influence',
      label: 'Influence / Reach',
      placeholder: 'How much power do they have?',
      type: 'textarea',
      metadataKey: true,
    },
  ],
  // ── Structural / ontology kinds ─────────────────────────────────
  timeline: [
    {
      key: 'era',
      label: 'Era / Age',
      placeholder: 'e.g. The First Age, Year Zero, Post-Collapse',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'scope',
      label: 'Scope',
      placeholder: 'What does this timeline cover?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'branchingPoint',
      label: 'Branching Point',
      placeholder: 'What divergence created this timeline?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'keyEvents',
      label: 'Key Events',
      placeholder: 'Major milestones in this timeline...',
      type: 'textarea',
      metadataKey: true,
    },
  ],
  reality: [
    {
      key: 'designation',
      label: 'Designation',
      placeholder: 'e.g. Earth-616, Prime Reality, Mirror World',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'divergence',
      label: 'Point of Divergence',
      placeholder: 'What makes this reality different?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'physicalLaws',
      label: 'Physical Laws',
      placeholder: 'How do the rules differ from baseline?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'accessibility',
      label: 'Accessibility',
      placeholder: 'How can this reality be reached?',
      type: 'input',
      metadataKey: true,
    },
  ],
  dimension: [
    {
      key: 'dimensionType',
      label: 'Type',
      placeholder: 'e.g. Pocket Dimension, Astral Layer, Fold Space',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'properties',
      label: 'Properties',
      placeholder: 'What are the defining characteristics?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'inhabitants',
      label: 'Inhabitants',
      placeholder: 'What lives here?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'entryPoints',
      label: 'Entry Points',
      placeholder: 'How do you get in and out?',
      type: 'textarea',
      metadataKey: true,
    },
  ],
  plane: [
    {
      key: 'planeType',
      label: 'Type',
      placeholder: 'e.g. Elemental, Spirit, Shadow, Ethereal',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'environment',
      label: 'Environment',
      placeholder: 'What does it look and feel like?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'rulers',
      label: 'Rulers / Powers',
      placeholder: 'Who or what governs this plane?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'effects',
      label: 'Effects on Visitors',
      placeholder: 'What happens to mortals who enter?',
      type: 'textarea',
      metadataKey: true,
    },
  ],
  realm: [
    {
      key: 'realmType',
      label: 'Type',
      placeholder: 'e.g. Kingdom, Empire, City-State, Wild Territory',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'ruler',
      label: 'Ruler',
      placeholder: 'Who rules this realm?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'geography',
      label: 'Geography',
      placeholder: 'Terrain, climate, key landmarks...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'culture',
      label: 'Culture',
      placeholder: 'Customs, laws, way of life...',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'resources',
      label: 'Resources',
      placeholder: 'What does this realm produce or control?',
      type: 'textarea',
      metadataKey: true,
    },
  ],
  domain: [
    {
      key: 'domainType',
      label: 'Type',
      placeholder: 'e.g. District, Estate, Province, Stronghold',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'controller',
      label: 'Controller',
      placeholder: 'Who controls this domain?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'purpose',
      label: 'Purpose',
      placeholder: 'What is this domain used for?',
      type: 'textarea',
      metadataKey: true,
    },
    {
      key: 'boundaries',
      label: 'Boundaries',
      placeholder: 'What defines its borders?',
      type: 'input',
      metadataKey: true,
    },
    {
      key: 'notableFeatures',
      label: 'Notable Features',
      placeholder: 'Landmarks, defenses, secrets...',
      type: 'textarea',
      metadataKey: true,
    },
  ],
};
